package com.mtc.mapper.app;

import com.mtc.entity.app.SBChickenStandar;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SBChickenStandarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_chicken_standar
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("farmId") Integer farmId, @Param("feedType") String feedType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_chicken_standar
     *
     * @mbggenerated
     */
    int insert(SBChickenStandar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_chicken_standar
     *
     * @mbggenerated
     */
    SBChickenStandar selectByPrimaryKey(@Param("id") Integer id, @Param("farmId") Integer farmId, @Param("feedType") String feedType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_chicken_standar
     *
     * @mbggenerated
     */
    List<SBChickenStandar> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_chicken_standar
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SBChickenStandar record);
}