package com.mtc.mapper.app;

import com.mtc.entity.app.SBDayageTemp;
import java.util.List;

public interface SBDayageTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_dayage_temp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uidNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_dayage_temp
     *
     * @mbggenerated
     */
    int insert(SBDayageTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_dayage_temp
     *
     * @mbggenerated
     */
    SBDayageTemp selectByPrimaryKey(Integer uidNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_dayage_temp
     *
     * @mbggenerated
     */
    List<SBDayageTemp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_dayage_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SBDayageTemp record);
}