package com.mtc.mapper.app;

import com.mtc.entity.app.SBEggSells;

import java.util.Date;
import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SBEggSellsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_egg_sells
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("farmId") Integer farmId, @Param("sellDate") Date sellDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_egg_sells
     *
     * @mbggenerated
     */
    int insert(SBEggSells record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_egg_sells
     *
     * @mbggenerated
     */
    SBEggSells selectByPrimaryKey(@Param("farmId") Integer farmId, @Param("sellDate") Date sellDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_egg_sells
     *
     * @mbggenerated
     */
    List<SBEggSells> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_egg_sells
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SBEggSells record);
    
    
}