package com.mtc.mapper.app;

import com.mtc.entity.app.SBFarmTask;
import java.util.List;

public interface SBFarmTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_farm_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_farm_task
     *
     * @mbggenerated
     */
    int insert(SBFarmTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_farm_task
     *
     * @mbggenerated
     */
    SBFarmTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_farm_task
     *
     * @mbggenerated
     */
    List<SBFarmTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_farm_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SBFarmTask record);
}