package com.mtc.mapper.app;

import com.mtc.entity.app.SBLayerFarmBreed;
import java.util.List;

public interface SBLayerFarmBreedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_layer_farm_breed
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_layer_farm_breed
     *
     * @mbggenerated
     */
    int insert(SBLayerFarmBreed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_layer_farm_breed
     *
     * @mbggenerated
     */
    SBLayerFarmBreed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_layer_farm_breed
     *
     * @mbggenerated
     */
    List<SBLayerFarmBreed> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_layer_farm_breed
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SBLayerFarmBreed record);
}