package com.mtc.mapper.app;

import com.mtc.entity.app.SBUserHouse;
import java.util.List;

public interface SBUserHouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_user_house
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_user_house
     *
     * @mbggenerated
     */
    int insert(SBUserHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_user_house
     *
     * @mbggenerated
     */
    SBUserHouse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_user_house
     *
     * @mbggenerated
     */
    List<SBUserHouse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_user_house
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SBUserHouse record);
}