package com.mtc.mapper.app;

import com.mtc.entity.app.SBUserFarm;
import java.util.List;

public interface SBUserFarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_user_farm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_user_farm
     *
     * @mbggenerated
     */
    int insert(SBUserFarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_user_farm
     *
     * @mbggenerated
     */
    SBUserFarm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_user_farm
     *
     * @mbggenerated
     */
    List<SBUserFarm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_user_farm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SBUserFarm record);
}