package com.mtc.mapper.app;

import com.mtc.entity.app.SDTask;
import java.util.List;

public interface SDTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String taskCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_task
     *
     * @mbggenerated
     */
    int insert(SDTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_task
     *
     * @mbggenerated
     */
    SDTask selectByPrimaryKey(String taskCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_task
     *
     * @mbggenerated
     */
    List<SDTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SDTask record);
}