/*zdyz更新*/
/*alter table s_b_dayage_setting_sub add COLUMN high_humidity_warning decimal(20,6) DEFAULT NULL COMMENT '高报湿度阈值';*/
/*alter table s_b_dayage_setting_sub add COLUMN low_humidity_warning decimal(20,6) DEFAULT NULL COMMENT '低报湿度阈值';*/
/*alter table s_b_dayage_setting_sub add COLUMN high_negative_pressure_warning decimal(20,6) DEFAULT NULL COMMENT '高报负压阈值';*/
/*alter table s_b_dayage_setting_sub add COLUMN low_negative_pressure_warning decimal(20,6) DEFAULT NULL COMMENT '低报负压阈值';*/


/*alter table s_b_dayage_temp_sub add COLUMN high_humidity_warning decimal(20,6) DEFAULT NULL COMMENT '高报湿度阈值';*/
/*alter table s_b_dayage_temp_sub add COLUMN low_humidity_warning decimal(20,6) DEFAULT NULL COMMENT '低报湿度阈值';*/
/*alter table s_b_dayage_temp_sub add COLUMN high_negative_pressure_warning decimal(20,6) DEFAULT NULL COMMENT '高报负压阈值';*/
/*alter table s_b_dayage_temp_sub add COLUMN low_negative_pressure_warning decimal(20,6) DEFAULT NULL COMMENT '低报负压阈值';*/



drop table if exists s_d_user_change;

/*==============================================================*/
/* Table: s_d_user_change                                       */
/*==============================================================*/
create table s_d_user_change
(
   id                   int not null auto_increment,
   user_id              int not null comment '用户id',
   change_type          int comment '1.名称变更
            2.密码变更
            3.手机变更
            4.邮箱变更
            5.冻结变更
            6.删除变更',
   bef_change           varchar(100) comment '变更前内容',
   after_change         varchar(100) comment '变更后内容',
   create_person        int not null comment '创建人',
   create_date          datetime not null comment '创建日期',
   create_time          timestamp not null comment '创建时间',
   primary key (id)
);


drop table if exists s_b_growing_setting_sub;

/*==============================================================*/
/* Table: s_b_growing_setting_sub                               */
/*==============================================================*/
create table s_b_growing_setting_sub
(
   id                   int not null auto_increment comment '序号',
   variety_id           int comment '品种id',
   variety              varchar(50) comment '品种',
   grow_week_age        int comment '生长周龄',
   female_week_avg_weed_out_alarm_rate numeric(20,6) comment '周母鸡平均死淘率报警百分比',
   female_week_avg_weed_out_warm_rate numeric(20,6) comment '周母鸡平均死淘率阈警百分比',
   female_week_avg_weed_out_high_alarm numeric(20,6) comment '周母鸡平均死淘率高报警值',
   female_week_avg_weed_out_low_alarm numeric(20,6) comment '周母鸡平均死淘率低报警值',
   female_week_avg_weed_out_high_warm numeric(20,6) comment '周母鸡平均死淘率高阈警值',
   female_week_avg_weed_out_low_warm numeric(20,6) comment '周母鸡平均死淘率低阈警值',
   female_week_total_weed_out_alarm_rate numeric(20,6) comment '母鸡累计死淘率报警百分比',
   female_week_total_weed_out_warm_rate numeric(20,6) comment '母鸡累计死淘率阈警百分比',
   female_week_total_weed_out_high_alarm numeric(20,6) comment '母鸡累计死淘率高报警值',
   female_week_total_weed_out_low_alarm numeric(20,6) comment '母鸡累计死淘率低报警值',
   female_week_total_weed_out_high_warm numeric(20,6) comment '母鸡累计死淘率高阈警值',
   female_week_total_weed_out_low_warm numeric(20,6) comment '母鸡累计死淘率低阈警值',
   female_life_alarm_rate numeric(20,6) comment '母鸡成活率报警百分比',
   female_life_warm_rate numeric(20,6) comment '母鸡成活率阈警百分比',
   female_life_high_alarm numeric(20,6) comment '母鸡成活率高报警值',
   female_life_low_alarm numeric(20,6) comment '母鸡成活率低报警值',
   female_life_high_warm numeric(20,6) comment '母鸡成活率高阈警值',
   female_life_low_warm numeric(20,6) comment '母鸡成活率低阈警值',
   male_weight_alarm_rate numeric(20,6) comment '公的均重报警百分比',
   male_weight_warm_rate numeric(20,6) comment '公的均重阈警百分比',
   male_weight_high_alarm numeric(20,6) comment '公的均重高报警值',
   male_weight_low_alarm numeric(20,6) comment '公的均重低报警值',
   male_weight_high_warm numeric(20,6) comment '公的均重高阈警值',
   male_weight_low_warm numeric(20,6) comment '公的均重低阈警值',
   female_weight_alarm_rate numeric(20,6) comment '母的均重报警百分比',
   female_weight_warm_rate numeric(20,6) comment '母的均重阈警百分比',
   female_weight_high_alarm numeric(20,6) comment '母的均重高报警值',
   female_weight_low_alarm numeric(20,6) comment '母的均重低报警值',
   female_weight_high_warm numeric(20,6) comment '母的均重高阈警值',
   female_weight_low_warm numeric(20,6) comment '母的均重低阈警值',
   avg_feed_daliy_alarm_rate numeric(20,6) comment '天平均饲料耗量报警百分比',
   avg_feed_daliy_warm_rate numeric(20,6) comment '天平均饲料耗量阈警百分比',
   avg_feed_daliy_high_alarm numeric(20,6) comment '天平均饲料耗量高报警值',
   avg_feed_daliy_low_alarm numeric(20,6) comment '天平均饲料耗量低报警值',
   avg_feed_daliy_high_warm numeric(20,6) comment '天平均饲料耗量高阈警值',
   avg_feed_daliy_low_warm numeric(20,6) comment '天平均饲料耗量低阈警值',
   total_feed_alarm_rate numeric(20,6) comment '累计饲料耗量报警百分比',
   total_feed_warm_rate numeric(20,6) comment '累计饲料耗量阈警百分比',
   total_feed_high_alarm numeric(20,6) comment '累计饲料耗量高报警值',
   total_feed_low_alarm numeric(20,6) comment '累计饲料耗量低报警值',
   total_feed_high_warm numeric(20,6) comment '累计饲料耗量高阈警值',
   total_feed_low_warm  numeric(20,6) comment '累计饲料耗量低阈警值',
   evenness_alarm_rate  numeric(20,6) comment '均匀度报警百分比',
   evenness_warm_rate   numeric(20,6) comment '均匀度阈警百分比',
   evenness_high_alarm  numeric(20,6) comment '均匀度高报警值',
   evenness_low_alarm   numeric(20,6) comment '均匀度低报警值',
   evenness_high_warm   numeric(20,6) comment '均匀度高阈警值',
   evenness_low_warm    numeric(20,6) comment '均匀度低阈警值',
   female_max_std_weight_alarm_rate numeric(20,6) comment '母鸡最大标准体重报警百分比',
   female_max_std_weight_warm_rate numeric(20,6) comment '母鸡最大标准体重阈警百分比',
   female_max_std_weight_high_alarm numeric(20,6) comment '母鸡最大标准体重高报警值',
   female_max_std_weight_low_alarm numeric(20,6) comment '母鸡最大标准体重低报警值',
   female_max_std_weight_high_warm numeric(20,6) comment '母鸡最大标准体重高阈警值',
   female_max_std_weight_low_warm numeric(20,6) comment '母鸡最大标准体重低阈警值',
   female_min_std_weight_alarm_rate numeric(20,6) comment '母鸡最小标准体重报警百分比',
   female_min_std_weight_warm_rate numeric(20,6) comment '母鸡最小标准体重阈警百分比',
   female_min_std_weight_high_alarm numeric(20,6) comment '母鸡最小标准体重高报警值',
   female_min_std_weight_low_alarm numeric(20,6) comment '母鸡最小标准体重低报警值',
   female_min_std_weight_high_warm numeric(20,6) comment '母鸡最小标准体重高阈警值',
   female_min_std_weight_low_warm numeric(20,6) comment '母鸡最小标准体重低阈警值',
   create_person        int comment '创建人',
   create_date          datetime comment '创建日期',
   create_time          timestamp comment '创建时间',
   modify_person        int,
   modify_date          datetime comment '创建日期',
   modify_time          datetime,
   primary key (id)
);

drop table if exists s_b_lay_egg_setting_sub;

/*==============================================================*/
/* Table: s_b_lay_egg_setting_sub                               */
/*==============================================================*/
create table s_b_lay_egg_setting_sub
(
   id                   int not null auto_increment comment '序号',
   variety_id           int comment '品种id',
   variety              varchar(50) comment '品种',
   grow_week_age        int comment '生长周龄',
   lay_egg_week_age     int comment '生产周龄',
   female_week_avg_weed_out_alarm_rate numeric(20,6) comment '周母鸡平均死淘率报警百分比',
   female_week_avg_weed_out_warm_rate numeric(20,6) comment '周母鸡平均死淘率阈警百分比',
   female_week_avg_weed_out_high_alarm numeric(20,6) comment '周母鸡平均死淘率高报警值',
   female_week_avg_weed_out_low_alarm numeric(20,6) comment '周母鸡平均死淘率低报警值',
   female_week_avg_weed_out_high_warm numeric(20,6) comment '周母鸡平均死淘率高阈警值',
   female_week_avg_weed_out_low_warm numeric(20,6) comment '周母鸡平均死淘率低阈警值',
   female_week_total_weed_out_alarm_rate numeric(20,6) comment '母鸡累计死淘率报警百分比',
   female_week_total_weed_out_warm_rate numeric(20,6) comment '母鸡累计死淘率阈警百分比',
   female_week_total_weed_out_high_alarm numeric(20,6) comment '母鸡累计死淘率高报警值',
   female_week_total_weed_out_low_alarm numeric(20,6) comment '母鸡累计死淘率低报警值',
   female_week_total_weed_out_high_warm numeric(20,6) comment '母鸡累计死淘率高阈警值',
   female_week_total_weed_out_low_warm numeric(20,6) comment '母鸡累计死淘率低阈警值',
   female_life_alarm_rate numeric(20,6) comment '母鸡成活率报警百分比',
   female_life_warm_rate numeric(20,6) comment '母鸡成活率阈警百分比',
   female_life_high_alarm numeric(20,6) comment '母鸡成活率高报警值',
   female_life_low_alarm numeric(20,6) comment '母鸡成活率低报警值',
   female_life_high_warm numeric(20,6) comment '母鸡成活率高阈警值',
   female_life_low_warm numeric(20,6) comment '母鸡成活率低阈警值',
   male_weight_alarm_rate numeric(20,6) comment '公的均重报警百分比',
   male_weight_warm_rate numeric(20,6) comment '公的均重阈警百分比',
   male_weight_high_alarm numeric(20,6) comment '公的均重高报警值',
   male_weight_low_alarm numeric(20,6) comment '公的均重低报警值',
   male_weight_high_warm numeric(20,6) comment '公的均重高阈警值',
   male_weight_low_warm numeric(20,6) comment '公的均重低阈警值',
   female_weight_alarm_rate numeric(20,6) comment '母的均重报警百分比',
   female_weight_warm_rate numeric(20,6) comment '母的均重阈警百分比',
   female_weight_high_alarm numeric(20,6) comment '母的均重高报警值',
   female_weight_low_alarm numeric(20,6) comment '母的均重低报警值',
   female_weight_high_warm numeric(20,6) comment '母的均重高阈警值',
   female_weight_low_warm numeric(20,6) comment '母的均重低阈警值',
   cl_laying_rate_alarm_rate numeric(20,6) comment '存栏产蛋率报警百分比',
   cl_laying_rate_warm_rate numeric(20,6) comment '存栏产蛋率阈警百分比',
   cl_laying_rate_high_alarm numeric(20,6) comment '存栏产蛋率高报警值',
   cl_laying_rate_low_alarm numeric(20,6) comment '存栏产蛋率低报警值',
   cl_laying_rate_high_warm numeric(20,6) comment '存栏产蛋率低报警值',
   cl_laying_rate_low_warm numeric(20,6) comment '存栏产蛋率低阈警值',
   rs_laying_rate_alarm_rate numeric(20,6) comment '入舍产蛋率报警百分比',
   rs_laying_rate_warm_rate numeric(20,6) comment '入舍产蛋率阈警百分比',
   rs_laying_rate_high_alarm numeric(20,6) comment '入舍产蛋率高报警值',
   rs_laying_rate_low_alarm numeric(20,6) comment '入舍产蛋率低报警值',
   rs_laying_rate_high_warm numeric(20,6) comment '入舍产蛋率高阈警值',
   rs_laying_rate_low_warm numeric(20,6) comment '入舍产蛋率低阈警值',
   rs_female_laying_avg_count_alarm_rate numeric(20,6) comment '入舍母鸡周平均产蛋数报警百分比',
   rs_female_laying_avg_count_warm_rate numeric(20,6) comment '入舍母鸡周平均产蛋数阈警百分比',
   rs_female_laying_avg_count_high_alarm numeric(20,6) comment '入舍母鸡周平均产蛋数高报警值',
   rs_female_laying_avg_count_low_alarm numeric(20,6) comment '入舍母鸡周平均产蛋数低报警值',
   rs_female_laying_avg_count_high_warm numeric(20,6) comment '入舍母鸡周平均产蛋数高阈警值',
   rs_female_laying_avg_count_low_warm numeric(20,6) comment '入舍母鸡周平均产蛋数低阈警值',
   rs_female_laying_total_count_alarm_rate numeric(20,6) comment '入舍母鸡总产蛋数报警百分比',
   rs_female_laying_total_count_warm_rate numeric(20,6) comment '入舍母鸡总产蛋数阈警百分比',
   rs_female_laying_total_count_high_alarm numeric(20,6) comment '入舍母鸡总产蛋数高报警值',
   rs_female_laying_total_count_low_alarm numeric(20,6) comment '入舍母鸡总产蛋数低报警值',
   rs_female_laying_total_count_high_warm numeric(20,6) comment '入舍母鸡总产蛋数高阈警值',
   rs_female_laying_total_count_low_warm numeric(20,6) comment '入舍母鸡总产蛋数低阈警值',
   qualified_egg_rate_alarm_rate numeric(20,6) comment '合格种蛋率报警百分比',
   qualified_egg_rate_warm_rate numeric(20,6) comment '合格种蛋率阈警百分比',
   qualified_egg_rate_high_alarm numeric(20,6) comment '合格种蛋率高报警值',
   qualified_egg_rate_low_alarm numeric(20,6) comment '合格种蛋率低报警值',
   qualified_egg_rate_high_warm numeric(20,6) comment '合格种蛋率高阈警值',
   qualified_egg_rate_low_warm numeric(20,6) comment '合格种蛋率低阈警值',
   rs_female_avg_qualified_count_alarm_rate numeric(20,6) comment '入舍母鸡周平均产合格种蛋数报警百分比',
   rs_female_avg_qualified_count_warm_rate numeric(20,6) comment '入舍母鸡周平均产合格种蛋数阈警百分比',
   rs_female_avg_qualified_count_high_alarm numeric(20,6) comment '入舍母鸡周平均产合格种蛋数高报警值',
   rs_female_avg_qualified_count_low_alarm numeric(20,6) comment '入舍母鸡周平均产合格种蛋数低报警值',
   rs_female_avg_qualified_count_high_warm numeric(20,6) comment '入舍母鸡周平均产合格种蛋数高阈警值',
   rs_female_avg_qualified_count_low_warm numeric(20,6) comment '入舍母鸡周平均产合格种蛋数低阈警值',
   rs_female_total_qualified_count_alarm_rate numeric(20,6) comment '入舍母鸡总产合格种蛋数报警百分比',
   rs_female_total_qualified_count_warm_rate numeric(20,6) comment '入舍母鸡总产合格种蛋数阈警百分比',
   rs_female_total_qualified_count_high_alarm numeric(20,6) comment '入舍母鸡总产合格种蛋数高报警值',
   rs_female_total_qualified_count_low_alarm numeric(20,6) comment '入舍母鸡总产合格种蛋数低报警值',
   rs_female_total_qualified_count_high_warm numeric(20,6) comment '入舍母鸡总产合格种蛋数高阈警值',
   rs_female_total_qualified_count_low_warm numeric(20,6) comment '入舍母鸡总产合格种蛋数低阈警值',
   chick_hatching_rate_alarm_rate numeric(20,6) comment '雏鸡孵化率报警百分比',
   chick_hatching_rate_warm_rate numeric(20,6) comment '雏鸡孵化率阈警百分比',
   chick_hatching_rate_high_alarm numeric(20,6) comment '雏鸡孵化率高报警值',
   chick_hatching_rate_low_alarm numeric(20,6) comment '雏鸡孵化率低报警值',
   chick_hatching_rate_high_warm numeric(20,6) comment '雏鸡孵化率高阈警值',
   chick_hatching_rate_low_warm numeric(20,6) comment '雏鸡孵化率低阈警值',
   breeding_chick_hatching_alarm_rate numeric(20,6) comment '种雏孵化率报警百分比',
   breeding_chick_hatching_warm_rate numeric(20,6) comment '种雏孵化率阈警百分比',
   breeding_chick_hatching_high_alarm numeric(20,6) comment '种雏孵化率高报警值',
   breeding_chick_hatching_low_alarm numeric(20,6) comment '种雏孵化率低报警值',
   breeding_chick_hatching_high_warm numeric(20,6) comment '种雏孵化率高阈警值',
   breeding_chick_hatching_low_warm numeric(20,6) comment '种雏孵化率低阈警值',
   breeding_chick_avg_count_alarm_rate numeric(20,6) comment '种雏周平均数报警百分比',
   breeding_chick_avg_count_warm_rate numeric(20,6) comment '种雏周平均数阈警百分比',
   breeding_chick_avg_count_high_alarm numeric(20,6) comment '种雏周平均数高报警值',
   breeding_chick_avg_count_low_alarm numeric(20,6) comment '种雏周平均数低报警值',
   breeding_chick_avg_count_high_warm numeric(20,6) comment '种雏周平均数高阈警值',
   breeding_chick_avg_count_low_warm numeric(20,6) comment '种雏周平均数低阈警值',
   breeding_chick_total_count_alarm_rate numeric(20,6) comment '种雏累计数报警百分比',
   breeding_chick_total_count_warm_rate numeric(20,6) comment '种雏累计数阈警百分比',
   breeding_chick_total_count_high_alarm numeric(20,6) comment '种雏累计数高报警值',
   breeding_chick_total_count_low_alarm numeric(20,6) comment '种雏累计数低报警值',
   breeding_chick_total_count_high_warm numeric(20,6) comment '种雏累计数高阈警值',
   breeding_chick_total_count_low_warm numeric(20,6) comment '种雏累计数低阈警值',
   avg_feed_daliy_alarm_rate numeric(20,6) comment '天平均饲料耗量报警百分比',
   avg_feed_daliy_warm_rate numeric(20,6) comment '天平均饲料耗量阈警百分比',
   avg_feed_daliy_high_alarm numeric(20,6) comment '天平均饲料耗量高报警值',
   avg_feed_daliy_low_alarm numeric(20,6) comment '天平均饲料耗量低报警值',
   avg_feed_daliy_high_warm numeric(20,6) comment '天平均饲料耗量高阈警值',
   avg_feed_daliy_low_warm numeric(20,6) comment '天平均饲料耗量低阈警值',
   total_feed_alarm_rate numeric(20,6) comment '只累计耗料报警百分比',
   total_feed_warm_rate numeric(20,6) comment '只累计耗料阈警百分比',
   total_feed_high_alarm numeric(20,6) comment '只累计耗料高报警值',
   total_feed_low_alarm numeric(20,6) comment '只累计耗料低报警值',
   total_feed_high_warm numeric(20,6) comment '只累计耗料高阈警值',
   total_feed_low_warm  numeric(20,6) comment '只累计耗料低阈警值',
   create_person        int comment '创建人',
   create_date          datetime comment '创建日期',
   create_time          timestamp comment '创建时间',
   modify_person        int,
   modify_date          datetime comment '创建日期',
   modify_time          datetime,
   primary key (id)
);


drop table if exists s_b_meat_setting_sub;

/*==============================================================*/
/* Table: s_b_meat_setting_sub                                  */
/*==============================================================*/
create table s_b_meat_setting_sub
(
   id                   int not null auto_increment comment '序号',
   variety_id           int comment '品种id',
   variety              varchar(50) comment '品种',
   grow_age             int comment '生长日龄',
   female_avg_weed_out_alarm_rate numeric(20,6) comment '母鸡平均死淘率报警百分比',
   female_avg_weed_out_warm_rate numeric(20,6) comment '母鸡平均死淘率阈警百分比',
   female_avg_weed_out_high_alarm numeric(20,6) comment '母鸡平均死淘率高报警值',
   female_avg_weed_out_low_alarm numeric(20,6) comment '母鸡平均死淘率低报警值',
   female_avg_weed_out_high_warm numeric(20,6) comment '母鸡平均死淘率高阈警值',
   female_avg_weed_out_low_warm numeric(20,6) comment '母鸡平均死淘率低阈警值',
   female_total_weed_out_alarm_rate numeric(20,6) comment '母鸡累计死淘率报警百分比',
   female_total_weed_out_warm_rate numeric(20,6) comment '母鸡累计死淘率阈警百分比',
   female_total_weed_out_high_alarm numeric(20,6) comment '母鸡累计死淘率高报警值',
   female_total_weed_out_low_alarm numeric(20,6) comment '母鸡累计死淘率低报警值',
   female_total_weed_out_high_warm numeric(20,6) comment '母鸡累计死淘率高阈警值',
   female_total_weed_out_low_warm numeric(20,6) comment '母鸡累计死淘率低阈警值',
   male_avg_weed_out_alarm_rate numeric(20,6) comment '公鸡平均死淘率报警百分比',
   male_avg_weed_out_warm_rate numeric(20,6) comment '公鸡平均死淘率阈警百分比',
   male_avg_weed_out_high_alarm numeric(20,6) comment '公鸡平均死淘率高报警值',
   male_avg_weed_out_low_alarm numeric(20,6) comment '公鸡平均死淘率低报警值',
   male_avg_weed_out_high_warm numeric(20,6) comment '公鸡平均死淘率高阈警值',
   male_avg_weed_out_low_warm numeric(20,6) comment '公鸡平均死淘率低阈警值',
   male_total_weed_out_alarm_rate numeric(20,6) comment '公鸡累计死淘率报警百分比',
   male_total_weed_out_warm_rate numeric(20,6) comment '公鸡累计死淘率阈警百分比',
   male_total_weed_out_high_alarm numeric(20,6) comment '公鸡累计死淘率高报警值',
   male_total_weed_out_low_alarm numeric(20,6) comment '公鸡累计死淘率低报警值',
   male_total_weed_out_high_warm numeric(20,6) comment '公鸡累计死淘率高阈警值',
   male_total_weed_out_low_warm numeric(20,6) comment '公鸡累计死淘率低阈警值',
   male_weight_alarm_rate numeric(20,6) comment '公的均重报警百分比',
   male_weight_warm_rate numeric(20,6) comment '公的均重阈警百分比',
   male_weight_high_alarm numeric(20,6) comment '公的均重高报警值',
   male_weight_low_alarm numeric(20,6) comment '公的均重低报警值',
   male_weight_high_warm numeric(20,6) comment '公的均重高阈警值',
   male_weight_low_warm numeric(20,6) comment '公的均重低阈警值',
   female_weight_alarm_rate numeric(20,6) comment '母的均重报警百分比',
   female_weight_warm_rate numeric(20,6) comment '母的均重阈警百分比',
   female_weight_high_alarm numeric(20,6) comment '母的均重高报警值',
   female_weight_low_alarm numeric(20,6) comment '母的均重低报警值',
   female_weight_high_warm numeric(20,6) comment '母的均重高阈警值',
   female_weight_low_warm numeric(20,6) comment '母的均重低阈警值',
   male_feed_daliy_alarm_rate numeric(20,6) comment '公只日采食量报警百分比',
   male_feed_daliy_warm_rate numeric(20,6) comment '公只日采食量阈警百分比',
   male_feed_daliy_high_alarm numeric(20,6) comment '公只日采食量高报警值',
   male_feed_daliy_low_alarm numeric(20,6) comment '公只日采食量低报警值',
   male_feed_daliy_high_warm numeric(20,6) comment '公只日采食量高阈警值',
   male_feed_daliy_low_warm numeric(20,6) comment '公只日采食量低阈警值',
   female_feed_daliy_alarm_rate numeric(20,6) comment '母只日采食量报警百分比',
   female_feed_daliy_warm_rate numeric(20,6) comment '母只日采食量阈警百分比',
   female_feed_daliy_high_alarm numeric(20,6) comment '母只日采食量高报警值',
   female_feed_daliy_low_alarm numeric(20,6) comment '母只日采食量低报警值',
   female_feed_daliy_high_warm numeric(20,6) comment '母只日采食量高阈警值',
   female_feed_daliy_low_warm numeric(20,6) comment '母只日采食量低阈警值',
   female_total_feed_alarm_rate numeric(20,6) comment '母累计饲料耗量报警百分比',
   female_total_feed_warm_rate numeric(20,6) comment '母累计饲料耗量阈警百分比',
   female_total_feed_high_alarm numeric(20,6) comment '母累计饲料耗量高报警值',
   female_total_feed_low_alarm numeric(20,6) comment '母累计饲料耗量低报警值',
   female_total_feed_high_warm numeric(20,6) comment '母累计饲料耗量高阈警值',
   female_total_feed_low_warm numeric(20,6) comment '母累计饲料耗量低阈警值',
   male_total_feed_alarm_rate numeric(20,6) comment '公累计饲料耗量报警百分比',
   male_total_feed_warm_rate numeric(20,6) comment '公累计饲料耗量阈警百分比',
   male_total_feed_high_alarm numeric(20,6) comment '公累计饲料耗量高报警值',
   male_total_feed_low_alarm numeric(20,6) comment '公累计饲料耗量低报警值',
   male_total_feed_high_warm numeric(20,6) comment '公累计饲料耗量高阈警值',
   male_total_feed_low_warm numeric(20,6) comment '公累计饲料耗量低阈警值',
   create_person        int comment '创建人',
   create_date          datetime comment '创建日期',
   create_time          timestamp comment '创建时间',
   modify_person        int,
   modify_date          datetime comment '创建日期',
   modify_time          datetime,
   primary key (id)
);
