/**
 *
 * MTC-上海农汇信息科技有限公司
 * Copyright © 2015 农汇 版权所有
 */
package com.mtc.app.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.mtc.entity.app.SDUserOperation;
import com.mtc.mapper.app.SDUserOperationMapper;

/**
 * @ClassName: SDUserOperationService
 * @Description: 用户操作记录
 *  * 
 */
@Service
public class SDUserOperationService {
	/**
	 * 操作类型
	 */
	public static final String OPERATION_SELECT = "SELECT";
	public static final String OPERATION_ADD = "ADD";
	public static final String OPERATION_DELETE = "DELETE";
	public static final String OPERATION_UPDATE = "UPDATE";
	
	/**
	 * code一共5位数字， demo:10001 
	 * 第一位代表所属模块，最后几位代表模块中的子功能
	 * 
	 * 大模块有
	 * 1：基础信息
	 * 2：环控检测
	 * 3：生产日报
	 * 4：任务提醒
	 * 5：数据分析
	 * 6：批次管理
	 * 
	 */
	/** 农场信息**/
	public static final String MENU_FARMINFO = "10001";
	/** 栋舍信息**/
	public static final String MENU_HOUSEINFO = "10002";
	/** 员工信息**/
	public static final String MENU_MEMBERINFO = "10003";
	/** 修改密码**/
	public static final String MENU_PASSWORD = "10004";
	/** 登录**/
	public static final String MENU_LOGIN= "10005";
	/** 语音设置*/
	public static final String MENU_FARM_ALARM_SETTING= "10006";
	
	/** 环控监测**/
	public static final String MENU_ENVIMONITOR = "20001";
	/** 环控监测设置**/
	public static final String MENU_ENVIMONITOR_SETTING = "20002";
	/** 报警延迟处理**/
	public static final String MENU_WARNTREATMENT = "20003";
	/** 报警统计**/
	public static final String MENU_WARNSTATISTICS = "20004";
	/** 报警日志**/
	public static final String MENU_WARNLOG = "20005";
	/** 报警次数堆积图 **/
	public static final String MENU_WARNCOUNTLOG = "20006";

	/** 生产记录**/
	public static final String MENU_PRODUCTION_DAY_INPUT = "30001";
	/** 入雏**/
	public static final String MENU_PRODUCTION_YOUNG = "30002";
	/** 出栏**/
	public static final String MENU_PRODUCTION_OUTPUT = "30003";
	/** 生产日报**/
	public static final String MENU_PRODUCTION_DAILY_REPORT = "30004";
	/** 生产周报**/
	public static final String MENU_PRODUCTION_WEEKLY_REPORT = "30005";
	/** 饲养和用药记录 **/
	public static final String MENU_PRODUCTION_REMARK_REPORT = "30006";


	/** 任务提醒**/
	public static final String MENU_TASK_REMIND = "40001";
	/** 入雏前准备**/
	public static final String MENU_TASK_SETTING_YOUNG_PREPARE = "40002";
	/** 入雏后日常工作**/
	public static final String MENU_TASK_SETTING_YOUNG_DAILY = "40003";
	/** 光照程序**/
	public static final String MENU_TASK_SETTING_LIGHT = "40004";
	/** 免疫用药程序**/
	public static final String MENU_TASK_SETTING_IMMUNE_DRUG = "40005";
	/** 其他临时任务**/
	public static final String MENU_TASK_SETTING_TEMPORARY_TASK = "40006";
	
	/** 数据分析 温度曲线**/
	public static final String MENU_DATAANALYSIS_TEMP = "50001";
	/** 温湿度综合曲线**/
	public static final String MENU_DATAANALYSIS_TEMPHUM = "50002";
	/** 成活率**/
	public static final String MENU_DATAANALYSIS_LIFE = "50003";
	/** 日采食曲线**/
	public static final String MENU_DATAANALYSIS_DAILYFOOD_CURVE = "50004";
	/** 批次报告 **/
	public static final String MENU_DATAANALYSIS_SUMREQ = "50005";
	/** 周体重**/
	public static final String MENU_DATAANALYSIS_WEEKWEIGHT = "50006";
	/** 日死淘率曲线**/
	public static final String MENU_DATAANALYSIS_DAILYDC_CURVE = "50007";
	/** 累计死淘率曲线**/
	public static final String MENU_DATAANALYSIS_ACCDC_CURVE = "50008";
	/** 日饮水曲线**/
	public static final String MENU_DATAANALYSIS_DAILYWARTER_CURVE = "50009";
	/** 点温差曲线**/
	public static final String MENU_DATAANALYSIS_TEMPDIFF = "50010";
	
	/** 农场管理 新建批次**/
	public static final String MENU_FARMMANAGEMENT_ADD = "60001";
	/** 批次结算**/
	public static final String MENU_FARMMANAGEMENT_BALANCE = "60002";
	/** 盈利报告**/
	public static final String MENU_FARMMANAGEMENT_PROFIT = "60003";
	/** 多批盈利查询**/
	public static final String MENU_FARMMANAGEMENT_PROFIT_QUERY = "60004";
	/** 多批结算查询**/
	public static final String MENU_FARMMANAGEMENT_BALANCE_QUERY = "60005";
	/** 设置农场标准*/
	public static final String MENU_FARMMANAGEMENT_SETTING_STANDARD = "60006";
	/** 查询标准数据*/
	public static final String MENU_FARMMANAGEMENT_STANDARD_QUERY = "60007";
	/** 编辑农场标准*/
	public static final String MENU_FARMMANAGEMENT_STANDARD_DIY = "60008";
    /** 入雏*/
    public static final String MENU_FARMMANAGEMENT_PLACE_CHICK = "60009";
    /** 出栏*/
    public static final String MENU_FARMMANAGEMENT_SETTLE_CHICK = "60010";

    /** 效益报告*/
    public static final String MENU_FARMMANAGEMENT_BenefitRep = "60011";
    /** 成本报告*/
    public static final String MENU_FARMMANAGEMENT_CostsRep = "60012";
    /** 结算价格*/
    public static final String MENU_FARMMANAGEMENT_SettlePriceRep = "60013";

		
	@Autowired
	private SDUserOperationMapper operationMapper ;
	
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_user_operation
     *
     * @mbggenerated
     */
    public int insert(SDUserOperation record){
    	return operationMapper.insert(record);
    }
    
    /**
     * 
     * 插入用户操作记录
     * 
     * @param menuCode
     * @param poerationType
     * @param personId
     * @return
     */
    public int insert(String menuCode,String poerationType,int personId){
    	SDUserOperation record = new SDUserOperation();
		//record.setCreateTime(new Date(System.currentTimeMillis()));
		record.setMenuCode(menuCode);
		record.setOperationType(poerationType);
		record.setPersonId(personId);
    	return insert(record);
    }
	
}









