package com.mtc.mapper.app;

import com.mtc.entity.app.SBAbnormalInfo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SBAbnormalInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_abnormal_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("farmId") Integer farmId, @Param("houseId") Integer houseId, @Param("alarmCode") String alarmCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_abnormal_info
     *
     * @mbggenerated
     */
    int insert(SBAbnormalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_abnormal_info
     *
     * @mbggenerated
     */
    SBAbnormalInfo selectByPrimaryKey(@Param("farmId") Integer farmId, @Param("houseId") Integer houseId, @Param("alarmCode") String alarmCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_abnormal_info
     *
     * @mbggenerated
     */
    List<SBAbnormalInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_abnormal_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SBAbnormalInfo record);
}