package com.mtc.mapper.app;


import com.mtc.entity.app.SBBbfar;
import java.util.List;

public interface SBBbfarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_bbfar
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_bbfar
     *
     * @mbggenerated
     */
    int insert(SBBbfar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_bbfar
     *
     * @mbggenerated
     */
    SBBbfar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_bbfar
     *
     * @mbggenerated
     */
    List<SBBbfar> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_bbfar
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SBBbfar record);
}