package com.mtc.mapper.app;

import com.mtc.entity.app.SBChickenStandar;
import java.util.List;

public interface SBChickenStandarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_chicken_standar
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_chicken_standar
     *
     * @mbggenerated
     */
    int insert(SBChickenStandar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_chicken_standar
     *
     * @mbggenerated
     */
    SBChickenStandar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_chicken_standar
     *
     * @mbggenerated
     */
    List<SBChickenStandar> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_chicken_standar
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SBChickenStandar record);
}