package com.mtc.mapper.app;

import com.mtc.entity.app.SBFarmSettle;
import java.util.List;

public interface SBFarmSettleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_farm_settle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_farm_settle
     *
     * @mbggenerated
     */
    int insert(SBFarmSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_farm_settle
     *
     * @mbggenerated
     */
    SBFarmSettle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_farm_settle
     *
     * @mbggenerated
     */
    List<SBFarmSettle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_farm_settle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SBFarmSettle record);
}