package com.mtc.mapper.app;

import com.mtc.entity.app.SDCode;
import java.util.List;

public interface SDCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_code
     *
     * @mbggenerated
     */
    int insert(SDCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_code
     *
     * @mbggenerated
     */
    SDCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_code
     *
     * @mbggenerated
     */
    List<SDCode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SDCode record);
}