package com.mtc.mapper.app;

import com.mtc.entity.app.SDFarm;
import java.util.List;

public interface SDFarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_farm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_farm
     *
     * @mbggenerated
     */
    int insert(SDFarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_farm
     *
     * @mbggenerated
     */
    SDFarm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_farm
     *
     * @mbggenerated
     */
    List<SDFarm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_farm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SDFarm record);
}