package com.mtc.mapper.app;

import com.mtc.entity.app.SLUserImei;
import java.util.List;

public interface SLUserImeiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_l_user_imei
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String imeiNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_l_user_imei
     *
     * @mbggenerated
     */
    int insert(SLUserImei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_l_user_imei
     *
     * @mbggenerated
     */
    SLUserImei selectByPrimaryKey(String imeiNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_l_user_imei
     *
     * @mbggenerated
     */
    List<SLUserImei> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_l_user_imei
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SLUserImei record);
}