package com.nh.ifarm.Alidayu.entity;

import java.util.Date;

public class SBCallMain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.sys_code
     *
     * @mbggenerated
     */
    private String sysCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.call_remark
     *
     * @mbggenerated
     */
    private String callRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.template_code
     *
     * @mbggenerated
     */
    private String templateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.max_time
     *
     * @mbggenerated
     */
    private Integer maxTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.call_status
     *
     * @mbggenerated
     */
    private String callStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.result_time
     *
     * @mbggenerated
     */
    private Date resultTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.result_detail
     *
     * @mbggenerated
     */
    private String resultDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.id
     *
     * @return the value of s_b_call_main.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.id
     *
     * @param id the value for s_b_call_main.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.sys_code
     *
     * @return the value of s_b_call_main.sys_code
     *
     * @mbggenerated
     */
    public String getSysCode() {
        return sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.sys_code
     *
     * @param sysCode the value for s_b_call_main.sys_code
     *
     * @mbggenerated
     */
    public void setSysCode(String sysCode) {
        this.sysCode = sysCode == null ? null : sysCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.call_remark
     *
     * @return the value of s_b_call_main.call_remark
     *
     * @mbggenerated
     */
    public String getCallRemark() {
        return callRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.call_remark
     *
     * @param callRemark the value for s_b_call_main.call_remark
     *
     * @mbggenerated
     */
    public void setCallRemark(String callRemark) {
        this.callRemark = callRemark == null ? null : callRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.template_code
     *
     * @return the value of s_b_call_main.template_code
     *
     * @mbggenerated
     */
    public String getTemplateCode() {
        return templateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.template_code
     *
     * @param templateCode the value for s_b_call_main.template_code
     *
     * @mbggenerated
     */
    public void setTemplateCode(String templateCode) {
        this.templateCode = templateCode == null ? null : templateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.max_time
     *
     * @return the value of s_b_call_main.max_time
     *
     * @mbggenerated
     */
    public Integer getMaxTime() {
        return maxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.max_time
     *
     * @param maxTime the value for s_b_call_main.max_time
     *
     * @mbggenerated
     */
    public void setMaxTime(Integer maxTime) {
        this.maxTime = maxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.call_status
     *
     * @return the value of s_b_call_main.call_status
     *
     * @mbggenerated
     */
    public String getCallStatus() {
        return callStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.call_status
     *
     * @param callStatus the value for s_b_call_main.call_status
     *
     * @mbggenerated
     */
    public void setCallStatus(String callStatus) {
        this.callStatus = callStatus == null ? null : callStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.result_time
     *
     * @return the value of s_b_call_main.result_time
     *
     * @mbggenerated
     */
    public Date getResultTime() {
        return resultTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.result_time
     *
     * @param resultTime the value for s_b_call_main.result_time
     *
     * @mbggenerated
     */
    public void setResultTime(Date resultTime) {
        this.resultTime = resultTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.result_detail
     *
     * @return the value of s_b_call_main.result_detail
     *
     * @mbggenerated
     */
    public String getResultDetail() {
        return resultDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.result_detail
     *
     * @param resultDetail the value for s_b_call_main.result_detail
     *
     * @mbggenerated
     */
    public void setResultDetail(String resultDetail) {
        this.resultDetail = resultDetail == null ? null : resultDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.create_time
     *
     * @return the value of s_b_call_main.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.create_time
     *
     * @param createTime the value for s_b_call_main.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.modify_time
     *
     * @return the value of s_b_call_main.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.modify_time
     *
     * @param modifyTime the value for s_b_call_main.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}