package com.mtc.entity.app;

import java.util.Date;

public class SBAbnormalInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_abnormal_info.farm_id
     *
     * @mbggenerated
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_abnormal_info.house_id
     *
     * @mbggenerated
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_abnormal_info.alarm_code
     *
     * @mbggenerated
     */
    private String alarmCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_abnormal_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_abnormal_info.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_abnormal_info.standar_delay
     *
     * @mbggenerated
     */
    private Integer standarDelay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_abnormal_info.deal_status
     *
     * @mbggenerated
     */
    private String dealStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_abnormal_info.deal_delay
     *
     * @mbggenerated
     */
    private Integer dealDelay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_abnormal_info.deal_time
     *
     * @mbggenerated
     */
    private Date dealTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_abnormal_info.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_abnormal_info.farm_id
     *
     * @return the value of s_b_abnormal_info.farm_id
     *
     * @mbggenerated
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_abnormal_info.farm_id
     *
     * @param farmId the value for s_b_abnormal_info.farm_id
     *
     * @mbggenerated
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_abnormal_info.house_id
     *
     * @return the value of s_b_abnormal_info.house_id
     *
     * @mbggenerated
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_abnormal_info.house_id
     *
     * @param houseId the value for s_b_abnormal_info.house_id
     *
     * @mbggenerated
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_abnormal_info.alarm_code
     *
     * @return the value of s_b_abnormal_info.alarm_code
     *
     * @mbggenerated
     */
    public String getAlarmCode() {
        return alarmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_abnormal_info.alarm_code
     *
     * @param alarmCode the value for s_b_abnormal_info.alarm_code
     *
     * @mbggenerated
     */
    public void setAlarmCode(String alarmCode) {
        this.alarmCode = alarmCode == null ? null : alarmCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_abnormal_info.status
     *
     * @return the value of s_b_abnormal_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_abnormal_info.status
     *
     * @param status the value for s_b_abnormal_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_abnormal_info.start_time
     *
     * @return the value of s_b_abnormal_info.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_abnormal_info.start_time
     *
     * @param startTime the value for s_b_abnormal_info.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_abnormal_info.standar_delay
     *
     * @return the value of s_b_abnormal_info.standar_delay
     *
     * @mbggenerated
     */
    public Integer getStandarDelay() {
        return standarDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_abnormal_info.standar_delay
     *
     * @param standarDelay the value for s_b_abnormal_info.standar_delay
     *
     * @mbggenerated
     */
    public void setStandarDelay(Integer standarDelay) {
        this.standarDelay = standarDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_abnormal_info.deal_status
     *
     * @return the value of s_b_abnormal_info.deal_status
     *
     * @mbggenerated
     */
    public String getDealStatus() {
        return dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_abnormal_info.deal_status
     *
     * @param dealStatus the value for s_b_abnormal_info.deal_status
     *
     * @mbggenerated
     */
    public void setDealStatus(String dealStatus) {
        this.dealStatus = dealStatus == null ? null : dealStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_abnormal_info.deal_delay
     *
     * @return the value of s_b_abnormal_info.deal_delay
     *
     * @mbggenerated
     */
    public Integer getDealDelay() {
        return dealDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_abnormal_info.deal_delay
     *
     * @param dealDelay the value for s_b_abnormal_info.deal_delay
     *
     * @mbggenerated
     */
    public void setDealDelay(Integer dealDelay) {
        this.dealDelay = dealDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_abnormal_info.deal_time
     *
     * @return the value of s_b_abnormal_info.deal_time
     *
     * @mbggenerated
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_abnormal_info.deal_time
     *
     * @param dealTime the value for s_b_abnormal_info.deal_time
     *
     * @mbggenerated
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_abnormal_info.modify_time
     *
     * @return the value of s_b_abnormal_info.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_abnormal_info.modify_time
     *
     * @param modifyTime the value for s_b_abnormal_info.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}