package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SBBreedDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.house_breed_id
     *
     * @mbggenerated
     */
    private Integer houseBreedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.growth_date
     *
     * @mbggenerated
     */
    private Date growthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.death_am
     *
     * @mbggenerated
     */
    private Integer deathAm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.death_pm
     *
     * @mbggenerated
     */
    private Integer deathPm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.culling_am
     *
     * @mbggenerated
     */
    private Integer cullingAm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.culling_pm
     *
     * @mbggenerated
     */
    private Integer cullingPm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.cur_cd
     *
     * @mbggenerated
     */
    private Integer curCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.acc_cd
     *
     * @mbggenerated
     */
    private Integer accCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.cur_feed
     *
     * @mbggenerated
     */
    private BigDecimal curFeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.acc_feed
     *
     * @mbggenerated
     */
    private BigDecimal accFeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.cur_weight
     *
     * @mbggenerated
     */
    private BigDecimal curWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.cur_amount
     *
     * @mbggenerated
     */
    private Integer curAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.ytd_amount
     *
     * @mbggenerated
     */
    private Integer ytdAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.int_bak1
     *
     * @mbggenerated
     */
    private Integer intBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.int_bak2
     *
     * @mbggenerated
     */
    private Integer intBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.int_bak3
     *
     * @mbggenerated
     */
    private Integer intBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.num_bak1
     *
     * @mbggenerated
     */
    private BigDecimal numBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.num_bak2
     *
     * @mbggenerated
     */
    private BigDecimal numBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.num_bak3
     *
     * @mbggenerated
     */
    private BigDecimal numBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.var_bak1
     *
     * @mbggenerated
     */
    private String varBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.var_bak2
     *
     * @mbggenerated
     */
    private String varBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.var_bak3
     *
     * @mbggenerated
     */
    private String varBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.date_bak1
     *
     * @mbggenerated
     */
    private Date dateBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.date_bak2
     *
     * @mbggenerated
     */
    private Date dateBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.date_bak3
     *
     * @mbggenerated
     */
    private Date dateBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.create_person
     *
     * @mbggenerated
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.modify_person
     *
     * @mbggenerated
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_breed_detail.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.house_breed_id
     *
     * @return the value of s_b_breed_detail.house_breed_id
     *
     * @mbggenerated
     */
    public Integer getHouseBreedId() {
        return houseBreedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.house_breed_id
     *
     * @param houseBreedId the value for s_b_breed_detail.house_breed_id
     *
     * @mbggenerated
     */
    public void setHouseBreedId(Integer houseBreedId) {
        this.houseBreedId = houseBreedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.age
     *
     * @return the value of s_b_breed_detail.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.age
     *
     * @param age the value for s_b_breed_detail.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.growth_date
     *
     * @return the value of s_b_breed_detail.growth_date
     *
     * @mbggenerated
     */
    public Date getGrowthDate() {
        return growthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.growth_date
     *
     * @param growthDate the value for s_b_breed_detail.growth_date
     *
     * @mbggenerated
     */
    public void setGrowthDate(Date growthDate) {
        this.growthDate = growthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.death_am
     *
     * @return the value of s_b_breed_detail.death_am
     *
     * @mbggenerated
     */
    public Integer getDeathAm() {
        return deathAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.death_am
     *
     * @param deathAm the value for s_b_breed_detail.death_am
     *
     * @mbggenerated
     */
    public void setDeathAm(Integer deathAm) {
        this.deathAm = deathAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.death_pm
     *
     * @return the value of s_b_breed_detail.death_pm
     *
     * @mbggenerated
     */
    public Integer getDeathPm() {
        return deathPm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.death_pm
     *
     * @param deathPm the value for s_b_breed_detail.death_pm
     *
     * @mbggenerated
     */
    public void setDeathPm(Integer deathPm) {
        this.deathPm = deathPm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.culling_am
     *
     * @return the value of s_b_breed_detail.culling_am
     *
     * @mbggenerated
     */
    public Integer getCullingAm() {
        return cullingAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.culling_am
     *
     * @param cullingAm the value for s_b_breed_detail.culling_am
     *
     * @mbggenerated
     */
    public void setCullingAm(Integer cullingAm) {
        this.cullingAm = cullingAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.culling_pm
     *
     * @return the value of s_b_breed_detail.culling_pm
     *
     * @mbggenerated
     */
    public Integer getCullingPm() {
        return cullingPm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.culling_pm
     *
     * @param cullingPm the value for s_b_breed_detail.culling_pm
     *
     * @mbggenerated
     */
    public void setCullingPm(Integer cullingPm) {
        this.cullingPm = cullingPm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.cur_cd
     *
     * @return the value of s_b_breed_detail.cur_cd
     *
     * @mbggenerated
     */
    public Integer getCurCd() {
        return curCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.cur_cd
     *
     * @param curCd the value for s_b_breed_detail.cur_cd
     *
     * @mbggenerated
     */
    public void setCurCd(Integer curCd) {
        this.curCd = curCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.acc_cd
     *
     * @return the value of s_b_breed_detail.acc_cd
     *
     * @mbggenerated
     */
    public Integer getAccCd() {
        return accCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.acc_cd
     *
     * @param accCd the value for s_b_breed_detail.acc_cd
     *
     * @mbggenerated
     */
    public void setAccCd(Integer accCd) {
        this.accCd = accCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.cur_feed
     *
     * @return the value of s_b_breed_detail.cur_feed
     *
     * @mbggenerated
     */
    public BigDecimal getCurFeed() {
        return curFeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.cur_feed
     *
     * @param curFeed the value for s_b_breed_detail.cur_feed
     *
     * @mbggenerated
     */
    public void setCurFeed(BigDecimal curFeed) {
        this.curFeed = curFeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.acc_feed
     *
     * @return the value of s_b_breed_detail.acc_feed
     *
     * @mbggenerated
     */
    public BigDecimal getAccFeed() {
        return accFeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.acc_feed
     *
     * @param accFeed the value for s_b_breed_detail.acc_feed
     *
     * @mbggenerated
     */
    public void setAccFeed(BigDecimal accFeed) {
        this.accFeed = accFeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.cur_weight
     *
     * @return the value of s_b_breed_detail.cur_weight
     *
     * @mbggenerated
     */
    public BigDecimal getCurWeight() {
        return curWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.cur_weight
     *
     * @param curWeight the value for s_b_breed_detail.cur_weight
     *
     * @mbggenerated
     */
    public void setCurWeight(BigDecimal curWeight) {
        this.curWeight = curWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.cur_amount
     *
     * @return the value of s_b_breed_detail.cur_amount
     *
     * @mbggenerated
     */
    public Integer getCurAmount() {
        return curAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.cur_amount
     *
     * @param curAmount the value for s_b_breed_detail.cur_amount
     *
     * @mbggenerated
     */
    public void setCurAmount(Integer curAmount) {
        this.curAmount = curAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.ytd_amount
     *
     * @return the value of s_b_breed_detail.ytd_amount
     *
     * @mbggenerated
     */
    public Integer getYtdAmount() {
        return ytdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.ytd_amount
     *
     * @param ytdAmount the value for s_b_breed_detail.ytd_amount
     *
     * @mbggenerated
     */
    public void setYtdAmount(Integer ytdAmount) {
        this.ytdAmount = ytdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.int_bak1
     *
     * @return the value of s_b_breed_detail.int_bak1
     *
     * @mbggenerated
     */
    public Integer getIntBak1() {
        return intBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.int_bak1
     *
     * @param intBak1 the value for s_b_breed_detail.int_bak1
     *
     * @mbggenerated
     */
    public void setIntBak1(Integer intBak1) {
        this.intBak1 = intBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.int_bak2
     *
     * @return the value of s_b_breed_detail.int_bak2
     *
     * @mbggenerated
     */
    public Integer getIntBak2() {
        return intBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.int_bak2
     *
     * @param intBak2 the value for s_b_breed_detail.int_bak2
     *
     * @mbggenerated
     */
    public void setIntBak2(Integer intBak2) {
        this.intBak2 = intBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.int_bak3
     *
     * @return the value of s_b_breed_detail.int_bak3
     *
     * @mbggenerated
     */
    public Integer getIntBak3() {
        return intBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.int_bak3
     *
     * @param intBak3 the value for s_b_breed_detail.int_bak3
     *
     * @mbggenerated
     */
    public void setIntBak3(Integer intBak3) {
        this.intBak3 = intBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.num_bak1
     *
     * @return the value of s_b_breed_detail.num_bak1
     *
     * @mbggenerated
     */
    public BigDecimal getNumBak1() {
        return numBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.num_bak1
     *
     * @param numBak1 the value for s_b_breed_detail.num_bak1
     *
     * @mbggenerated
     */
    public void setNumBak1(BigDecimal numBak1) {
        this.numBak1 = numBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.num_bak2
     *
     * @return the value of s_b_breed_detail.num_bak2
     *
     * @mbggenerated
     */
    public BigDecimal getNumBak2() {
        return numBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.num_bak2
     *
     * @param numBak2 the value for s_b_breed_detail.num_bak2
     *
     * @mbggenerated
     */
    public void setNumBak2(BigDecimal numBak2) {
        this.numBak2 = numBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.num_bak3
     *
     * @return the value of s_b_breed_detail.num_bak3
     *
     * @mbggenerated
     */
    public BigDecimal getNumBak3() {
        return numBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.num_bak3
     *
     * @param numBak3 the value for s_b_breed_detail.num_bak3
     *
     * @mbggenerated
     */
    public void setNumBak3(BigDecimal numBak3) {
        this.numBak3 = numBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.var_bak1
     *
     * @return the value of s_b_breed_detail.var_bak1
     *
     * @mbggenerated
     */
    public String getVarBak1() {
        return varBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.var_bak1
     *
     * @param varBak1 the value for s_b_breed_detail.var_bak1
     *
     * @mbggenerated
     */
    public void setVarBak1(String varBak1) {
        this.varBak1 = varBak1 == null ? null : varBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.var_bak2
     *
     * @return the value of s_b_breed_detail.var_bak2
     *
     * @mbggenerated
     */
    public String getVarBak2() {
        return varBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.var_bak2
     *
     * @param varBak2 the value for s_b_breed_detail.var_bak2
     *
     * @mbggenerated
     */
    public void setVarBak2(String varBak2) {
        this.varBak2 = varBak2 == null ? null : varBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.var_bak3
     *
     * @return the value of s_b_breed_detail.var_bak3
     *
     * @mbggenerated
     */
    public String getVarBak3() {
        return varBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.var_bak3
     *
     * @param varBak3 the value for s_b_breed_detail.var_bak3
     *
     * @mbggenerated
     */
    public void setVarBak3(String varBak3) {
        this.varBak3 = varBak3 == null ? null : varBak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.date_bak1
     *
     * @return the value of s_b_breed_detail.date_bak1
     *
     * @mbggenerated
     */
    public Date getDateBak1() {
        return dateBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.date_bak1
     *
     * @param dateBak1 the value for s_b_breed_detail.date_bak1
     *
     * @mbggenerated
     */
    public void setDateBak1(Date dateBak1) {
        this.dateBak1 = dateBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.date_bak2
     *
     * @return the value of s_b_breed_detail.date_bak2
     *
     * @mbggenerated
     */
    public Date getDateBak2() {
        return dateBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.date_bak2
     *
     * @param dateBak2 the value for s_b_breed_detail.date_bak2
     *
     * @mbggenerated
     */
    public void setDateBak2(Date dateBak2) {
        this.dateBak2 = dateBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.date_bak3
     *
     * @return the value of s_b_breed_detail.date_bak3
     *
     * @mbggenerated
     */
    public Date getDateBak3() {
        return dateBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.date_bak3
     *
     * @param dateBak3 the value for s_b_breed_detail.date_bak3
     *
     * @mbggenerated
     */
    public void setDateBak3(Date dateBak3) {
        this.dateBak3 = dateBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.create_person
     *
     * @return the value of s_b_breed_detail.create_person
     *
     * @mbggenerated
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.create_person
     *
     * @param createPerson the value for s_b_breed_detail.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.create_date
     *
     * @return the value of s_b_breed_detail.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.create_date
     *
     * @param createDate the value for s_b_breed_detail.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.create_time
     *
     * @return the value of s_b_breed_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.create_time
     *
     * @param createTime the value for s_b_breed_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.modify_person
     *
     * @return the value of s_b_breed_detail.modify_person
     *
     * @mbggenerated
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.modify_person
     *
     * @param modifyPerson the value for s_b_breed_detail.modify_person
     *
     * @mbggenerated
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.modify_date
     *
     * @return the value of s_b_breed_detail.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.modify_date
     *
     * @param modifyDate the value for s_b_breed_detail.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_breed_detail.modify_time
     *
     * @return the value of s_b_breed_detail.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_breed_detail.modify_time
     *
     * @param modifyTime the value for s_b_breed_detail.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}