package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SBChickenStandar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.breed_name
     *
     * @mbggenerated
     */
    private String breedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.feed_type
     *
     * @mbggenerated
     */
    private String feedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.farm_id
     *
     * @mbggenerated
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.daily_motality
     *
     * @mbggenerated
     */
    private BigDecimal dailyMotality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.cum_motality
     *
     * @mbggenerated
     */
    private BigDecimal cumMotality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.body_weight
     *
     * @mbggenerated
     */
    private BigDecimal bodyWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.daily_intake
     *
     * @mbggenerated
     */
    private BigDecimal dailyIntake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.avg_water
     *
     * @mbggenerated
     */
    private BigDecimal avgWater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.bak1
     *
     * @mbggenerated
     */
    private BigDecimal bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.bak2
     *
     * @mbggenerated
     */
    private BigDecimal bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.bak3
     *
     * @mbggenerated
     */
    private BigDecimal bak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.create_person
     *
     * @mbggenerated
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.modify_person
     *
     * @mbggenerated
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_chicken_standar.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.id
     *
     * @return the value of s_b_chicken_standar.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.id
     *
     * @param id the value for s_b_chicken_standar.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.breed_name
     *
     * @return the value of s_b_chicken_standar.breed_name
     *
     * @mbggenerated
     */
    public String getBreedName() {
        return breedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.breed_name
     *
     * @param breedName the value for s_b_chicken_standar.breed_name
     *
     * @mbggenerated
     */
    public void setBreedName(String breedName) {
        this.breedName = breedName == null ? null : breedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.feed_type
     *
     * @return the value of s_b_chicken_standar.feed_type
     *
     * @mbggenerated
     */
    public String getFeedType() {
        return feedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.feed_type
     *
     * @param feedType the value for s_b_chicken_standar.feed_type
     *
     * @mbggenerated
     */
    public void setFeedType(String feedType) {
        this.feedType = feedType == null ? null : feedType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.farm_id
     *
     * @return the value of s_b_chicken_standar.farm_id
     *
     * @mbggenerated
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.farm_id
     *
     * @param farmId the value for s_b_chicken_standar.farm_id
     *
     * @mbggenerated
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.age
     *
     * @return the value of s_b_chicken_standar.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.age
     *
     * @param age the value for s_b_chicken_standar.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.daily_motality
     *
     * @return the value of s_b_chicken_standar.daily_motality
     *
     * @mbggenerated
     */
    public BigDecimal getDailyMotality() {
        return dailyMotality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.daily_motality
     *
     * @param dailyMotality the value for s_b_chicken_standar.daily_motality
     *
     * @mbggenerated
     */
    public void setDailyMotality(BigDecimal dailyMotality) {
        this.dailyMotality = dailyMotality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.cum_motality
     *
     * @return the value of s_b_chicken_standar.cum_motality
     *
     * @mbggenerated
     */
    public BigDecimal getCumMotality() {
        return cumMotality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.cum_motality
     *
     * @param cumMotality the value for s_b_chicken_standar.cum_motality
     *
     * @mbggenerated
     */
    public void setCumMotality(BigDecimal cumMotality) {
        this.cumMotality = cumMotality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.body_weight
     *
     * @return the value of s_b_chicken_standar.body_weight
     *
     * @mbggenerated
     */
    public BigDecimal getBodyWeight() {
        return bodyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.body_weight
     *
     * @param bodyWeight the value for s_b_chicken_standar.body_weight
     *
     * @mbggenerated
     */
    public void setBodyWeight(BigDecimal bodyWeight) {
        this.bodyWeight = bodyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.daily_intake
     *
     * @return the value of s_b_chicken_standar.daily_intake
     *
     * @mbggenerated
     */
    public BigDecimal getDailyIntake() {
        return dailyIntake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.daily_intake
     *
     * @param dailyIntake the value for s_b_chicken_standar.daily_intake
     *
     * @mbggenerated
     */
    public void setDailyIntake(BigDecimal dailyIntake) {
        this.dailyIntake = dailyIntake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.avg_water
     *
     * @return the value of s_b_chicken_standar.avg_water
     *
     * @mbggenerated
     */
    public BigDecimal getAvgWater() {
        return avgWater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.avg_water
     *
     * @param avgWater the value for s_b_chicken_standar.avg_water
     *
     * @mbggenerated
     */
    public void setAvgWater(BigDecimal avgWater) {
        this.avgWater = avgWater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.bak1
     *
     * @return the value of s_b_chicken_standar.bak1
     *
     * @mbggenerated
     */
    public BigDecimal getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.bak1
     *
     * @param bak1 the value for s_b_chicken_standar.bak1
     *
     * @mbggenerated
     */
    public void setBak1(BigDecimal bak1) {
        this.bak1 = bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.bak2
     *
     * @return the value of s_b_chicken_standar.bak2
     *
     * @mbggenerated
     */
    public BigDecimal getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.bak2
     *
     * @param bak2 the value for s_b_chicken_standar.bak2
     *
     * @mbggenerated
     */
    public void setBak2(BigDecimal bak2) {
        this.bak2 = bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.bak3
     *
     * @return the value of s_b_chicken_standar.bak3
     *
     * @mbggenerated
     */
    public BigDecimal getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.bak3
     *
     * @param bak3 the value for s_b_chicken_standar.bak3
     *
     * @mbggenerated
     */
    public void setBak3(BigDecimal bak3) {
        this.bak3 = bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.create_person
     *
     * @return the value of s_b_chicken_standar.create_person
     *
     * @mbggenerated
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.create_person
     *
     * @param createPerson the value for s_b_chicken_standar.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.create_date
     *
     * @return the value of s_b_chicken_standar.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.create_date
     *
     * @param createDate the value for s_b_chicken_standar.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.create_time
     *
     * @return the value of s_b_chicken_standar.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.create_time
     *
     * @param createTime the value for s_b_chicken_standar.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.modify_person
     *
     * @return the value of s_b_chicken_standar.modify_person
     *
     * @mbggenerated
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.modify_person
     *
     * @param modifyPerson the value for s_b_chicken_standar.modify_person
     *
     * @mbggenerated
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.modify_date
     *
     * @return the value of s_b_chicken_standar.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.modify_date
     *
     * @param modifyDate the value for s_b_chicken_standar.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_chicken_standar.modify_time
     *
     * @return the value of s_b_chicken_standar.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_chicken_standar.modify_time
     *
     * @param modifyTime the value for s_b_chicken_standar.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}