package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SBDayageTempSub {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.uid_num
     *
     * @mbggenerated
     */
    private Integer uidNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.day_age
     *
     * @mbggenerated
     */
    private Integer dayAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.record_datetime
     *
     * @mbggenerated
     */
    private Date recordDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.set_temp
     *
     * @mbggenerated
     */
    private BigDecimal setTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.high_alarm_temp
     *
     * @mbggenerated
     */
    private BigDecimal highAlarmTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.low_alarm_temp
     *
     * @mbggenerated
     */
    private BigDecimal lowAlarmTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.set_humidity
     *
     * @mbggenerated
     */
    private BigDecimal setHumidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.create_person
     *
     * @mbggenerated
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.modify_person
     *
     * @mbggenerated
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_dayage_temp_sub.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.uid_num
     *
     * @return the value of s_b_dayage_temp_sub.uid_num
     *
     * @mbggenerated
     */
    public Integer getUidNum() {
        return uidNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.uid_num
     *
     * @param uidNum the value for s_b_dayage_temp_sub.uid_num
     *
     * @mbggenerated
     */
    public void setUidNum(Integer uidNum) {
        this.uidNum = uidNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.day_age
     *
     * @return the value of s_b_dayage_temp_sub.day_age
     *
     * @mbggenerated
     */
    public Integer getDayAge() {
        return dayAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.day_age
     *
     * @param dayAge the value for s_b_dayage_temp_sub.day_age
     *
     * @mbggenerated
     */
    public void setDayAge(Integer dayAge) {
        this.dayAge = dayAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.record_datetime
     *
     * @return the value of s_b_dayage_temp_sub.record_datetime
     *
     * @mbggenerated
     */
    public Date getRecordDatetime() {
        return recordDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.record_datetime
     *
     * @param recordDatetime the value for s_b_dayage_temp_sub.record_datetime
     *
     * @mbggenerated
     */
    public void setRecordDatetime(Date recordDatetime) {
        this.recordDatetime = recordDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.set_temp
     *
     * @return the value of s_b_dayage_temp_sub.set_temp
     *
     * @mbggenerated
     */
    public BigDecimal getSetTemp() {
        return setTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.set_temp
     *
     * @param setTemp the value for s_b_dayage_temp_sub.set_temp
     *
     * @mbggenerated
     */
    public void setSetTemp(BigDecimal setTemp) {
        this.setTemp = setTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.high_alarm_temp
     *
     * @return the value of s_b_dayage_temp_sub.high_alarm_temp
     *
     * @mbggenerated
     */
    public BigDecimal getHighAlarmTemp() {
        return highAlarmTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.high_alarm_temp
     *
     * @param highAlarmTemp the value for s_b_dayage_temp_sub.high_alarm_temp
     *
     * @mbggenerated
     */
    public void setHighAlarmTemp(BigDecimal highAlarmTemp) {
        this.highAlarmTemp = highAlarmTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.low_alarm_temp
     *
     * @return the value of s_b_dayage_temp_sub.low_alarm_temp
     *
     * @mbggenerated
     */
    public BigDecimal getLowAlarmTemp() {
        return lowAlarmTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.low_alarm_temp
     *
     * @param lowAlarmTemp the value for s_b_dayage_temp_sub.low_alarm_temp
     *
     * @mbggenerated
     */
    public void setLowAlarmTemp(BigDecimal lowAlarmTemp) {
        this.lowAlarmTemp = lowAlarmTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.set_humidity
     *
     * @return the value of s_b_dayage_temp_sub.set_humidity
     *
     * @mbggenerated
     */
    public BigDecimal getSetHumidity() {
        return setHumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.set_humidity
     *
     * @param setHumidity the value for s_b_dayage_temp_sub.set_humidity
     *
     * @mbggenerated
     */
    public void setSetHumidity(BigDecimal setHumidity) {
        this.setHumidity = setHumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.memo
     *
     * @return the value of s_b_dayage_temp_sub.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.memo
     *
     * @param memo the value for s_b_dayage_temp_sub.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.create_person
     *
     * @return the value of s_b_dayage_temp_sub.create_person
     *
     * @mbggenerated
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.create_person
     *
     * @param createPerson the value for s_b_dayage_temp_sub.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.create_date
     *
     * @return the value of s_b_dayage_temp_sub.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.create_date
     *
     * @param createDate the value for s_b_dayage_temp_sub.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.create_time
     *
     * @return the value of s_b_dayage_temp_sub.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.create_time
     *
     * @param createTime the value for s_b_dayage_temp_sub.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.modify_person
     *
     * @return the value of s_b_dayage_temp_sub.modify_person
     *
     * @mbggenerated
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.modify_person
     *
     * @param modifyPerson the value for s_b_dayage_temp_sub.modify_person
     *
     * @mbggenerated
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.modify_date
     *
     * @return the value of s_b_dayage_temp_sub.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.modify_date
     *
     * @param modifyDate the value for s_b_dayage_temp_sub.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_dayage_temp_sub.modify_time
     *
     * @return the value of s_b_dayage_temp_sub.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_dayage_temp_sub.modify_time
     *
     * @param modifyTime the value for s_b_dayage_temp_sub.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}