package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SBHouseBreed {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.farm_breed_id
     *
     * @mbggenerated
     */
    private Integer farmBreedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.farm_id
     *
     * @mbggenerated
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.house_id
     *
     * @mbggenerated
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.place_date
     *
     * @mbggenerated
     */
    private Date placeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.place_num
     *
     * @mbggenerated
     */
    private Integer placeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.place_weight
     *
     * @mbggenerated
     */
    private BigDecimal placeWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.moveout_num
     *
     * @mbggenerated
     */
    private Integer moveoutNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.moveout_weight
     *
     * @mbggenerated
     */
    private BigDecimal moveoutWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.batch_status
     *
     * @mbggenerated
     */
    private String batchStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.market_date
     *
     * @mbggenerated
     */
    private Date marketDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.create_person
     *
     * @mbggenerated
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.modify_person
     *
     * @mbggenerated
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.moveout_sumweight
     *
     * @mbggenerated
     */
    private BigDecimal moveoutSumweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.market_feed_weight
     *
     * @mbggenerated
     */
    private BigDecimal marketFeedWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.var_bak1
     *
     * @mbggenerated
     */
    private String varBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.var_bak2
     *
     * @mbggenerated
     */
    private String varBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.num_bak1
     *
     * @mbggenerated
     */
    private BigDecimal numBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.num_bak2
     *
     * @mbggenerated
     */
    private BigDecimal numBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_house_breed.num_bak3
     *
     * @mbggenerated
     */
    private BigDecimal numBak3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.id
     *
     * @return the value of s_b_house_breed.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.id
     *
     * @param id the value for s_b_house_breed.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.farm_breed_id
     *
     * @return the value of s_b_house_breed.farm_breed_id
     *
     * @mbggenerated
     */
    public Integer getFarmBreedId() {
        return farmBreedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.farm_breed_id
     *
     * @param farmBreedId the value for s_b_house_breed.farm_breed_id
     *
     * @mbggenerated
     */
    public void setFarmBreedId(Integer farmBreedId) {
        this.farmBreedId = farmBreedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.farm_id
     *
     * @return the value of s_b_house_breed.farm_id
     *
     * @mbggenerated
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.farm_id
     *
     * @param farmId the value for s_b_house_breed.farm_id
     *
     * @mbggenerated
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.house_id
     *
     * @return the value of s_b_house_breed.house_id
     *
     * @mbggenerated
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.house_id
     *
     * @param houseId the value for s_b_house_breed.house_id
     *
     * @mbggenerated
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.place_date
     *
     * @return the value of s_b_house_breed.place_date
     *
     * @mbggenerated
     */
    public Date getPlaceDate() {
        return placeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.place_date
     *
     * @param placeDate the value for s_b_house_breed.place_date
     *
     * @mbggenerated
     */
    public void setPlaceDate(Date placeDate) {
        this.placeDate = placeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.place_num
     *
     * @return the value of s_b_house_breed.place_num
     *
     * @mbggenerated
     */
    public Integer getPlaceNum() {
        return placeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.place_num
     *
     * @param placeNum the value for s_b_house_breed.place_num
     *
     * @mbggenerated
     */
    public void setPlaceNum(Integer placeNum) {
        this.placeNum = placeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.place_weight
     *
     * @return the value of s_b_house_breed.place_weight
     *
     * @mbggenerated
     */
    public BigDecimal getPlaceWeight() {
        return placeWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.place_weight
     *
     * @param placeWeight the value for s_b_house_breed.place_weight
     *
     * @mbggenerated
     */
    public void setPlaceWeight(BigDecimal placeWeight) {
        this.placeWeight = placeWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.moveout_num
     *
     * @return the value of s_b_house_breed.moveout_num
     *
     * @mbggenerated
     */
    public Integer getMoveoutNum() {
        return moveoutNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.moveout_num
     *
     * @param moveoutNum the value for s_b_house_breed.moveout_num
     *
     * @mbggenerated
     */
    public void setMoveoutNum(Integer moveoutNum) {
        this.moveoutNum = moveoutNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.moveout_weight
     *
     * @return the value of s_b_house_breed.moveout_weight
     *
     * @mbggenerated
     */
    public BigDecimal getMoveoutWeight() {
        return moveoutWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.moveout_weight
     *
     * @param moveoutWeight the value for s_b_house_breed.moveout_weight
     *
     * @mbggenerated
     */
    public void setMoveoutWeight(BigDecimal moveoutWeight) {
        this.moveoutWeight = moveoutWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.batch_status
     *
     * @return the value of s_b_house_breed.batch_status
     *
     * @mbggenerated
     */
    public String getBatchStatus() {
        return batchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.batch_status
     *
     * @param batchStatus the value for s_b_house_breed.batch_status
     *
     * @mbggenerated
     */
    public void setBatchStatus(String batchStatus) {
        this.batchStatus = batchStatus == null ? null : batchStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.market_date
     *
     * @return the value of s_b_house_breed.market_date
     *
     * @mbggenerated
     */
    public Date getMarketDate() {
        return marketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.market_date
     *
     * @param marketDate the value for s_b_house_breed.market_date
     *
     * @mbggenerated
     */
    public void setMarketDate(Date marketDate) {
        this.marketDate = marketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.create_person
     *
     * @return the value of s_b_house_breed.create_person
     *
     * @mbggenerated
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.create_person
     *
     * @param createPerson the value for s_b_house_breed.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.create_date
     *
     * @return the value of s_b_house_breed.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.create_date
     *
     * @param createDate the value for s_b_house_breed.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.create_time
     *
     * @return the value of s_b_house_breed.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.create_time
     *
     * @param createTime the value for s_b_house_breed.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.modify_person
     *
     * @return the value of s_b_house_breed.modify_person
     *
     * @mbggenerated
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.modify_person
     *
     * @param modifyPerson the value for s_b_house_breed.modify_person
     *
     * @mbggenerated
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.modify_date
     *
     * @return the value of s_b_house_breed.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.modify_date
     *
     * @param modifyDate the value for s_b_house_breed.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.modify_time
     *
     * @return the value of s_b_house_breed.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.modify_time
     *
     * @param modifyTime the value for s_b_house_breed.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.moveout_sumweight
     *
     * @return the value of s_b_house_breed.moveout_sumweight
     *
     * @mbggenerated
     */
    public BigDecimal getMoveoutSumweight() {
        return moveoutSumweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.moveout_sumweight
     *
     * @param moveoutSumweight the value for s_b_house_breed.moveout_sumweight
     *
     * @mbggenerated
     */
    public void setMoveoutSumweight(BigDecimal moveoutSumweight) {
        this.moveoutSumweight = moveoutSumweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.market_feed_weight
     *
     * @return the value of s_b_house_breed.market_feed_weight
     *
     * @mbggenerated
     */
    public BigDecimal getMarketFeedWeight() {
        return marketFeedWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.market_feed_weight
     *
     * @param marketFeedWeight the value for s_b_house_breed.market_feed_weight
     *
     * @mbggenerated
     */
    public void setMarketFeedWeight(BigDecimal marketFeedWeight) {
        this.marketFeedWeight = marketFeedWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.var_bak1
     *
     * @return the value of s_b_house_breed.var_bak1
     *
     * @mbggenerated
     */
    public String getVarBak1() {
        return varBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.var_bak1
     *
     * @param varBak1 the value for s_b_house_breed.var_bak1
     *
     * @mbggenerated
     */
    public void setVarBak1(String varBak1) {
        this.varBak1 = varBak1 == null ? null : varBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.var_bak2
     *
     * @return the value of s_b_house_breed.var_bak2
     *
     * @mbggenerated
     */
    public String getVarBak2() {
        return varBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.var_bak2
     *
     * @param varBak2 the value for s_b_house_breed.var_bak2
     *
     * @mbggenerated
     */
    public void setVarBak2(String varBak2) {
        this.varBak2 = varBak2 == null ? null : varBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.num_bak1
     *
     * @return the value of s_b_house_breed.num_bak1
     *
     * @mbggenerated
     */
    public BigDecimal getNumBak1() {
        return numBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.num_bak1
     *
     * @param numBak1 the value for s_b_house_breed.num_bak1
     *
     * @mbggenerated
     */
    public void setNumBak1(BigDecimal numBak1) {
        this.numBak1 = numBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.num_bak2
     *
     * @return the value of s_b_house_breed.num_bak2
     *
     * @mbggenerated
     */
    public BigDecimal getNumBak2() {
        return numBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.num_bak2
     *
     * @param numBak2 the value for s_b_house_breed.num_bak2
     *
     * @mbggenerated
     */
    public void setNumBak2(BigDecimal numBak2) {
        this.numBak2 = numBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_house_breed.num_bak3
     *
     * @return the value of s_b_house_breed.num_bak3
     *
     * @mbggenerated
     */
    public BigDecimal getNumBak3() {
        return numBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_house_breed.num_bak3
     *
     * @param numBak3 the value for s_b_house_breed.num_bak3
     *
     * @mbggenerated
     */
    public void setNumBak3(BigDecimal numBak3) {
        this.numBak3 = numBak3;
    }
}