package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SBMonitorHist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.farm_id
     *
     * @mbggenerated
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.house_id
     *
     * @mbggenerated
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.collect_datetime
     *
     * @mbggenerated
     */
    private Date collectDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.update_datetime
     *
     * @mbggenerated
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.deal_status
     *
     * @mbggenerated
     */
    private Integer dealStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.date_age
     *
     * @mbggenerated
     */
    private Integer dateAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.week_age
     *
     * @mbggenerated
     */
    private Integer weekAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp1
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp2
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp3
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp4
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp5
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp6
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp7
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp8
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp9
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp10
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp11
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp12
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp13
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp14
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp15
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp16
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp17
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp18
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp19
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_temp20
     *
     * @mbggenerated
     */
    private BigDecimal insideTemp20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_avg_temp
     *
     * @mbggenerated
     */
    private BigDecimal insideAvgTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_set_temp
     *
     * @mbggenerated
     */
    private BigDecimal insideSetTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.high_alarm_temp
     *
     * @mbggenerated
     */
    private BigDecimal highAlarmTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.low_alarm_temp
     *
     * @mbggenerated
     */
    private BigDecimal lowAlarmTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.outside_temp
     *
     * @mbggenerated
     */
    private BigDecimal outsideTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_humidity
     *
     * @mbggenerated
     */
    private BigDecimal insideHumidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_humidity2
     *
     * @mbggenerated
     */
    private BigDecimal insideHumidity2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.inside_humidity3
     *
     * @mbggenerated
     */
    private BigDecimal insideHumidity3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.point_temp_diff
     *
     * @mbggenerated
     */
    private BigDecimal pointTempDiff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.target_humidity
     *
     * @mbggenerated
     */
    private BigDecimal targetHumidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.co2
     *
     * @mbggenerated
     */
    private BigDecimal co2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.co2_2
     *
     * @mbggenerated
     */
    private BigDecimal co22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.co2_3
     *
     * @mbggenerated
     */
    private BigDecimal co23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.power_status
     *
     * @mbggenerated
     */
    private Integer powerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.lux_1
     *
     * @mbggenerated
     */
    private BigDecimal lux1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.lux_2
     *
     * @mbggenerated
     */
    private BigDecimal lux2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.lux_3
     *
     * @mbggenerated
     */
    private BigDecimal lux3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.NH4_1
     *
     * @mbggenerated
     */
    private BigDecimal nh41;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.NH4_2
     *
     * @mbggenerated
     */
    private BigDecimal nh42;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.NH4_3
     *
     * @mbggenerated
     */
    private BigDecimal nh43;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.pressure_1
     *
     * @mbggenerated
     */
    private BigDecimal pressure1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.pressure_2
     *
     * @mbggenerated
     */
    private BigDecimal pressure2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_monitor_hist.pressure_3
     *
     * @mbggenerated
     */
    private BigDecimal pressure3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.id
     *
     * @return the value of s_b_monitor_hist.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.id
     *
     * @param id the value for s_b_monitor_hist.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.farm_id
     *
     * @return the value of s_b_monitor_hist.farm_id
     *
     * @mbggenerated
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.farm_id
     *
     * @param farmId the value for s_b_monitor_hist.farm_id
     *
     * @mbggenerated
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.house_id
     *
     * @return the value of s_b_monitor_hist.house_id
     *
     * @mbggenerated
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.house_id
     *
     * @param houseId the value for s_b_monitor_hist.house_id
     *
     * @mbggenerated
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.collect_datetime
     *
     * @return the value of s_b_monitor_hist.collect_datetime
     *
     * @mbggenerated
     */
    public Date getCollectDatetime() {
        return collectDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.collect_datetime
     *
     * @param collectDatetime the value for s_b_monitor_hist.collect_datetime
     *
     * @mbggenerated
     */
    public void setCollectDatetime(Date collectDatetime) {
        this.collectDatetime = collectDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.update_datetime
     *
     * @return the value of s_b_monitor_hist.update_datetime
     *
     * @mbggenerated
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.update_datetime
     *
     * @param updateDatetime the value for s_b_monitor_hist.update_datetime
     *
     * @mbggenerated
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.deal_status
     *
     * @return the value of s_b_monitor_hist.deal_status
     *
     * @mbggenerated
     */
    public Integer getDealStatus() {
        return dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.deal_status
     *
     * @param dealStatus the value for s_b_monitor_hist.deal_status
     *
     * @mbggenerated
     */
    public void setDealStatus(Integer dealStatus) {
        this.dealStatus = dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.date_age
     *
     * @return the value of s_b_monitor_hist.date_age
     *
     * @mbggenerated
     */
    public Integer getDateAge() {
        return dateAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.date_age
     *
     * @param dateAge the value for s_b_monitor_hist.date_age
     *
     * @mbggenerated
     */
    public void setDateAge(Integer dateAge) {
        this.dateAge = dateAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.week_age
     *
     * @return the value of s_b_monitor_hist.week_age
     *
     * @mbggenerated
     */
    public Integer getWeekAge() {
        return weekAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.week_age
     *
     * @param weekAge the value for s_b_monitor_hist.week_age
     *
     * @mbggenerated
     */
    public void setWeekAge(Integer weekAge) {
        this.weekAge = weekAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp1
     *
     * @return the value of s_b_monitor_hist.inside_temp1
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp1() {
        return insideTemp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp1
     *
     * @param insideTemp1 the value for s_b_monitor_hist.inside_temp1
     *
     * @mbggenerated
     */
    public void setInsideTemp1(BigDecimal insideTemp1) {
        this.insideTemp1 = insideTemp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp2
     *
     * @return the value of s_b_monitor_hist.inside_temp2
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp2() {
        return insideTemp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp2
     *
     * @param insideTemp2 the value for s_b_monitor_hist.inside_temp2
     *
     * @mbggenerated
     */
    public void setInsideTemp2(BigDecimal insideTemp2) {
        this.insideTemp2 = insideTemp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp3
     *
     * @return the value of s_b_monitor_hist.inside_temp3
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp3() {
        return insideTemp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp3
     *
     * @param insideTemp3 the value for s_b_monitor_hist.inside_temp3
     *
     * @mbggenerated
     */
    public void setInsideTemp3(BigDecimal insideTemp3) {
        this.insideTemp3 = insideTemp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp4
     *
     * @return the value of s_b_monitor_hist.inside_temp4
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp4() {
        return insideTemp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp4
     *
     * @param insideTemp4 the value for s_b_monitor_hist.inside_temp4
     *
     * @mbggenerated
     */
    public void setInsideTemp4(BigDecimal insideTemp4) {
        this.insideTemp4 = insideTemp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp5
     *
     * @return the value of s_b_monitor_hist.inside_temp5
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp5() {
        return insideTemp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp5
     *
     * @param insideTemp5 the value for s_b_monitor_hist.inside_temp5
     *
     * @mbggenerated
     */
    public void setInsideTemp5(BigDecimal insideTemp5) {
        this.insideTemp5 = insideTemp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp6
     *
     * @return the value of s_b_monitor_hist.inside_temp6
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp6() {
        return insideTemp6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp6
     *
     * @param insideTemp6 the value for s_b_monitor_hist.inside_temp6
     *
     * @mbggenerated
     */
    public void setInsideTemp6(BigDecimal insideTemp6) {
        this.insideTemp6 = insideTemp6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp7
     *
     * @return the value of s_b_monitor_hist.inside_temp7
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp7() {
        return insideTemp7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp7
     *
     * @param insideTemp7 the value for s_b_monitor_hist.inside_temp7
     *
     * @mbggenerated
     */
    public void setInsideTemp7(BigDecimal insideTemp7) {
        this.insideTemp7 = insideTemp7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp8
     *
     * @return the value of s_b_monitor_hist.inside_temp8
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp8() {
        return insideTemp8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp8
     *
     * @param insideTemp8 the value for s_b_monitor_hist.inside_temp8
     *
     * @mbggenerated
     */
    public void setInsideTemp8(BigDecimal insideTemp8) {
        this.insideTemp8 = insideTemp8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp9
     *
     * @return the value of s_b_monitor_hist.inside_temp9
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp9() {
        return insideTemp9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp9
     *
     * @param insideTemp9 the value for s_b_monitor_hist.inside_temp9
     *
     * @mbggenerated
     */
    public void setInsideTemp9(BigDecimal insideTemp9) {
        this.insideTemp9 = insideTemp9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp10
     *
     * @return the value of s_b_monitor_hist.inside_temp10
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp10() {
        return insideTemp10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp10
     *
     * @param insideTemp10 the value for s_b_monitor_hist.inside_temp10
     *
     * @mbggenerated
     */
    public void setInsideTemp10(BigDecimal insideTemp10) {
        this.insideTemp10 = insideTemp10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp11
     *
     * @return the value of s_b_monitor_hist.inside_temp11
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp11() {
        return insideTemp11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp11
     *
     * @param insideTemp11 the value for s_b_monitor_hist.inside_temp11
     *
     * @mbggenerated
     */
    public void setInsideTemp11(BigDecimal insideTemp11) {
        this.insideTemp11 = insideTemp11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp12
     *
     * @return the value of s_b_monitor_hist.inside_temp12
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp12() {
        return insideTemp12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp12
     *
     * @param insideTemp12 the value for s_b_monitor_hist.inside_temp12
     *
     * @mbggenerated
     */
    public void setInsideTemp12(BigDecimal insideTemp12) {
        this.insideTemp12 = insideTemp12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp13
     *
     * @return the value of s_b_monitor_hist.inside_temp13
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp13() {
        return insideTemp13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp13
     *
     * @param insideTemp13 the value for s_b_monitor_hist.inside_temp13
     *
     * @mbggenerated
     */
    public void setInsideTemp13(BigDecimal insideTemp13) {
        this.insideTemp13 = insideTemp13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp14
     *
     * @return the value of s_b_monitor_hist.inside_temp14
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp14() {
        return insideTemp14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp14
     *
     * @param insideTemp14 the value for s_b_monitor_hist.inside_temp14
     *
     * @mbggenerated
     */
    public void setInsideTemp14(BigDecimal insideTemp14) {
        this.insideTemp14 = insideTemp14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp15
     *
     * @return the value of s_b_monitor_hist.inside_temp15
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp15() {
        return insideTemp15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp15
     *
     * @param insideTemp15 the value for s_b_monitor_hist.inside_temp15
     *
     * @mbggenerated
     */
    public void setInsideTemp15(BigDecimal insideTemp15) {
        this.insideTemp15 = insideTemp15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp16
     *
     * @return the value of s_b_monitor_hist.inside_temp16
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp16() {
        return insideTemp16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp16
     *
     * @param insideTemp16 the value for s_b_monitor_hist.inside_temp16
     *
     * @mbggenerated
     */
    public void setInsideTemp16(BigDecimal insideTemp16) {
        this.insideTemp16 = insideTemp16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp17
     *
     * @return the value of s_b_monitor_hist.inside_temp17
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp17() {
        return insideTemp17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp17
     *
     * @param insideTemp17 the value for s_b_monitor_hist.inside_temp17
     *
     * @mbggenerated
     */
    public void setInsideTemp17(BigDecimal insideTemp17) {
        this.insideTemp17 = insideTemp17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp18
     *
     * @return the value of s_b_monitor_hist.inside_temp18
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp18() {
        return insideTemp18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp18
     *
     * @param insideTemp18 the value for s_b_monitor_hist.inside_temp18
     *
     * @mbggenerated
     */
    public void setInsideTemp18(BigDecimal insideTemp18) {
        this.insideTemp18 = insideTemp18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp19
     *
     * @return the value of s_b_monitor_hist.inside_temp19
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp19() {
        return insideTemp19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp19
     *
     * @param insideTemp19 the value for s_b_monitor_hist.inside_temp19
     *
     * @mbggenerated
     */
    public void setInsideTemp19(BigDecimal insideTemp19) {
        this.insideTemp19 = insideTemp19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_temp20
     *
     * @return the value of s_b_monitor_hist.inside_temp20
     *
     * @mbggenerated
     */
    public BigDecimal getInsideTemp20() {
        return insideTemp20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_temp20
     *
     * @param insideTemp20 the value for s_b_monitor_hist.inside_temp20
     *
     * @mbggenerated
     */
    public void setInsideTemp20(BigDecimal insideTemp20) {
        this.insideTemp20 = insideTemp20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_avg_temp
     *
     * @return the value of s_b_monitor_hist.inside_avg_temp
     *
     * @mbggenerated
     */
    public BigDecimal getInsideAvgTemp() {
        return insideAvgTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_avg_temp
     *
     * @param insideAvgTemp the value for s_b_monitor_hist.inside_avg_temp
     *
     * @mbggenerated
     */
    public void setInsideAvgTemp(BigDecimal insideAvgTemp) {
        this.insideAvgTemp = insideAvgTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_set_temp
     *
     * @return the value of s_b_monitor_hist.inside_set_temp
     *
     * @mbggenerated
     */
    public BigDecimal getInsideSetTemp() {
        return insideSetTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_set_temp
     *
     * @param insideSetTemp the value for s_b_monitor_hist.inside_set_temp
     *
     * @mbggenerated
     */
    public void setInsideSetTemp(BigDecimal insideSetTemp) {
        this.insideSetTemp = insideSetTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.high_alarm_temp
     *
     * @return the value of s_b_monitor_hist.high_alarm_temp
     *
     * @mbggenerated
     */
    public BigDecimal getHighAlarmTemp() {
        return highAlarmTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.high_alarm_temp
     *
     * @param highAlarmTemp the value for s_b_monitor_hist.high_alarm_temp
     *
     * @mbggenerated
     */
    public void setHighAlarmTemp(BigDecimal highAlarmTemp) {
        this.highAlarmTemp = highAlarmTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.low_alarm_temp
     *
     * @return the value of s_b_monitor_hist.low_alarm_temp
     *
     * @mbggenerated
     */
    public BigDecimal getLowAlarmTemp() {
        return lowAlarmTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.low_alarm_temp
     *
     * @param lowAlarmTemp the value for s_b_monitor_hist.low_alarm_temp
     *
     * @mbggenerated
     */
    public void setLowAlarmTemp(BigDecimal lowAlarmTemp) {
        this.lowAlarmTemp = lowAlarmTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.outside_temp
     *
     * @return the value of s_b_monitor_hist.outside_temp
     *
     * @mbggenerated
     */
    public BigDecimal getOutsideTemp() {
        return outsideTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.outside_temp
     *
     * @param outsideTemp the value for s_b_monitor_hist.outside_temp
     *
     * @mbggenerated
     */
    public void setOutsideTemp(BigDecimal outsideTemp) {
        this.outsideTemp = outsideTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_humidity
     *
     * @return the value of s_b_monitor_hist.inside_humidity
     *
     * @mbggenerated
     */
    public BigDecimal getInsideHumidity() {
        return insideHumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_humidity
     *
     * @param insideHumidity the value for s_b_monitor_hist.inside_humidity
     *
     * @mbggenerated
     */
    public void setInsideHumidity(BigDecimal insideHumidity) {
        this.insideHumidity = insideHumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_humidity2
     *
     * @return the value of s_b_monitor_hist.inside_humidity2
     *
     * @mbggenerated
     */
    public BigDecimal getInsideHumidity2() {
        return insideHumidity2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_humidity2
     *
     * @param insideHumidity2 the value for s_b_monitor_hist.inside_humidity2
     *
     * @mbggenerated
     */
    public void setInsideHumidity2(BigDecimal insideHumidity2) {
        this.insideHumidity2 = insideHumidity2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.inside_humidity3
     *
     * @return the value of s_b_monitor_hist.inside_humidity3
     *
     * @mbggenerated
     */
    public BigDecimal getInsideHumidity3() {
        return insideHumidity3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.inside_humidity3
     *
     * @param insideHumidity3 the value for s_b_monitor_hist.inside_humidity3
     *
     * @mbggenerated
     */
    public void setInsideHumidity3(BigDecimal insideHumidity3) {
        this.insideHumidity3 = insideHumidity3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.point_temp_diff
     *
     * @return the value of s_b_monitor_hist.point_temp_diff
     *
     * @mbggenerated
     */
    public BigDecimal getPointTempDiff() {
        return pointTempDiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.point_temp_diff
     *
     * @param pointTempDiff the value for s_b_monitor_hist.point_temp_diff
     *
     * @mbggenerated
     */
    public void setPointTempDiff(BigDecimal pointTempDiff) {
        this.pointTempDiff = pointTempDiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.target_humidity
     *
     * @return the value of s_b_monitor_hist.target_humidity
     *
     * @mbggenerated
     */
    public BigDecimal getTargetHumidity() {
        return targetHumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.target_humidity
     *
     * @param targetHumidity the value for s_b_monitor_hist.target_humidity
     *
     * @mbggenerated
     */
    public void setTargetHumidity(BigDecimal targetHumidity) {
        this.targetHumidity = targetHumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.co2
     *
     * @return the value of s_b_monitor_hist.co2
     *
     * @mbggenerated
     */
    public BigDecimal getCo2() {
        return co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.co2
     *
     * @param co2 the value for s_b_monitor_hist.co2
     *
     * @mbggenerated
     */
    public void setCo2(BigDecimal co2) {
        this.co2 = co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.co2_2
     *
     * @return the value of s_b_monitor_hist.co2_2
     *
     * @mbggenerated
     */
    public BigDecimal getCo22() {
        return co22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.co2_2
     *
     * @param co22 the value for s_b_monitor_hist.co2_2
     *
     * @mbggenerated
     */
    public void setCo22(BigDecimal co22) {
        this.co22 = co22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.co2_3
     *
     * @return the value of s_b_monitor_hist.co2_3
     *
     * @mbggenerated
     */
    public BigDecimal getCo23() {
        return co23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.co2_3
     *
     * @param co23 the value for s_b_monitor_hist.co2_3
     *
     * @mbggenerated
     */
    public void setCo23(BigDecimal co23) {
        this.co23 = co23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.power_status
     *
     * @return the value of s_b_monitor_hist.power_status
     *
     * @mbggenerated
     */
    public Integer getPowerStatus() {
        return powerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.power_status
     *
     * @param powerStatus the value for s_b_monitor_hist.power_status
     *
     * @mbggenerated
     */
    public void setPowerStatus(Integer powerStatus) {
        this.powerStatus = powerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.lux_1
     *
     * @return the value of s_b_monitor_hist.lux_1
     *
     * @mbggenerated
     */
    public BigDecimal getLux1() {
        return lux1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.lux_1
     *
     * @param lux1 the value for s_b_monitor_hist.lux_1
     *
     * @mbggenerated
     */
    public void setLux1(BigDecimal lux1) {
        this.lux1 = lux1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.lux_2
     *
     * @return the value of s_b_monitor_hist.lux_2
     *
     * @mbggenerated
     */
    public BigDecimal getLux2() {
        return lux2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.lux_2
     *
     * @param lux2 the value for s_b_monitor_hist.lux_2
     *
     * @mbggenerated
     */
    public void setLux2(BigDecimal lux2) {
        this.lux2 = lux2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.lux_3
     *
     * @return the value of s_b_monitor_hist.lux_3
     *
     * @mbggenerated
     */
    public BigDecimal getLux3() {
        return lux3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.lux_3
     *
     * @param lux3 the value for s_b_monitor_hist.lux_3
     *
     * @mbggenerated
     */
    public void setLux3(BigDecimal lux3) {
        this.lux3 = lux3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.NH4_1
     *
     * @return the value of s_b_monitor_hist.NH4_1
     *
     * @mbggenerated
     */
    public BigDecimal getNh41() {
        return nh41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.NH4_1
     *
     * @param nh41 the value for s_b_monitor_hist.NH4_1
     *
     * @mbggenerated
     */
    public void setNh41(BigDecimal nh41) {
        this.nh41 = nh41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.NH4_2
     *
     * @return the value of s_b_monitor_hist.NH4_2
     *
     * @mbggenerated
     */
    public BigDecimal getNh42() {
        return nh42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.NH4_2
     *
     * @param nh42 the value for s_b_monitor_hist.NH4_2
     *
     * @mbggenerated
     */
    public void setNh42(BigDecimal nh42) {
        this.nh42 = nh42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.NH4_3
     *
     * @return the value of s_b_monitor_hist.NH4_3
     *
     * @mbggenerated
     */
    public BigDecimal getNh43() {
        return nh43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.NH4_3
     *
     * @param nh43 the value for s_b_monitor_hist.NH4_3
     *
     * @mbggenerated
     */
    public void setNh43(BigDecimal nh43) {
        this.nh43 = nh43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.pressure_1
     *
     * @return the value of s_b_monitor_hist.pressure_1
     *
     * @mbggenerated
     */
    public BigDecimal getPressure1() {
        return pressure1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.pressure_1
     *
     * @param pressure1 the value for s_b_monitor_hist.pressure_1
     *
     * @mbggenerated
     */
    public void setPressure1(BigDecimal pressure1) {
        this.pressure1 = pressure1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.pressure_2
     *
     * @return the value of s_b_monitor_hist.pressure_2
     *
     * @mbggenerated
     */
    public BigDecimal getPressure2() {
        return pressure2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.pressure_2
     *
     * @param pressure2 the value for s_b_monitor_hist.pressure_2
     *
     * @mbggenerated
     */
    public void setPressure2(BigDecimal pressure2) {
        this.pressure2 = pressure2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_monitor_hist.pressure_3
     *
     * @return the value of s_b_monitor_hist.pressure_3
     *
     * @mbggenerated
     */
    public BigDecimal getPressure3() {
        return pressure3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_monitor_hist.pressure_3
     *
     * @param pressure3 the value for s_b_monitor_hist.pressure_3
     *
     * @mbggenerated
     */
    public void setPressure3(BigDecimal pressure3) {
        this.pressure3 = pressure3;
    }
}