package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SBYincommSub {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.mm_sn
     *
     * @mbggenerated
     */
    private String mmSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.sensor_code
     *
     * @mbggenerated
     */
    private String sensorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.sensor_sn
     *
     * @mbggenerated
     */
    private Integer sensorSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.make_time
     *
     * @mbggenerated
     */
    private Date makeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.ytdata_time
     *
     * @mbggenerated
     */
    private Date ytdataTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.sensor_status
     *
     * @mbggenerated
     */
    private String sensorStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.signal_strength
     *
     * @mbggenerated
     */
    private Integer signalStrength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.value_type
     *
     * @mbggenerated
     */
    private Integer valueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.value_int
     *
     * @mbggenerated
     */
    private Integer valueInt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.value_num
     *
     * @mbggenerated
     */
    private BigDecimal valueNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.value_str
     *
     * @mbggenerated
     */
    private String valueStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.special_flag
     *
     * @mbggenerated
     */
    private String specialFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.special_area
     *
     * @mbggenerated
     */
    private String specialArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.bak1
     *
     * @mbggenerated
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.bak2
     *
     * @mbggenerated
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_sub.bak3
     *
     * @mbggenerated
     */
    private String bak3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.mm_sn
     *
     * @return the value of s_b_yincomm_sub.mm_sn
     *
     * @mbggenerated
     */
    public String getMmSn() {
        return mmSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.mm_sn
     *
     * @param mmSn the value for s_b_yincomm_sub.mm_sn
     *
     * @mbggenerated
     */
    public void setMmSn(String mmSn) {
        this.mmSn = mmSn == null ? null : mmSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.sensor_code
     *
     * @return the value of s_b_yincomm_sub.sensor_code
     *
     * @mbggenerated
     */
    public String getSensorCode() {
        return sensorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.sensor_code
     *
     * @param sensorCode the value for s_b_yincomm_sub.sensor_code
     *
     * @mbggenerated
     */
    public void setSensorCode(String sensorCode) {
        this.sensorCode = sensorCode == null ? null : sensorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.sensor_sn
     *
     * @return the value of s_b_yincomm_sub.sensor_sn
     *
     * @mbggenerated
     */
    public Integer getSensorSn() {
        return sensorSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.sensor_sn
     *
     * @param sensorSn the value for s_b_yincomm_sub.sensor_sn
     *
     * @mbggenerated
     */
    public void setSensorSn(Integer sensorSn) {
        this.sensorSn = sensorSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.make_time
     *
     * @return the value of s_b_yincomm_sub.make_time
     *
     * @mbggenerated
     */
    public Date getMakeTime() {
        return makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.make_time
     *
     * @param makeTime the value for s_b_yincomm_sub.make_time
     *
     * @mbggenerated
     */
    public void setMakeTime(Date makeTime) {
        this.makeTime = makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.ytdata_time
     *
     * @return the value of s_b_yincomm_sub.ytdata_time
     *
     * @mbggenerated
     */
    public Date getYtdataTime() {
        return ytdataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.ytdata_time
     *
     * @param ytdataTime the value for s_b_yincomm_sub.ytdata_time
     *
     * @mbggenerated
     */
    public void setYtdataTime(Date ytdataTime) {
        this.ytdataTime = ytdataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.sensor_status
     *
     * @return the value of s_b_yincomm_sub.sensor_status
     *
     * @mbggenerated
     */
    public String getSensorStatus() {
        return sensorStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.sensor_status
     *
     * @param sensorStatus the value for s_b_yincomm_sub.sensor_status
     *
     * @mbggenerated
     */
    public void setSensorStatus(String sensorStatus) {
        this.sensorStatus = sensorStatus == null ? null : sensorStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.signal_strength
     *
     * @return the value of s_b_yincomm_sub.signal_strength
     *
     * @mbggenerated
     */
    public Integer getSignalStrength() {
        return signalStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.signal_strength
     *
     * @param signalStrength the value for s_b_yincomm_sub.signal_strength
     *
     * @mbggenerated
     */
    public void setSignalStrength(Integer signalStrength) {
        this.signalStrength = signalStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.value_type
     *
     * @return the value of s_b_yincomm_sub.value_type
     *
     * @mbggenerated
     */
    public Integer getValueType() {
        return valueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.value_type
     *
     * @param valueType the value for s_b_yincomm_sub.value_type
     *
     * @mbggenerated
     */
    public void setValueType(Integer valueType) {
        this.valueType = valueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.value_int
     *
     * @return the value of s_b_yincomm_sub.value_int
     *
     * @mbggenerated
     */
    public Integer getValueInt() {
        return valueInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.value_int
     *
     * @param valueInt the value for s_b_yincomm_sub.value_int
     *
     * @mbggenerated
     */
    public void setValueInt(Integer valueInt) {
        this.valueInt = valueInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.value_num
     *
     * @return the value of s_b_yincomm_sub.value_num
     *
     * @mbggenerated
     */
    public BigDecimal getValueNum() {
        return valueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.value_num
     *
     * @param valueNum the value for s_b_yincomm_sub.value_num
     *
     * @mbggenerated
     */
    public void setValueNum(BigDecimal valueNum) {
        this.valueNum = valueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.value_str
     *
     * @return the value of s_b_yincomm_sub.value_str
     *
     * @mbggenerated
     */
    public String getValueStr() {
        return valueStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.value_str
     *
     * @param valueStr the value for s_b_yincomm_sub.value_str
     *
     * @mbggenerated
     */
    public void setValueStr(String valueStr) {
        this.valueStr = valueStr == null ? null : valueStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.special_flag
     *
     * @return the value of s_b_yincomm_sub.special_flag
     *
     * @mbggenerated
     */
    public String getSpecialFlag() {
        return specialFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.special_flag
     *
     * @param specialFlag the value for s_b_yincomm_sub.special_flag
     *
     * @mbggenerated
     */
    public void setSpecialFlag(String specialFlag) {
        this.specialFlag = specialFlag == null ? null : specialFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.special_area
     *
     * @return the value of s_b_yincomm_sub.special_area
     *
     * @mbggenerated
     */
    public String getSpecialArea() {
        return specialArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.special_area
     *
     * @param specialArea the value for s_b_yincomm_sub.special_area
     *
     * @mbggenerated
     */
    public void setSpecialArea(String specialArea) {
        this.specialArea = specialArea == null ? null : specialArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.bak1
     *
     * @return the value of s_b_yincomm_sub.bak1
     *
     * @mbggenerated
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.bak1
     *
     * @param bak1 the value for s_b_yincomm_sub.bak1
     *
     * @mbggenerated
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.bak2
     *
     * @return the value of s_b_yincomm_sub.bak2
     *
     * @mbggenerated
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.bak2
     *
     * @param bak2 the value for s_b_yincomm_sub.bak2
     *
     * @mbggenerated
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_sub.bak3
     *
     * @return the value of s_b_yincomm_sub.bak3
     *
     * @mbggenerated
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_sub.bak3
     *
     * @param bak3 the value for s_b_yincomm_sub.bak3
     *
     * @mbggenerated
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }
}