package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SBYincommData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_data.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_data.data_date
     *
     * @mbggenerated
     */
    private Date dataDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_data.data_type
     *
     * @mbggenerated
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_data.MM_sn
     *
     * @mbggenerated
     */
    private String mmSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_data.data_sn
     *
     * @mbggenerated
     */
    private Integer dataSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_data.sensor_sn_hex
     *
     * @mbggenerated
     */
    private String sensorSnHex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_data.sensor_sn
     *
     * @mbggenerated
     */
    private Long sensorSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_data.para_id
     *
     * @mbggenerated
     */
    private Integer paraId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_data.para_value
     *
     * @mbggenerated
     */
    private BigDecimal paraValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_data.receive_data
     *
     * @mbggenerated
     */
    private String receiveData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_data.confirm_data
     *
     * @mbggenerated
     */
    private String confirmData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_data.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_data.id
     *
     * @return the value of s_b_yincomm_data.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_data.id
     *
     * @param id the value for s_b_yincomm_data.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_data.data_date
     *
     * @return the value of s_b_yincomm_data.data_date
     *
     * @mbggenerated
     */
    public Date getDataDate() {
        return dataDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_data.data_date
     *
     * @param dataDate the value for s_b_yincomm_data.data_date
     *
     * @mbggenerated
     */
    public void setDataDate(Date dataDate) {
        this.dataDate = dataDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_data.data_type
     *
     * @return the value of s_b_yincomm_data.data_type
     *
     * @mbggenerated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_data.data_type
     *
     * @param dataType the value for s_b_yincomm_data.data_type
     *
     * @mbggenerated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_data.MM_sn
     *
     * @return the value of s_b_yincomm_data.MM_sn
     *
     * @mbggenerated
     */
    public String getMmSn() {
        return mmSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_data.MM_sn
     *
     * @param mmSn the value for s_b_yincomm_data.MM_sn
     *
     * @mbggenerated
     */
    public void setMmSn(String mmSn) {
        this.mmSn = mmSn == null ? null : mmSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_data.data_sn
     *
     * @return the value of s_b_yincomm_data.data_sn
     *
     * @mbggenerated
     */
    public Integer getDataSn() {
        return dataSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_data.data_sn
     *
     * @param dataSn the value for s_b_yincomm_data.data_sn
     *
     * @mbggenerated
     */
    public void setDataSn(Integer dataSn) {
        this.dataSn = dataSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_data.sensor_sn_hex
     *
     * @return the value of s_b_yincomm_data.sensor_sn_hex
     *
     * @mbggenerated
     */
    public String getSensorSnHex() {
        return sensorSnHex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_data.sensor_sn_hex
     *
     * @param sensorSnHex the value for s_b_yincomm_data.sensor_sn_hex
     *
     * @mbggenerated
     */
    public void setSensorSnHex(String sensorSnHex) {
        this.sensorSnHex = sensorSnHex == null ? null : sensorSnHex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_data.sensor_sn
     *
     * @return the value of s_b_yincomm_data.sensor_sn
     *
     * @mbggenerated
     */
    public Long getSensorSn() {
        return sensorSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_data.sensor_sn
     *
     * @param sensorSn the value for s_b_yincomm_data.sensor_sn
     *
     * @mbggenerated
     */
    public void setSensorSn(Long sensorSn) {
        this.sensorSn = sensorSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_data.para_id
     *
     * @return the value of s_b_yincomm_data.para_id
     *
     * @mbggenerated
     */
    public Integer getParaId() {
        return paraId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_data.para_id
     *
     * @param paraId the value for s_b_yincomm_data.para_id
     *
     * @mbggenerated
     */
    public void setParaId(Integer paraId) {
        this.paraId = paraId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_data.para_value
     *
     * @return the value of s_b_yincomm_data.para_value
     *
     * @mbggenerated
     */
    public BigDecimal getParaValue() {
        return paraValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_data.para_value
     *
     * @param paraValue the value for s_b_yincomm_data.para_value
     *
     * @mbggenerated
     */
    public void setParaValue(BigDecimal paraValue) {
        this.paraValue = paraValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_data.receive_data
     *
     * @return the value of s_b_yincomm_data.receive_data
     *
     * @mbggenerated
     */
    public String getReceiveData() {
        return receiveData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_data.receive_data
     *
     * @param receiveData the value for s_b_yincomm_data.receive_data
     *
     * @mbggenerated
     */
    public void setReceiveData(String receiveData) {
        this.receiveData = receiveData == null ? null : receiveData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_data.confirm_data
     *
     * @return the value of s_b_yincomm_data.confirm_data
     *
     * @mbggenerated
     */
    public String getConfirmData() {
        return confirmData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_data.confirm_data
     *
     * @param confirmData the value for s_b_yincomm_data.confirm_data
     *
     * @mbggenerated
     */
    public void setConfirmData(String confirmData) {
        this.confirmData = confirmData == null ? null : confirmData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_data.create_date
     *
     * @return the value of s_b_yincomm_data.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_data.create_date
     *
     * @param createDate the value for s_b_yincomm_data.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}