package com.mtc.entity.app;

import java.util.Date;

public class SLUserImei {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_user_imei.imei_no
     *
     * @mbggenerated
     */
    private String imeiNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_user_imei.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_user_imei.user_code
     *
     * @mbggenerated
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_user_imei.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_user_imei.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_user_imei.sys_version
     *
     * @mbggenerated
     */
    private String sysVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_user_imei.platform
     *
     * @mbggenerated
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_user_imei.bak1
     *
     * @mbggenerated
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_user_imei.bak2
     *
     * @mbggenerated
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_user_imei.create_person
     *
     * @mbggenerated
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_user_imei.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_user_imei.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_user_imei.imei_no
     *
     * @return the value of s_l_user_imei.imei_no
     *
     * @mbggenerated
     */
    public String getImeiNo() {
        return imeiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_user_imei.imei_no
     *
     * @param imeiNo the value for s_l_user_imei.imei_no
     *
     * @mbggenerated
     */
    public void setImeiNo(String imeiNo) {
        this.imeiNo = imeiNo == null ? null : imeiNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_user_imei.user_id
     *
     * @return the value of s_l_user_imei.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_user_imei.user_id
     *
     * @param userId the value for s_l_user_imei.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_user_imei.user_code
     *
     * @return the value of s_l_user_imei.user_code
     *
     * @mbggenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_user_imei.user_code
     *
     * @param userCode the value for s_l_user_imei.user_code
     *
     * @mbggenerated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_user_imei.uuid
     *
     * @return the value of s_l_user_imei.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_user_imei.uuid
     *
     * @param uuid the value for s_l_user_imei.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_user_imei.model
     *
     * @return the value of s_l_user_imei.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_user_imei.model
     *
     * @param model the value for s_l_user_imei.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_user_imei.sys_version
     *
     * @return the value of s_l_user_imei.sys_version
     *
     * @mbggenerated
     */
    public String getSysVersion() {
        return sysVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_user_imei.sys_version
     *
     * @param sysVersion the value for s_l_user_imei.sys_version
     *
     * @mbggenerated
     */
    public void setSysVersion(String sysVersion) {
        this.sysVersion = sysVersion == null ? null : sysVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_user_imei.platform
     *
     * @return the value of s_l_user_imei.platform
     *
     * @mbggenerated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_user_imei.platform
     *
     * @param platform the value for s_l_user_imei.platform
     *
     * @mbggenerated
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_user_imei.bak1
     *
     * @return the value of s_l_user_imei.bak1
     *
     * @mbggenerated
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_user_imei.bak1
     *
     * @param bak1 the value for s_l_user_imei.bak1
     *
     * @mbggenerated
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_user_imei.bak2
     *
     * @return the value of s_l_user_imei.bak2
     *
     * @mbggenerated
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_user_imei.bak2
     *
     * @param bak2 the value for s_l_user_imei.bak2
     *
     * @mbggenerated
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_user_imei.create_person
     *
     * @return the value of s_l_user_imei.create_person
     *
     * @mbggenerated
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_user_imei.create_person
     *
     * @param createPerson the value for s_l_user_imei.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_user_imei.create_date
     *
     * @return the value of s_l_user_imei.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_user_imei.create_date
     *
     * @param createDate the value for s_l_user_imei.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_user_imei.create_time
     *
     * @return the value of s_l_user_imei.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_user_imei.create_time
     *
     * @param createTime the value for s_l_user_imei.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}