package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SBDataInput {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.farm_breed_id
     *
     * @mbggenerated
     */
    private Integer farmBreedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.house_breed_id
     *
     * @mbggenerated
     */
    private Integer houseBreedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.farm_id
     *
     * @mbggenerated
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.house_id
     *
     * @mbggenerated
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.data_type
     *
     * @mbggenerated
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.value_type
     *
     * @mbggenerated
     */
    private String valueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.val_int
     *
     * @mbggenerated
     */
    private Integer valInt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.val_num
     *
     * @mbggenerated
     */
    private BigDecimal valNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.val_varc
     *
     * @mbggenerated
     */
    private String valVarc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.val_date
     *
     * @mbggenerated
     */
    private Date valDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.freeze_status
     *
     * @mbggenerated
     */
    private String freezeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.create_person
     *
     * @mbggenerated
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.modify_person
     *
     * @mbggenerated
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_data_input.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.id
     *
     * @return the value of s_b_data_input.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.id
     *
     * @param id the value for s_b_data_input.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.farm_breed_id
     *
     * @return the value of s_b_data_input.farm_breed_id
     *
     * @mbggenerated
     */
    public Integer getFarmBreedId() {
        return farmBreedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.farm_breed_id
     *
     * @param farmBreedId the value for s_b_data_input.farm_breed_id
     *
     * @mbggenerated
     */
    public void setFarmBreedId(Integer farmBreedId) {
        this.farmBreedId = farmBreedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.house_breed_id
     *
     * @return the value of s_b_data_input.house_breed_id
     *
     * @mbggenerated
     */
    public Integer getHouseBreedId() {
        return houseBreedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.house_breed_id
     *
     * @param houseBreedId the value for s_b_data_input.house_breed_id
     *
     * @mbggenerated
     */
    public void setHouseBreedId(Integer houseBreedId) {
        this.houseBreedId = houseBreedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.farm_id
     *
     * @return the value of s_b_data_input.farm_id
     *
     * @mbggenerated
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.farm_id
     *
     * @param farmId the value for s_b_data_input.farm_id
     *
     * @mbggenerated
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.house_id
     *
     * @return the value of s_b_data_input.house_id
     *
     * @mbggenerated
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.house_id
     *
     * @param houseId the value for s_b_data_input.house_id
     *
     * @mbggenerated
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.age
     *
     * @return the value of s_b_data_input.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.age
     *
     * @param age the value for s_b_data_input.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.data_type
     *
     * @return the value of s_b_data_input.data_type
     *
     * @mbggenerated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.data_type
     *
     * @param dataType the value for s_b_data_input.data_type
     *
     * @mbggenerated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.value_type
     *
     * @return the value of s_b_data_input.value_type
     *
     * @mbggenerated
     */
    public String getValueType() {
        return valueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.value_type
     *
     * @param valueType the value for s_b_data_input.value_type
     *
     * @mbggenerated
     */
    public void setValueType(String valueType) {
        this.valueType = valueType == null ? null : valueType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.val_int
     *
     * @return the value of s_b_data_input.val_int
     *
     * @mbggenerated
     */
    public Integer getValInt() {
        return valInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.val_int
     *
     * @param valInt the value for s_b_data_input.val_int
     *
     * @mbggenerated
     */
    public void setValInt(Integer valInt) {
        this.valInt = valInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.val_num
     *
     * @return the value of s_b_data_input.val_num
     *
     * @mbggenerated
     */
    public BigDecimal getValNum() {
        return valNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.val_num
     *
     * @param valNum the value for s_b_data_input.val_num
     *
     * @mbggenerated
     */
    public void setValNum(BigDecimal valNum) {
        this.valNum = valNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.val_varc
     *
     * @return the value of s_b_data_input.val_varc
     *
     * @mbggenerated
     */
    public String getValVarc() {
        return valVarc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.val_varc
     *
     * @param valVarc the value for s_b_data_input.val_varc
     *
     * @mbggenerated
     */
    public void setValVarc(String valVarc) {
        this.valVarc = valVarc == null ? null : valVarc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.val_date
     *
     * @return the value of s_b_data_input.val_date
     *
     * @mbggenerated
     */
    public Date getValDate() {
        return valDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.val_date
     *
     * @param valDate the value for s_b_data_input.val_date
     *
     * @mbggenerated
     */
    public void setValDate(Date valDate) {
        this.valDate = valDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.freeze_status
     *
     * @return the value of s_b_data_input.freeze_status
     *
     * @mbggenerated
     */
    public String getFreezeStatus() {
        return freezeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.freeze_status
     *
     * @param freezeStatus the value for s_b_data_input.freeze_status
     *
     * @mbggenerated
     */
    public void setFreezeStatus(String freezeStatus) {
        this.freezeStatus = freezeStatus == null ? null : freezeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.create_person
     *
     * @return the value of s_b_data_input.create_person
     *
     * @mbggenerated
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.create_person
     *
     * @param createPerson the value for s_b_data_input.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.create_date
     *
     * @return the value of s_b_data_input.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.create_date
     *
     * @param createDate the value for s_b_data_input.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.create_time
     *
     * @return the value of s_b_data_input.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.create_time
     *
     * @param createTime the value for s_b_data_input.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.modify_person
     *
     * @return the value of s_b_data_input.modify_person
     *
     * @mbggenerated
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.modify_person
     *
     * @param modifyPerson the value for s_b_data_input.modify_person
     *
     * @mbggenerated
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.modify_date
     *
     * @return the value of s_b_data_input.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.modify_date
     *
     * @param modifyDate the value for s_b_data_input.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_data_input.modify_time
     *
     * @return the value of s_b_data_input.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_data_input.modify_time
     *
     * @param modifyTime the value for s_b_data_input.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}