package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SBEggSells {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.farm_id
     *
     * @mbggenerated
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.sell_date
     *
     * @mbggenerated
     */
    private Date sellDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.is_history
     *
     * @mbggenerated
     */
    private String isHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.day_age
     *
     * @mbggenerated
     */
    private Integer dayAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.week_age
     *
     * @mbggenerated
     */
    private Integer weekAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.farm_breed_id
     *
     * @mbggenerated
     */
    private Integer farmBreedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.good_box_size
     *
     * @mbggenerated
     */
    private BigDecimal goodBoxSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.good_price_type
     *
     * @mbggenerated
     */
    private String goodPriceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.good_price_value
     *
     * @mbggenerated
     */
    private BigDecimal goodPriceValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.good_salebox_num
     *
     * @mbggenerated
     */
    private BigDecimal goodSaleboxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.good_sale_weight
     *
     * @mbggenerated
     */
    private BigDecimal goodSaleWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.good_sale_money
     *
     * @mbggenerated
     */
    private BigDecimal goodSaleMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.broken_box_size
     *
     * @mbggenerated
     */
    private BigDecimal brokenBoxSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.broken_price_type
     *
     * @mbggenerated
     */
    private String brokenPriceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.broken_price_value
     *
     * @mbggenerated
     */
    private BigDecimal brokenPriceValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.broken_salebox_num
     *
     * @mbggenerated
     */
    private BigDecimal brokenSaleboxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.broken_sale_weight
     *
     * @mbggenerated
     */
    private BigDecimal brokenSaleWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.broken_sale_money
     *
     * @mbggenerated
     */
    private BigDecimal brokenSaleMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.chicken_manure
     *
     * @mbggenerated
     */
    private BigDecimal chickenManure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.int_bak1
     *
     * @mbggenerated
     */
    private Integer intBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.int_bak2
     *
     * @mbggenerated
     */
    private Integer intBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.int_bak3
     *
     * @mbggenerated
     */
    private Integer intBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.num_bak1
     *
     * @mbggenerated
     */
    private BigDecimal numBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.num_bak2
     *
     * @mbggenerated
     */
    private BigDecimal numBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.num_bak3
     *
     * @mbggenerated
     */
    private BigDecimal numBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.var_bak1
     *
     * @mbggenerated
     */
    private String varBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.var_bak2
     *
     * @mbggenerated
     */
    private String varBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.var_bak3
     *
     * @mbggenerated
     */
    private String varBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.date_bak1
     *
     * @mbggenerated
     */
    private Date dateBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.date_bak2
     *
     * @mbggenerated
     */
    private Date dateBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.date_bak3
     *
     * @mbggenerated
     */
    private Date dateBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.create_person
     *
     * @mbggenerated
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.modify_person
     *
     * @mbggenerated
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_egg_sells.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.farm_id
     *
     * @return the value of s_b_egg_sells.farm_id
     *
     * @mbggenerated
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.farm_id
     *
     * @param farmId the value for s_b_egg_sells.farm_id
     *
     * @mbggenerated
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.sell_date
     *
     * @return the value of s_b_egg_sells.sell_date
     *
     * @mbggenerated
     */
    public Date getSellDate() {
        return sellDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.sell_date
     *
     * @param sellDate the value for s_b_egg_sells.sell_date
     *
     * @mbggenerated
     */
    public void setSellDate(Date sellDate) {
        this.sellDate = sellDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.is_history
     *
     * @return the value of s_b_egg_sells.is_history
     *
     * @mbggenerated
     */
    public String getIsHistory() {
        return isHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.is_history
     *
     * @param isHistory the value for s_b_egg_sells.is_history
     *
     * @mbggenerated
     */
    public void setIsHistory(String isHistory) {
        this.isHistory = isHistory == null ? null : isHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.day_age
     *
     * @return the value of s_b_egg_sells.day_age
     *
     * @mbggenerated
     */
    public Integer getDayAge() {
        return dayAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.day_age
     *
     * @param dayAge the value for s_b_egg_sells.day_age
     *
     * @mbggenerated
     */
    public void setDayAge(Integer dayAge) {
        this.dayAge = dayAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.week_age
     *
     * @return the value of s_b_egg_sells.week_age
     *
     * @mbggenerated
     */
    public Integer getWeekAge() {
        return weekAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.week_age
     *
     * @param weekAge the value for s_b_egg_sells.week_age
     *
     * @mbggenerated
     */
    public void setWeekAge(Integer weekAge) {
        this.weekAge = weekAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.farm_breed_id
     *
     * @return the value of s_b_egg_sells.farm_breed_id
     *
     * @mbggenerated
     */
    public Integer getFarmBreedId() {
        return farmBreedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.farm_breed_id
     *
     * @param farmBreedId the value for s_b_egg_sells.farm_breed_id
     *
     * @mbggenerated
     */
    public void setFarmBreedId(Integer farmBreedId) {
        this.farmBreedId = farmBreedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.good_box_size
     *
     * @return the value of s_b_egg_sells.good_box_size
     *
     * @mbggenerated
     */
    public BigDecimal getGoodBoxSize() {
        return goodBoxSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.good_box_size
     *
     * @param goodBoxSize the value for s_b_egg_sells.good_box_size
     *
     * @mbggenerated
     */
    public void setGoodBoxSize(BigDecimal goodBoxSize) {
        this.goodBoxSize = goodBoxSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.good_price_type
     *
     * @return the value of s_b_egg_sells.good_price_type
     *
     * @mbggenerated
     */
    public String getGoodPriceType() {
        return goodPriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.good_price_type
     *
     * @param goodPriceType the value for s_b_egg_sells.good_price_type
     *
     * @mbggenerated
     */
    public void setGoodPriceType(String goodPriceType) {
        this.goodPriceType = goodPriceType == null ? null : goodPriceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.good_price_value
     *
     * @return the value of s_b_egg_sells.good_price_value
     *
     * @mbggenerated
     */
    public BigDecimal getGoodPriceValue() {
        return goodPriceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.good_price_value
     *
     * @param goodPriceValue the value for s_b_egg_sells.good_price_value
     *
     * @mbggenerated
     */
    public void setGoodPriceValue(BigDecimal goodPriceValue) {
        this.goodPriceValue = goodPriceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.good_salebox_num
     *
     * @return the value of s_b_egg_sells.good_salebox_num
     *
     * @mbggenerated
     */
    public BigDecimal getGoodSaleboxNum() {
        return goodSaleboxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.good_salebox_num
     *
     * @param goodSaleboxNum the value for s_b_egg_sells.good_salebox_num
     *
     * @mbggenerated
     */
    public void setGoodSaleboxNum(BigDecimal goodSaleboxNum) {
        this.goodSaleboxNum = goodSaleboxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.good_sale_weight
     *
     * @return the value of s_b_egg_sells.good_sale_weight
     *
     * @mbggenerated
     */
    public BigDecimal getGoodSaleWeight() {
        return goodSaleWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.good_sale_weight
     *
     * @param goodSaleWeight the value for s_b_egg_sells.good_sale_weight
     *
     * @mbggenerated
     */
    public void setGoodSaleWeight(BigDecimal goodSaleWeight) {
        this.goodSaleWeight = goodSaleWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.good_sale_money
     *
     * @return the value of s_b_egg_sells.good_sale_money
     *
     * @mbggenerated
     */
    public BigDecimal getGoodSaleMoney() {
        return goodSaleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.good_sale_money
     *
     * @param goodSaleMoney the value for s_b_egg_sells.good_sale_money
     *
     * @mbggenerated
     */
    public void setGoodSaleMoney(BigDecimal goodSaleMoney) {
        this.goodSaleMoney = goodSaleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.broken_box_size
     *
     * @return the value of s_b_egg_sells.broken_box_size
     *
     * @mbggenerated
     */
    public BigDecimal getBrokenBoxSize() {
        return brokenBoxSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.broken_box_size
     *
     * @param brokenBoxSize the value for s_b_egg_sells.broken_box_size
     *
     * @mbggenerated
     */
    public void setBrokenBoxSize(BigDecimal brokenBoxSize) {
        this.brokenBoxSize = brokenBoxSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.broken_price_type
     *
     * @return the value of s_b_egg_sells.broken_price_type
     *
     * @mbggenerated
     */
    public String getBrokenPriceType() {
        return brokenPriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.broken_price_type
     *
     * @param brokenPriceType the value for s_b_egg_sells.broken_price_type
     *
     * @mbggenerated
     */
    public void setBrokenPriceType(String brokenPriceType) {
        this.brokenPriceType = brokenPriceType == null ? null : brokenPriceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.broken_price_value
     *
     * @return the value of s_b_egg_sells.broken_price_value
     *
     * @mbggenerated
     */
    public BigDecimal getBrokenPriceValue() {
        return brokenPriceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.broken_price_value
     *
     * @param brokenPriceValue the value for s_b_egg_sells.broken_price_value
     *
     * @mbggenerated
     */
    public void setBrokenPriceValue(BigDecimal brokenPriceValue) {
        this.brokenPriceValue = brokenPriceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.broken_salebox_num
     *
     * @return the value of s_b_egg_sells.broken_salebox_num
     *
     * @mbggenerated
     */
    public BigDecimal getBrokenSaleboxNum() {
        return brokenSaleboxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.broken_salebox_num
     *
     * @param brokenSaleboxNum the value for s_b_egg_sells.broken_salebox_num
     *
     * @mbggenerated
     */
    public void setBrokenSaleboxNum(BigDecimal brokenSaleboxNum) {
        this.brokenSaleboxNum = brokenSaleboxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.broken_sale_weight
     *
     * @return the value of s_b_egg_sells.broken_sale_weight
     *
     * @mbggenerated
     */
    public BigDecimal getBrokenSaleWeight() {
        return brokenSaleWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.broken_sale_weight
     *
     * @param brokenSaleWeight the value for s_b_egg_sells.broken_sale_weight
     *
     * @mbggenerated
     */
    public void setBrokenSaleWeight(BigDecimal brokenSaleWeight) {
        this.brokenSaleWeight = brokenSaleWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.broken_sale_money
     *
     * @return the value of s_b_egg_sells.broken_sale_money
     *
     * @mbggenerated
     */
    public BigDecimal getBrokenSaleMoney() {
        return brokenSaleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.broken_sale_money
     *
     * @param brokenSaleMoney the value for s_b_egg_sells.broken_sale_money
     *
     * @mbggenerated
     */
    public void setBrokenSaleMoney(BigDecimal brokenSaleMoney) {
        this.brokenSaleMoney = brokenSaleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.chicken_manure
     *
     * @return the value of s_b_egg_sells.chicken_manure
     *
     * @mbggenerated
     */
    public BigDecimal getChickenManure() {
        return chickenManure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.chicken_manure
     *
     * @param chickenManure the value for s_b_egg_sells.chicken_manure
     *
     * @mbggenerated
     */
    public void setChickenManure(BigDecimal chickenManure) {
        this.chickenManure = chickenManure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.int_bak1
     *
     * @return the value of s_b_egg_sells.int_bak1
     *
     * @mbggenerated
     */
    public Integer getIntBak1() {
        return intBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.int_bak1
     *
     * @param intBak1 the value for s_b_egg_sells.int_bak1
     *
     * @mbggenerated
     */
    public void setIntBak1(Integer intBak1) {
        this.intBak1 = intBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.int_bak2
     *
     * @return the value of s_b_egg_sells.int_bak2
     *
     * @mbggenerated
     */
    public Integer getIntBak2() {
        return intBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.int_bak2
     *
     * @param intBak2 the value for s_b_egg_sells.int_bak2
     *
     * @mbggenerated
     */
    public void setIntBak2(Integer intBak2) {
        this.intBak2 = intBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.int_bak3
     *
     * @return the value of s_b_egg_sells.int_bak3
     *
     * @mbggenerated
     */
    public Integer getIntBak3() {
        return intBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.int_bak3
     *
     * @param intBak3 the value for s_b_egg_sells.int_bak3
     *
     * @mbggenerated
     */
    public void setIntBak3(Integer intBak3) {
        this.intBak3 = intBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.num_bak1
     *
     * @return the value of s_b_egg_sells.num_bak1
     *
     * @mbggenerated
     */
    public BigDecimal getNumBak1() {
        return numBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.num_bak1
     *
     * @param numBak1 the value for s_b_egg_sells.num_bak1
     *
     * @mbggenerated
     */
    public void setNumBak1(BigDecimal numBak1) {
        this.numBak1 = numBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.num_bak2
     *
     * @return the value of s_b_egg_sells.num_bak2
     *
     * @mbggenerated
     */
    public BigDecimal getNumBak2() {
        return numBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.num_bak2
     *
     * @param numBak2 the value for s_b_egg_sells.num_bak2
     *
     * @mbggenerated
     */
    public void setNumBak2(BigDecimal numBak2) {
        this.numBak2 = numBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.num_bak3
     *
     * @return the value of s_b_egg_sells.num_bak3
     *
     * @mbggenerated
     */
    public BigDecimal getNumBak3() {
        return numBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.num_bak3
     *
     * @param numBak3 the value for s_b_egg_sells.num_bak3
     *
     * @mbggenerated
     */
    public void setNumBak3(BigDecimal numBak3) {
        this.numBak3 = numBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.var_bak1
     *
     * @return the value of s_b_egg_sells.var_bak1
     *
     * @mbggenerated
     */
    public String getVarBak1() {
        return varBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.var_bak1
     *
     * @param varBak1 the value for s_b_egg_sells.var_bak1
     *
     * @mbggenerated
     */
    public void setVarBak1(String varBak1) {
        this.varBak1 = varBak1 == null ? null : varBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.var_bak2
     *
     * @return the value of s_b_egg_sells.var_bak2
     *
     * @mbggenerated
     */
    public String getVarBak2() {
        return varBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.var_bak2
     *
     * @param varBak2 the value for s_b_egg_sells.var_bak2
     *
     * @mbggenerated
     */
    public void setVarBak2(String varBak2) {
        this.varBak2 = varBak2 == null ? null : varBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.var_bak3
     *
     * @return the value of s_b_egg_sells.var_bak3
     *
     * @mbggenerated
     */
    public String getVarBak3() {
        return varBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.var_bak3
     *
     * @param varBak3 the value for s_b_egg_sells.var_bak3
     *
     * @mbggenerated
     */
    public void setVarBak3(String varBak3) {
        this.varBak3 = varBak3 == null ? null : varBak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.date_bak1
     *
     * @return the value of s_b_egg_sells.date_bak1
     *
     * @mbggenerated
     */
    public Date getDateBak1() {
        return dateBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.date_bak1
     *
     * @param dateBak1 the value for s_b_egg_sells.date_bak1
     *
     * @mbggenerated
     */
    public void setDateBak1(Date dateBak1) {
        this.dateBak1 = dateBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.date_bak2
     *
     * @return the value of s_b_egg_sells.date_bak2
     *
     * @mbggenerated
     */
    public Date getDateBak2() {
        return dateBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.date_bak2
     *
     * @param dateBak2 the value for s_b_egg_sells.date_bak2
     *
     * @mbggenerated
     */
    public void setDateBak2(Date dateBak2) {
        this.dateBak2 = dateBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.date_bak3
     *
     * @return the value of s_b_egg_sells.date_bak3
     *
     * @mbggenerated
     */
    public Date getDateBak3() {
        return dateBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.date_bak3
     *
     * @param dateBak3 the value for s_b_egg_sells.date_bak3
     *
     * @mbggenerated
     */
    public void setDateBak3(Date dateBak3) {
        this.dateBak3 = dateBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.create_person
     *
     * @return the value of s_b_egg_sells.create_person
     *
     * @mbggenerated
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.create_person
     *
     * @param createPerson the value for s_b_egg_sells.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.create_date
     *
     * @return the value of s_b_egg_sells.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.create_date
     *
     * @param createDate the value for s_b_egg_sells.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.create_time
     *
     * @return the value of s_b_egg_sells.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.create_time
     *
     * @param createTime the value for s_b_egg_sells.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.modify_person
     *
     * @return the value of s_b_egg_sells.modify_person
     *
     * @mbggenerated
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.modify_person
     *
     * @param modifyPerson the value for s_b_egg_sells.modify_person
     *
     * @mbggenerated
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.modify_date
     *
     * @return the value of s_b_egg_sells.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.modify_date
     *
     * @param modifyDate the value for s_b_egg_sells.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_egg_sells.modify_time
     *
     * @return the value of s_b_egg_sells.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_egg_sells.modify_time
     *
     * @param modifyTime the value for s_b_egg_sells.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}