package com.mtc.entity.app;

import java.util.Date;

public class SBFarmBreed {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.farm_id
     *
     * @mbggenerated
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.batch_code
     *
     * @mbggenerated
     */
    private String batchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.place_date
     *
     * @mbggenerated
     */
    private Date placeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.place_num
     *
     * @mbggenerated
     */
    private Integer placeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.breed_days
     *
     * @mbggenerated
     */
    private Integer breedDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.market_date
     *
     * @mbggenerated
     */
    private Date marketDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.doc_vendors
     *
     * @mbggenerated
     */
    private String docVendors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.breed
     *
     * @mbggenerated
     */
    private String breed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.settle_date
     *
     * @mbggenerated
     */
    private Date settleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.batch_status
     *
     * @mbggenerated
     */
    private String batchStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.create_person
     *
     * @mbggenerated
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.modify_person
     *
     * @mbggenerated
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_breed.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.id
     *
     * @return the value of s_b_farm_breed.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.id
     *
     * @param id the value for s_b_farm_breed.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.farm_id
     *
     * @return the value of s_b_farm_breed.farm_id
     *
     * @mbggenerated
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.farm_id
     *
     * @param farmId the value for s_b_farm_breed.farm_id
     *
     * @mbggenerated
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.batch_code
     *
     * @return the value of s_b_farm_breed.batch_code
     *
     * @mbggenerated
     */
    public String getBatchCode() {
        return batchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.batch_code
     *
     * @param batchCode the value for s_b_farm_breed.batch_code
     *
     * @mbggenerated
     */
    public void setBatchCode(String batchCode) {
        this.batchCode = batchCode == null ? null : batchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.place_date
     *
     * @return the value of s_b_farm_breed.place_date
     *
     * @mbggenerated
     */
    public Date getPlaceDate() {
        return placeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.place_date
     *
     * @param placeDate the value for s_b_farm_breed.place_date
     *
     * @mbggenerated
     */
    public void setPlaceDate(Date placeDate) {
        this.placeDate = placeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.place_num
     *
     * @return the value of s_b_farm_breed.place_num
     *
     * @mbggenerated
     */
    public Integer getPlaceNum() {
        return placeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.place_num
     *
     * @param placeNum the value for s_b_farm_breed.place_num
     *
     * @mbggenerated
     */
    public void setPlaceNum(Integer placeNum) {
        this.placeNum = placeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.breed_days
     *
     * @return the value of s_b_farm_breed.breed_days
     *
     * @mbggenerated
     */
    public Integer getBreedDays() {
        return breedDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.breed_days
     *
     * @param breedDays the value for s_b_farm_breed.breed_days
     *
     * @mbggenerated
     */
    public void setBreedDays(Integer breedDays) {
        this.breedDays = breedDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.market_date
     *
     * @return the value of s_b_farm_breed.market_date
     *
     * @mbggenerated
     */
    public Date getMarketDate() {
        return marketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.market_date
     *
     * @param marketDate the value for s_b_farm_breed.market_date
     *
     * @mbggenerated
     */
    public void setMarketDate(Date marketDate) {
        this.marketDate = marketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.doc_vendors
     *
     * @return the value of s_b_farm_breed.doc_vendors
     *
     * @mbggenerated
     */
    public String getDocVendors() {
        return docVendors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.doc_vendors
     *
     * @param docVendors the value for s_b_farm_breed.doc_vendors
     *
     * @mbggenerated
     */
    public void setDocVendors(String docVendors) {
        this.docVendors = docVendors == null ? null : docVendors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.breed
     *
     * @return the value of s_b_farm_breed.breed
     *
     * @mbggenerated
     */
    public String getBreed() {
        return breed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.breed
     *
     * @param breed the value for s_b_farm_breed.breed
     *
     * @mbggenerated
     */
    public void setBreed(String breed) {
        this.breed = breed == null ? null : breed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.settle_date
     *
     * @return the value of s_b_farm_breed.settle_date
     *
     * @mbggenerated
     */
    public Date getSettleDate() {
        return settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.settle_date
     *
     * @param settleDate the value for s_b_farm_breed.settle_date
     *
     * @mbggenerated
     */
    public void setSettleDate(Date settleDate) {
        this.settleDate = settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.batch_status
     *
     * @return the value of s_b_farm_breed.batch_status
     *
     * @mbggenerated
     */
    public String getBatchStatus() {
        return batchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.batch_status
     *
     * @param batchStatus the value for s_b_farm_breed.batch_status
     *
     * @mbggenerated
     */
    public void setBatchStatus(String batchStatus) {
        this.batchStatus = batchStatus == null ? null : batchStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.create_person
     *
     * @return the value of s_b_farm_breed.create_person
     *
     * @mbggenerated
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.create_person
     *
     * @param createPerson the value for s_b_farm_breed.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.create_date
     *
     * @return the value of s_b_farm_breed.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.create_date
     *
     * @param createDate the value for s_b_farm_breed.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.create_time
     *
     * @return the value of s_b_farm_breed.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.create_time
     *
     * @param createTime the value for s_b_farm_breed.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.modify_person
     *
     * @return the value of s_b_farm_breed.modify_person
     *
     * @mbggenerated
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.modify_person
     *
     * @param modifyPerson the value for s_b_farm_breed.modify_person
     *
     * @mbggenerated
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.modify_date
     *
     * @return the value of s_b_farm_breed.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.modify_date
     *
     * @param modifyDate the value for s_b_farm_breed.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_breed.modify_time
     *
     * @return the value of s_b_farm_breed.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_breed.modify_time
     *
     * @param modifyTime the value for s_b_farm_breed.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}