package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SBLayerFarmSettle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.farm_id
     *
     * @mbggenerated
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.farm_breed_id
     *
     * @mbggenerated
     */
    private Integer farmBreedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.house_id
     *
     * @mbggenerated
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.settle_month
     *
     * @mbggenerated
     */
    private String settleMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.fee_type
     *
     * @mbggenerated
     */
    private String feeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.fee_code
     *
     * @mbggenerated
     */
    private String feeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.fee_name
     *
     * @mbggenerated
     */
    private String feeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.company_code
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.price_pu
     *
     * @mbggenerated
     */
    private BigDecimal pricePu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.quentity
     *
     * @mbggenerated
     */
    private Integer quentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.weight
     *
     * @mbggenerated
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.money_sum
     *
     * @mbggenerated
     */
    private BigDecimal moneySum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.bak_var1
     *
     * @mbggenerated
     */
    private String bakVar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.bak_var2
     *
     * @mbggenerated
     */
    private String bakVar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.bak_var3
     *
     * @mbggenerated
     */
    private String bakVar3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.bak_num1
     *
     * @mbggenerated
     */
    private BigDecimal bakNum1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.bak_num2
     *
     * @mbggenerated
     */
    private BigDecimal bakNum2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.bak_num3
     *
     * @mbggenerated
     */
    private BigDecimal bakNum3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.bak_num4
     *
     * @mbggenerated
     */
    private BigDecimal bakNum4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.bak_num5
     *
     * @mbggenerated
     */
    private BigDecimal bakNum5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.bak_num6
     *
     * @mbggenerated
     */
    private BigDecimal bakNum6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.create_person
     *
     * @mbggenerated
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.modify_person
     *
     * @mbggenerated
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_layer_farm_settle.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.id
     *
     * @return the value of s_b_layer_farm_settle.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.id
     *
     * @param id the value for s_b_layer_farm_settle.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.farm_id
     *
     * @return the value of s_b_layer_farm_settle.farm_id
     *
     * @mbggenerated
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.farm_id
     *
     * @param farmId the value for s_b_layer_farm_settle.farm_id
     *
     * @mbggenerated
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.farm_breed_id
     *
     * @return the value of s_b_layer_farm_settle.farm_breed_id
     *
     * @mbggenerated
     */
    public Integer getFarmBreedId() {
        return farmBreedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.farm_breed_id
     *
     * @param farmBreedId the value for s_b_layer_farm_settle.farm_breed_id
     *
     * @mbggenerated
     */
    public void setFarmBreedId(Integer farmBreedId) {
        this.farmBreedId = farmBreedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.house_id
     *
     * @return the value of s_b_layer_farm_settle.house_id
     *
     * @mbggenerated
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.house_id
     *
     * @param houseId the value for s_b_layer_farm_settle.house_id
     *
     * @mbggenerated
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.settle_month
     *
     * @return the value of s_b_layer_farm_settle.settle_month
     *
     * @mbggenerated
     */
    public String getSettleMonth() {
        return settleMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.settle_month
     *
     * @param settleMonth the value for s_b_layer_farm_settle.settle_month
     *
     * @mbggenerated
     */
    public void setSettleMonth(String settleMonth) {
        this.settleMonth = settleMonth == null ? null : settleMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.fee_type
     *
     * @return the value of s_b_layer_farm_settle.fee_type
     *
     * @mbggenerated
     */
    public String getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.fee_type
     *
     * @param feeType the value for s_b_layer_farm_settle.fee_type
     *
     * @mbggenerated
     */
    public void setFeeType(String feeType) {
        this.feeType = feeType == null ? null : feeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.fee_code
     *
     * @return the value of s_b_layer_farm_settle.fee_code
     *
     * @mbggenerated
     */
    public String getFeeCode() {
        return feeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.fee_code
     *
     * @param feeCode the value for s_b_layer_farm_settle.fee_code
     *
     * @mbggenerated
     */
    public void setFeeCode(String feeCode) {
        this.feeCode = feeCode == null ? null : feeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.fee_name
     *
     * @return the value of s_b_layer_farm_settle.fee_name
     *
     * @mbggenerated
     */
    public String getFeeName() {
        return feeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.fee_name
     *
     * @param feeName the value for s_b_layer_farm_settle.fee_name
     *
     * @mbggenerated
     */
    public void setFeeName(String feeName) {
        this.feeName = feeName == null ? null : feeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.company_code
     *
     * @return the value of s_b_layer_farm_settle.company_code
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.company_code
     *
     * @param companyCode the value for s_b_layer_farm_settle.company_code
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.company_name
     *
     * @return the value of s_b_layer_farm_settle.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.company_name
     *
     * @param companyName the value for s_b_layer_farm_settle.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.price_pu
     *
     * @return the value of s_b_layer_farm_settle.price_pu
     *
     * @mbggenerated
     */
    public BigDecimal getPricePu() {
        return pricePu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.price_pu
     *
     * @param pricePu the value for s_b_layer_farm_settle.price_pu
     *
     * @mbggenerated
     */
    public void setPricePu(BigDecimal pricePu) {
        this.pricePu = pricePu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.quentity
     *
     * @return the value of s_b_layer_farm_settle.quentity
     *
     * @mbggenerated
     */
    public Integer getQuentity() {
        return quentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.quentity
     *
     * @param quentity the value for s_b_layer_farm_settle.quentity
     *
     * @mbggenerated
     */
    public void setQuentity(Integer quentity) {
        this.quentity = quentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.weight
     *
     * @return the value of s_b_layer_farm_settle.weight
     *
     * @mbggenerated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.weight
     *
     * @param weight the value for s_b_layer_farm_settle.weight
     *
     * @mbggenerated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.money_sum
     *
     * @return the value of s_b_layer_farm_settle.money_sum
     *
     * @mbggenerated
     */
    public BigDecimal getMoneySum() {
        return moneySum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.money_sum
     *
     * @param moneySum the value for s_b_layer_farm_settle.money_sum
     *
     * @mbggenerated
     */
    public void setMoneySum(BigDecimal moneySum) {
        this.moneySum = moneySum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.bak_var1
     *
     * @return the value of s_b_layer_farm_settle.bak_var1
     *
     * @mbggenerated
     */
    public String getBakVar1() {
        return bakVar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.bak_var1
     *
     * @param bakVar1 the value for s_b_layer_farm_settle.bak_var1
     *
     * @mbggenerated
     */
    public void setBakVar1(String bakVar1) {
        this.bakVar1 = bakVar1 == null ? null : bakVar1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.bak_var2
     *
     * @return the value of s_b_layer_farm_settle.bak_var2
     *
     * @mbggenerated
     */
    public String getBakVar2() {
        return bakVar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.bak_var2
     *
     * @param bakVar2 the value for s_b_layer_farm_settle.bak_var2
     *
     * @mbggenerated
     */
    public void setBakVar2(String bakVar2) {
        this.bakVar2 = bakVar2 == null ? null : bakVar2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.bak_var3
     *
     * @return the value of s_b_layer_farm_settle.bak_var3
     *
     * @mbggenerated
     */
    public String getBakVar3() {
        return bakVar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.bak_var3
     *
     * @param bakVar3 the value for s_b_layer_farm_settle.bak_var3
     *
     * @mbggenerated
     */
    public void setBakVar3(String bakVar3) {
        this.bakVar3 = bakVar3 == null ? null : bakVar3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.bak_num1
     *
     * @return the value of s_b_layer_farm_settle.bak_num1
     *
     * @mbggenerated
     */
    public BigDecimal getBakNum1() {
        return bakNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.bak_num1
     *
     * @param bakNum1 the value for s_b_layer_farm_settle.bak_num1
     *
     * @mbggenerated
     */
    public void setBakNum1(BigDecimal bakNum1) {
        this.bakNum1 = bakNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.bak_num2
     *
     * @return the value of s_b_layer_farm_settle.bak_num2
     *
     * @mbggenerated
     */
    public BigDecimal getBakNum2() {
        return bakNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.bak_num2
     *
     * @param bakNum2 the value for s_b_layer_farm_settle.bak_num2
     *
     * @mbggenerated
     */
    public void setBakNum2(BigDecimal bakNum2) {
        this.bakNum2 = bakNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.bak_num3
     *
     * @return the value of s_b_layer_farm_settle.bak_num3
     *
     * @mbggenerated
     */
    public BigDecimal getBakNum3() {
        return bakNum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.bak_num3
     *
     * @param bakNum3 the value for s_b_layer_farm_settle.bak_num3
     *
     * @mbggenerated
     */
    public void setBakNum3(BigDecimal bakNum3) {
        this.bakNum3 = bakNum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.bak_num4
     *
     * @return the value of s_b_layer_farm_settle.bak_num4
     *
     * @mbggenerated
     */
    public BigDecimal getBakNum4() {
        return bakNum4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.bak_num4
     *
     * @param bakNum4 the value for s_b_layer_farm_settle.bak_num4
     *
     * @mbggenerated
     */
    public void setBakNum4(BigDecimal bakNum4) {
        this.bakNum4 = bakNum4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.bak_num5
     *
     * @return the value of s_b_layer_farm_settle.bak_num5
     *
     * @mbggenerated
     */
    public BigDecimal getBakNum5() {
        return bakNum5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.bak_num5
     *
     * @param bakNum5 the value for s_b_layer_farm_settle.bak_num5
     *
     * @mbggenerated
     */
    public void setBakNum5(BigDecimal bakNum5) {
        this.bakNum5 = bakNum5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.bak_num6
     *
     * @return the value of s_b_layer_farm_settle.bak_num6
     *
     * @mbggenerated
     */
    public BigDecimal getBakNum6() {
        return bakNum6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.bak_num6
     *
     * @param bakNum6 the value for s_b_layer_farm_settle.bak_num6
     *
     * @mbggenerated
     */
    public void setBakNum6(BigDecimal bakNum6) {
        this.bakNum6 = bakNum6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.create_person
     *
     * @return the value of s_b_layer_farm_settle.create_person
     *
     * @mbggenerated
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.create_person
     *
     * @param createPerson the value for s_b_layer_farm_settle.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.create_date
     *
     * @return the value of s_b_layer_farm_settle.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.create_date
     *
     * @param createDate the value for s_b_layer_farm_settle.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.create_time
     *
     * @return the value of s_b_layer_farm_settle.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.create_time
     *
     * @param createTime the value for s_b_layer_farm_settle.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.modify_person
     *
     * @return the value of s_b_layer_farm_settle.modify_person
     *
     * @mbggenerated
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.modify_person
     *
     * @param modifyPerson the value for s_b_layer_farm_settle.modify_person
     *
     * @mbggenerated
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.modify_date
     *
     * @return the value of s_b_layer_farm_settle.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.modify_date
     *
     * @param modifyDate the value for s_b_layer_farm_settle.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_layer_farm_settle.modify_time
     *
     * @return the value of s_b_layer_farm_settle.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_layer_farm_settle.modify_time
     *
     * @param modifyTime the value for s_b_layer_farm_settle.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}