package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SBYincommMain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.mm_sn
     *
     * @mbggenerated
     */
    private String mmSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.make_time
     *
     * @mbggenerated
     */
    private Date makeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.ytdata_time
     *
     * @mbggenerated
     */
    private Date ytdataTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.power_status
     *
     * @mbggenerated
     */
    private String powerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.voltage
     *
     * @mbggenerated
     */
    private BigDecimal voltage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.run_time
     *
     * @mbggenerated
     */
    private Integer runTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.hardware_version
     *
     * @mbggenerated
     */
    private String hardwareVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.software_version
     *
     * @mbggenerated
     */
    private String softwareVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.property
     *
     * @mbggenerated
     */
    private String property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.signal_strength
     *
     * @mbggenerated
     */
    private Integer signalStrength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.device_info
     *
     * @mbggenerated
     */
    private String deviceInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.sim_iccid
     *
     * @mbggenerated
     */
    private String simIccid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.bak1
     *
     * @mbggenerated
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.bak2
     *
     * @mbggenerated
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_main.bak3
     *
     * @mbggenerated
     */
    private String bak3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.mm_sn
     *
     * @return the value of s_b_yincomm_main.mm_sn
     *
     * @mbggenerated
     */
    public String getMmSn() {
        return mmSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.mm_sn
     *
     * @param mmSn the value for s_b_yincomm_main.mm_sn
     *
     * @mbggenerated
     */
    public void setMmSn(String mmSn) {
        this.mmSn = mmSn == null ? null : mmSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.make_time
     *
     * @return the value of s_b_yincomm_main.make_time
     *
     * @mbggenerated
     */
    public Date getMakeTime() {
        return makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.make_time
     *
     * @param makeTime the value for s_b_yincomm_main.make_time
     *
     * @mbggenerated
     */
    public void setMakeTime(Date makeTime) {
        this.makeTime = makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.ytdata_time
     *
     * @return the value of s_b_yincomm_main.ytdata_time
     *
     * @mbggenerated
     */
    public Date getYtdataTime() {
        return ytdataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.ytdata_time
     *
     * @param ytdataTime the value for s_b_yincomm_main.ytdata_time
     *
     * @mbggenerated
     */
    public void setYtdataTime(Date ytdataTime) {
        this.ytdataTime = ytdataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.power_status
     *
     * @return the value of s_b_yincomm_main.power_status
     *
     * @mbggenerated
     */
    public String getPowerStatus() {
        return powerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.power_status
     *
     * @param powerStatus the value for s_b_yincomm_main.power_status
     *
     * @mbggenerated
     */
    public void setPowerStatus(String powerStatus) {
        this.powerStatus = powerStatus == null ? null : powerStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.voltage
     *
     * @return the value of s_b_yincomm_main.voltage
     *
     * @mbggenerated
     */
    public BigDecimal getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.voltage
     *
     * @param voltage the value for s_b_yincomm_main.voltage
     *
     * @mbggenerated
     */
    public void setVoltage(BigDecimal voltage) {
        this.voltage = voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.run_time
     *
     * @return the value of s_b_yincomm_main.run_time
     *
     * @mbggenerated
     */
    public Integer getRunTime() {
        return runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.run_time
     *
     * @param runTime the value for s_b_yincomm_main.run_time
     *
     * @mbggenerated
     */
    public void setRunTime(Integer runTime) {
        this.runTime = runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.hardware_version
     *
     * @return the value of s_b_yincomm_main.hardware_version
     *
     * @mbggenerated
     */
    public String getHardwareVersion() {
        return hardwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.hardware_version
     *
     * @param hardwareVersion the value for s_b_yincomm_main.hardware_version
     *
     * @mbggenerated
     */
    public void setHardwareVersion(String hardwareVersion) {
        this.hardwareVersion = hardwareVersion == null ? null : hardwareVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.software_version
     *
     * @return the value of s_b_yincomm_main.software_version
     *
     * @mbggenerated
     */
    public String getSoftwareVersion() {
        return softwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.software_version
     *
     * @param softwareVersion the value for s_b_yincomm_main.software_version
     *
     * @mbggenerated
     */
    public void setSoftwareVersion(String softwareVersion) {
        this.softwareVersion = softwareVersion == null ? null : softwareVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.property
     *
     * @return the value of s_b_yincomm_main.property
     *
     * @mbggenerated
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.property
     *
     * @param property the value for s_b_yincomm_main.property
     *
     * @mbggenerated
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.signal_strength
     *
     * @return the value of s_b_yincomm_main.signal_strength
     *
     * @mbggenerated
     */
    public Integer getSignalStrength() {
        return signalStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.signal_strength
     *
     * @param signalStrength the value for s_b_yincomm_main.signal_strength
     *
     * @mbggenerated
     */
    public void setSignalStrength(Integer signalStrength) {
        this.signalStrength = signalStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.device_info
     *
     * @return the value of s_b_yincomm_main.device_info
     *
     * @mbggenerated
     */
    public String getDeviceInfo() {
        return deviceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.device_info
     *
     * @param deviceInfo the value for s_b_yincomm_main.device_info
     *
     * @mbggenerated
     */
    public void setDeviceInfo(String deviceInfo) {
        this.deviceInfo = deviceInfo == null ? null : deviceInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.sim_iccid
     *
     * @return the value of s_b_yincomm_main.sim_iccid
     *
     * @mbggenerated
     */
    public String getSimIccid() {
        return simIccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.sim_iccid
     *
     * @param simIccid the value for s_b_yincomm_main.sim_iccid
     *
     * @mbggenerated
     */
    public void setSimIccid(String simIccid) {
        this.simIccid = simIccid == null ? null : simIccid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.bak1
     *
     * @return the value of s_b_yincomm_main.bak1
     *
     * @mbggenerated
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.bak1
     *
     * @param bak1 the value for s_b_yincomm_main.bak1
     *
     * @mbggenerated
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.bak2
     *
     * @return the value of s_b_yincomm_main.bak2
     *
     * @mbggenerated
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.bak2
     *
     * @param bak2 the value for s_b_yincomm_main.bak2
     *
     * @mbggenerated
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_main.bak3
     *
     * @return the value of s_b_yincomm_main.bak3
     *
     * @mbggenerated
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_main.bak3
     *
     * @param bak3 the value for s_b_yincomm_main.bak3
     *
     * @mbggenerated
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }
}