package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SBYincommTrans {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.date_time
     *
     * @mbggenerated
     */
    private Date dateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.mm_sn
     *
     * @mbggenerated
     */
    private String mmSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.proterty
     *
     * @mbggenerated
     */
    private String proterty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.power_status
     *
     * @mbggenerated
     */
    private String powerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.voltage
     *
     * @mbggenerated
     */
    private BigDecimal voltage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.run_time
     *
     * @mbggenerated
     */
    private Integer runTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.hardware_version
     *
     * @mbggenerated
     */
    private String hardwareVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.software_version
     *
     * @mbggenerated
     */
    private String softwareVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_1
     *
     * @mbggenerated
     */
    private BigDecimal temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_2
     *
     * @mbggenerated
     */
    private BigDecimal temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_3
     *
     * @mbggenerated
     */
    private BigDecimal temp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_4
     *
     * @mbggenerated
     */
    private BigDecimal temp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_5
     *
     * @mbggenerated
     */
    private BigDecimal temp5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_6
     *
     * @mbggenerated
     */
    private BigDecimal temp6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_7
     *
     * @mbggenerated
     */
    private BigDecimal temp7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_8
     *
     * @mbggenerated
     */
    private BigDecimal temp8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_9
     *
     * @mbggenerated
     */
    private BigDecimal temp9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_10
     *
     * @mbggenerated
     */
    private BigDecimal temp10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_11
     *
     * @mbggenerated
     */
    private BigDecimal temp11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_12
     *
     * @mbggenerated
     */
    private BigDecimal temp12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_13
     *
     * @mbggenerated
     */
    private BigDecimal temp13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_14
     *
     * @mbggenerated
     */
    private BigDecimal temp14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.temp_15
     *
     * @mbggenerated
     */
    private BigDecimal temp15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.humi_1
     *
     * @mbggenerated
     */
    private BigDecimal humi1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.humi_2
     *
     * @mbggenerated
     */
    private BigDecimal humi2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.humi_3
     *
     * @mbggenerated
     */
    private BigDecimal humi3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.CO2_1
     *
     * @mbggenerated
     */
    private BigDecimal co21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.CO2_2
     *
     * @mbggenerated
     */
    private BigDecimal co22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.CO2_3
     *
     * @mbggenerated
     */
    private BigDecimal co23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.lux_1
     *
     * @mbggenerated
     */
    private BigDecimal lux1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.lux_2
     *
     * @mbggenerated
     */
    private BigDecimal lux2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.lux_3
     *
     * @mbggenerated
     */
    private BigDecimal lux3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.NH4_1
     *
     * @mbggenerated
     */
    private BigDecimal nh41;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.NH4_2
     *
     * @mbggenerated
     */
    private BigDecimal nh42;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.NH4_3
     *
     * @mbggenerated
     */
    private BigDecimal nh43;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.pressure_1
     *
     * @mbggenerated
     */
    private BigDecimal pressure1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.pressure_2
     *
     * @mbggenerated
     */
    private BigDecimal pressure2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_yincomm_trans.pressure_3
     *
     * @mbggenerated
     */
    private BigDecimal pressure3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.id
     *
     * @return the value of s_b_yincomm_trans.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.id
     *
     * @param id the value for s_b_yincomm_trans.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.date_time
     *
     * @return the value of s_b_yincomm_trans.date_time
     *
     * @mbggenerated
     */
    public Date getDateTime() {
        return dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.date_time
     *
     * @param dateTime the value for s_b_yincomm_trans.date_time
     *
     * @mbggenerated
     */
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.mm_sn
     *
     * @return the value of s_b_yincomm_trans.mm_sn
     *
     * @mbggenerated
     */
    public String getMmSn() {
        return mmSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.mm_sn
     *
     * @param mmSn the value for s_b_yincomm_trans.mm_sn
     *
     * @mbggenerated
     */
    public void setMmSn(String mmSn) {
        this.mmSn = mmSn == null ? null : mmSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.proterty
     *
     * @return the value of s_b_yincomm_trans.proterty
     *
     * @mbggenerated
     */
    public String getProterty() {
        return proterty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.proterty
     *
     * @param proterty the value for s_b_yincomm_trans.proterty
     *
     * @mbggenerated
     */
    public void setProterty(String proterty) {
        this.proterty = proterty == null ? null : proterty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.power_status
     *
     * @return the value of s_b_yincomm_trans.power_status
     *
     * @mbggenerated
     */
    public String getPowerStatus() {
        return powerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.power_status
     *
     * @param powerStatus the value for s_b_yincomm_trans.power_status
     *
     * @mbggenerated
     */
    public void setPowerStatus(String powerStatus) {
        this.powerStatus = powerStatus == null ? null : powerStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.voltage
     *
     * @return the value of s_b_yincomm_trans.voltage
     *
     * @mbggenerated
     */
    public BigDecimal getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.voltage
     *
     * @param voltage the value for s_b_yincomm_trans.voltage
     *
     * @mbggenerated
     */
    public void setVoltage(BigDecimal voltage) {
        this.voltage = voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.run_time
     *
     * @return the value of s_b_yincomm_trans.run_time
     *
     * @mbggenerated
     */
    public Integer getRunTime() {
        return runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.run_time
     *
     * @param runTime the value for s_b_yincomm_trans.run_time
     *
     * @mbggenerated
     */
    public void setRunTime(Integer runTime) {
        this.runTime = runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.hardware_version
     *
     * @return the value of s_b_yincomm_trans.hardware_version
     *
     * @mbggenerated
     */
    public String getHardwareVersion() {
        return hardwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.hardware_version
     *
     * @param hardwareVersion the value for s_b_yincomm_trans.hardware_version
     *
     * @mbggenerated
     */
    public void setHardwareVersion(String hardwareVersion) {
        this.hardwareVersion = hardwareVersion == null ? null : hardwareVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.software_version
     *
     * @return the value of s_b_yincomm_trans.software_version
     *
     * @mbggenerated
     */
    public String getSoftwareVersion() {
        return softwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.software_version
     *
     * @param softwareVersion the value for s_b_yincomm_trans.software_version
     *
     * @mbggenerated
     */
    public void setSoftwareVersion(String softwareVersion) {
        this.softwareVersion = softwareVersion == null ? null : softwareVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_1
     *
     * @return the value of s_b_yincomm_trans.temp_1
     *
     * @mbggenerated
     */
    public BigDecimal getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_1
     *
     * @param temp1 the value for s_b_yincomm_trans.temp_1
     *
     * @mbggenerated
     */
    public void setTemp1(BigDecimal temp1) {
        this.temp1 = temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_2
     *
     * @return the value of s_b_yincomm_trans.temp_2
     *
     * @mbggenerated
     */
    public BigDecimal getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_2
     *
     * @param temp2 the value for s_b_yincomm_trans.temp_2
     *
     * @mbggenerated
     */
    public void setTemp2(BigDecimal temp2) {
        this.temp2 = temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_3
     *
     * @return the value of s_b_yincomm_trans.temp_3
     *
     * @mbggenerated
     */
    public BigDecimal getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_3
     *
     * @param temp3 the value for s_b_yincomm_trans.temp_3
     *
     * @mbggenerated
     */
    public void setTemp3(BigDecimal temp3) {
        this.temp3 = temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_4
     *
     * @return the value of s_b_yincomm_trans.temp_4
     *
     * @mbggenerated
     */
    public BigDecimal getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_4
     *
     * @param temp4 the value for s_b_yincomm_trans.temp_4
     *
     * @mbggenerated
     */
    public void setTemp4(BigDecimal temp4) {
        this.temp4 = temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_5
     *
     * @return the value of s_b_yincomm_trans.temp_5
     *
     * @mbggenerated
     */
    public BigDecimal getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_5
     *
     * @param temp5 the value for s_b_yincomm_trans.temp_5
     *
     * @mbggenerated
     */
    public void setTemp5(BigDecimal temp5) {
        this.temp5 = temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_6
     *
     * @return the value of s_b_yincomm_trans.temp_6
     *
     * @mbggenerated
     */
    public BigDecimal getTemp6() {
        return temp6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_6
     *
     * @param temp6 the value for s_b_yincomm_trans.temp_6
     *
     * @mbggenerated
     */
    public void setTemp6(BigDecimal temp6) {
        this.temp6 = temp6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_7
     *
     * @return the value of s_b_yincomm_trans.temp_7
     *
     * @mbggenerated
     */
    public BigDecimal getTemp7() {
        return temp7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_7
     *
     * @param temp7 the value for s_b_yincomm_trans.temp_7
     *
     * @mbggenerated
     */
    public void setTemp7(BigDecimal temp7) {
        this.temp7 = temp7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_8
     *
     * @return the value of s_b_yincomm_trans.temp_8
     *
     * @mbggenerated
     */
    public BigDecimal getTemp8() {
        return temp8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_8
     *
     * @param temp8 the value for s_b_yincomm_trans.temp_8
     *
     * @mbggenerated
     */
    public void setTemp8(BigDecimal temp8) {
        this.temp8 = temp8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_9
     *
     * @return the value of s_b_yincomm_trans.temp_9
     *
     * @mbggenerated
     */
    public BigDecimal getTemp9() {
        return temp9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_9
     *
     * @param temp9 the value for s_b_yincomm_trans.temp_9
     *
     * @mbggenerated
     */
    public void setTemp9(BigDecimal temp9) {
        this.temp9 = temp9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_10
     *
     * @return the value of s_b_yincomm_trans.temp_10
     *
     * @mbggenerated
     */
    public BigDecimal getTemp10() {
        return temp10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_10
     *
     * @param temp10 the value for s_b_yincomm_trans.temp_10
     *
     * @mbggenerated
     */
    public void setTemp10(BigDecimal temp10) {
        this.temp10 = temp10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_11
     *
     * @return the value of s_b_yincomm_trans.temp_11
     *
     * @mbggenerated
     */
    public BigDecimal getTemp11() {
        return temp11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_11
     *
     * @param temp11 the value for s_b_yincomm_trans.temp_11
     *
     * @mbggenerated
     */
    public void setTemp11(BigDecimal temp11) {
        this.temp11 = temp11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_12
     *
     * @return the value of s_b_yincomm_trans.temp_12
     *
     * @mbggenerated
     */
    public BigDecimal getTemp12() {
        return temp12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_12
     *
     * @param temp12 the value for s_b_yincomm_trans.temp_12
     *
     * @mbggenerated
     */
    public void setTemp12(BigDecimal temp12) {
        this.temp12 = temp12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_13
     *
     * @return the value of s_b_yincomm_trans.temp_13
     *
     * @mbggenerated
     */
    public BigDecimal getTemp13() {
        return temp13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_13
     *
     * @param temp13 the value for s_b_yincomm_trans.temp_13
     *
     * @mbggenerated
     */
    public void setTemp13(BigDecimal temp13) {
        this.temp13 = temp13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_14
     *
     * @return the value of s_b_yincomm_trans.temp_14
     *
     * @mbggenerated
     */
    public BigDecimal getTemp14() {
        return temp14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_14
     *
     * @param temp14 the value for s_b_yincomm_trans.temp_14
     *
     * @mbggenerated
     */
    public void setTemp14(BigDecimal temp14) {
        this.temp14 = temp14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.temp_15
     *
     * @return the value of s_b_yincomm_trans.temp_15
     *
     * @mbggenerated
     */
    public BigDecimal getTemp15() {
        return temp15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.temp_15
     *
     * @param temp15 the value for s_b_yincomm_trans.temp_15
     *
     * @mbggenerated
     */
    public void setTemp15(BigDecimal temp15) {
        this.temp15 = temp15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.humi_1
     *
     * @return the value of s_b_yincomm_trans.humi_1
     *
     * @mbggenerated
     */
    public BigDecimal getHumi1() {
        return humi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.humi_1
     *
     * @param humi1 the value for s_b_yincomm_trans.humi_1
     *
     * @mbggenerated
     */
    public void setHumi1(BigDecimal humi1) {
        this.humi1 = humi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.humi_2
     *
     * @return the value of s_b_yincomm_trans.humi_2
     *
     * @mbggenerated
     */
    public BigDecimal getHumi2() {
        return humi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.humi_2
     *
     * @param humi2 the value for s_b_yincomm_trans.humi_2
     *
     * @mbggenerated
     */
    public void setHumi2(BigDecimal humi2) {
        this.humi2 = humi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.humi_3
     *
     * @return the value of s_b_yincomm_trans.humi_3
     *
     * @mbggenerated
     */
    public BigDecimal getHumi3() {
        return humi3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.humi_3
     *
     * @param humi3 the value for s_b_yincomm_trans.humi_3
     *
     * @mbggenerated
     */
    public void setHumi3(BigDecimal humi3) {
        this.humi3 = humi3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.CO2_1
     *
     * @return the value of s_b_yincomm_trans.CO2_1
     *
     * @mbggenerated
     */
    public BigDecimal getCo21() {
        return co21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.CO2_1
     *
     * @param co21 the value for s_b_yincomm_trans.CO2_1
     *
     * @mbggenerated
     */
    public void setCo21(BigDecimal co21) {
        this.co21 = co21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.CO2_2
     *
     * @return the value of s_b_yincomm_trans.CO2_2
     *
     * @mbggenerated
     */
    public BigDecimal getCo22() {
        return co22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.CO2_2
     *
     * @param co22 the value for s_b_yincomm_trans.CO2_2
     *
     * @mbggenerated
     */
    public void setCo22(BigDecimal co22) {
        this.co22 = co22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.CO2_3
     *
     * @return the value of s_b_yincomm_trans.CO2_3
     *
     * @mbggenerated
     */
    public BigDecimal getCo23() {
        return co23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.CO2_3
     *
     * @param co23 the value for s_b_yincomm_trans.CO2_3
     *
     * @mbggenerated
     */
    public void setCo23(BigDecimal co23) {
        this.co23 = co23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.lux_1
     *
     * @return the value of s_b_yincomm_trans.lux_1
     *
     * @mbggenerated
     */
    public BigDecimal getLux1() {
        return lux1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.lux_1
     *
     * @param lux1 the value for s_b_yincomm_trans.lux_1
     *
     * @mbggenerated
     */
    public void setLux1(BigDecimal lux1) {
        this.lux1 = lux1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.lux_2
     *
     * @return the value of s_b_yincomm_trans.lux_2
     *
     * @mbggenerated
     */
    public BigDecimal getLux2() {
        return lux2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.lux_2
     *
     * @param lux2 the value for s_b_yincomm_trans.lux_2
     *
     * @mbggenerated
     */
    public void setLux2(BigDecimal lux2) {
        this.lux2 = lux2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.lux_3
     *
     * @return the value of s_b_yincomm_trans.lux_3
     *
     * @mbggenerated
     */
    public BigDecimal getLux3() {
        return lux3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.lux_3
     *
     * @param lux3 the value for s_b_yincomm_trans.lux_3
     *
     * @mbggenerated
     */
    public void setLux3(BigDecimal lux3) {
        this.lux3 = lux3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.NH4_1
     *
     * @return the value of s_b_yincomm_trans.NH4_1
     *
     * @mbggenerated
     */
    public BigDecimal getNh41() {
        return nh41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.NH4_1
     *
     * @param nh41 the value for s_b_yincomm_trans.NH4_1
     *
     * @mbggenerated
     */
    public void setNh41(BigDecimal nh41) {
        this.nh41 = nh41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.NH4_2
     *
     * @return the value of s_b_yincomm_trans.NH4_2
     *
     * @mbggenerated
     */
    public BigDecimal getNh42() {
        return nh42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.NH4_2
     *
     * @param nh42 the value for s_b_yincomm_trans.NH4_2
     *
     * @mbggenerated
     */
    public void setNh42(BigDecimal nh42) {
        this.nh42 = nh42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.NH4_3
     *
     * @return the value of s_b_yincomm_trans.NH4_3
     *
     * @mbggenerated
     */
    public BigDecimal getNh43() {
        return nh43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.NH4_3
     *
     * @param nh43 the value for s_b_yincomm_trans.NH4_3
     *
     * @mbggenerated
     */
    public void setNh43(BigDecimal nh43) {
        this.nh43 = nh43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.pressure_1
     *
     * @return the value of s_b_yincomm_trans.pressure_1
     *
     * @mbggenerated
     */
    public BigDecimal getPressure1() {
        return pressure1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.pressure_1
     *
     * @param pressure1 the value for s_b_yincomm_trans.pressure_1
     *
     * @mbggenerated
     */
    public void setPressure1(BigDecimal pressure1) {
        this.pressure1 = pressure1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.pressure_2
     *
     * @return the value of s_b_yincomm_trans.pressure_2
     *
     * @mbggenerated
     */
    public BigDecimal getPressure2() {
        return pressure2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.pressure_2
     *
     * @param pressure2 the value for s_b_yincomm_trans.pressure_2
     *
     * @mbggenerated
     */
    public void setPressure2(BigDecimal pressure2) {
        this.pressure2 = pressure2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_yincomm_trans.pressure_3
     *
     * @return the value of s_b_yincomm_trans.pressure_3
     *
     * @mbggenerated
     */
    public BigDecimal getPressure3() {
        return pressure3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_yincomm_trans.pressure_3
     *
     * @param pressure3 the value for s_b_yincomm_trans.pressure_3
     *
     * @mbggenerated
     */
    public void setPressure3(BigDecimal pressure3) {
        this.pressure3 = pressure3;
    }
}