package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SDHouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.house_code
     *
     * @mbggenerated
     */
    private String houseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.house_name
     *
     * @mbggenerated
     */
    private String houseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.farm_id
     *
     * @mbggenerated
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.feed_density
     *
     * @mbggenerated
     */
    private BigDecimal feedDensity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.house_length
     *
     * @mbggenerated
     */
    private BigDecimal houseLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.house_width
     *
     * @mbggenerated
     */
    private BigDecimal houseWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.house_height
     *
     * @mbggenerated
     */
    private BigDecimal houseHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.memo_1
     *
     * @mbggenerated
     */
    private String memo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.memo_2
     *
     * @mbggenerated
     */
    private String memo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.freeze_status
     *
     * @mbggenerated
     */
    private String freezeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.create_person
     *
     * @mbggenerated
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.modify_person
     *
     * @mbggenerated
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_house.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.id
     *
     * @return the value of s_d_house.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.id
     *
     * @param id the value for s_d_house.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.house_code
     *
     * @return the value of s_d_house.house_code
     *
     * @mbggenerated
     */
    public String getHouseCode() {
        return houseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.house_code
     *
     * @param houseCode the value for s_d_house.house_code
     *
     * @mbggenerated
     */
    public void setHouseCode(String houseCode) {
        this.houseCode = houseCode == null ? null : houseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.house_name
     *
     * @return the value of s_d_house.house_name
     *
     * @mbggenerated
     */
    public String getHouseName() {
        return houseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.house_name
     *
     * @param houseName the value for s_d_house.house_name
     *
     * @mbggenerated
     */
    public void setHouseName(String houseName) {
        this.houseName = houseName == null ? null : houseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.farm_id
     *
     * @return the value of s_d_house.farm_id
     *
     * @mbggenerated
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.farm_id
     *
     * @param farmId the value for s_d_house.farm_id
     *
     * @mbggenerated
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.feed_density
     *
     * @return the value of s_d_house.feed_density
     *
     * @mbggenerated
     */
    public BigDecimal getFeedDensity() {
        return feedDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.feed_density
     *
     * @param feedDensity the value for s_d_house.feed_density
     *
     * @mbggenerated
     */
    public void setFeedDensity(BigDecimal feedDensity) {
        this.feedDensity = feedDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.house_length
     *
     * @return the value of s_d_house.house_length
     *
     * @mbggenerated
     */
    public BigDecimal getHouseLength() {
        return houseLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.house_length
     *
     * @param houseLength the value for s_d_house.house_length
     *
     * @mbggenerated
     */
    public void setHouseLength(BigDecimal houseLength) {
        this.houseLength = houseLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.house_width
     *
     * @return the value of s_d_house.house_width
     *
     * @mbggenerated
     */
    public BigDecimal getHouseWidth() {
        return houseWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.house_width
     *
     * @param houseWidth the value for s_d_house.house_width
     *
     * @mbggenerated
     */
    public void setHouseWidth(BigDecimal houseWidth) {
        this.houseWidth = houseWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.house_height
     *
     * @return the value of s_d_house.house_height
     *
     * @mbggenerated
     */
    public BigDecimal getHouseHeight() {
        return houseHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.house_height
     *
     * @param houseHeight the value for s_d_house.house_height
     *
     * @mbggenerated
     */
    public void setHouseHeight(BigDecimal houseHeight) {
        this.houseHeight = houseHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.memo_1
     *
     * @return the value of s_d_house.memo_1
     *
     * @mbggenerated
     */
    public String getMemo1() {
        return memo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.memo_1
     *
     * @param memo1 the value for s_d_house.memo_1
     *
     * @mbggenerated
     */
    public void setMemo1(String memo1) {
        this.memo1 = memo1 == null ? null : memo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.memo_2
     *
     * @return the value of s_d_house.memo_2
     *
     * @mbggenerated
     */
    public String getMemo2() {
        return memo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.memo_2
     *
     * @param memo2 the value for s_d_house.memo_2
     *
     * @mbggenerated
     */
    public void setMemo2(String memo2) {
        this.memo2 = memo2 == null ? null : memo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.freeze_status
     *
     * @return the value of s_d_house.freeze_status
     *
     * @mbggenerated
     */
    public String getFreezeStatus() {
        return freezeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.freeze_status
     *
     * @param freezeStatus the value for s_d_house.freeze_status
     *
     * @mbggenerated
     */
    public void setFreezeStatus(String freezeStatus) {
        this.freezeStatus = freezeStatus == null ? null : freezeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.create_person
     *
     * @return the value of s_d_house.create_person
     *
     * @mbggenerated
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.create_person
     *
     * @param createPerson the value for s_d_house.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.create_date
     *
     * @return the value of s_d_house.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.create_date
     *
     * @param createDate the value for s_d_house.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.create_time
     *
     * @return the value of s_d_house.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.create_time
     *
     * @param createTime the value for s_d_house.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.modify_person
     *
     * @return the value of s_d_house.modify_person
     *
     * @mbggenerated
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.modify_person
     *
     * @param modifyPerson the value for s_d_house.modify_person
     *
     * @mbggenerated
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.modify_date
     *
     * @return the value of s_d_house.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.modify_date
     *
     * @param modifyDate the value for s_d_house.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_house.modify_time
     *
     * @return the value of s_d_house.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_house.modify_time
     *
     * @param modifyTime the value for s_d_house.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}