package com.mtc.entity.app;

import java.math.BigDecimal;
import java.util.Date;

public class SDLayerChickenStandar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.farm_id
     *
     * @mbggenerated
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.day_age
     *
     * @mbggenerated
     */
    private Integer dayAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.week_age
     *
     * @mbggenerated
     */
    private Integer weekAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.type1
     *
     * @mbggenerated
     */
    private String type1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.day_lay_rate_max
     *
     * @mbggenerated
     */
    private BigDecimal dayLayRateMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.day_lay_rate_min
     *
     * @mbggenerated
     */
    private BigDecimal dayLayRateMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.acc_cur_lay_max
     *
     * @mbggenerated
     */
    private BigDecimal accCurLayMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.acc_cur_lay_min
     *
     * @mbggenerated
     */
    private BigDecimal accCurLayMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.acc_ori_lay_max
     *
     * @mbggenerated
     */
    private BigDecimal accOriLayMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.acc_ori_lay_min
     *
     * @mbggenerated
     */
    private BigDecimal accOriLayMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.acc_cd_rate
     *
     * @mbggenerated
     */
    private BigDecimal accCdRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.chicken_weight_max
     *
     * @mbggenerated
     */
    private BigDecimal chickenWeightMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.chicken_weight_min
     *
     * @mbggenerated
     */
    private BigDecimal chickenWeightMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.day_feed_max
     *
     * @mbggenerated
     */
    private BigDecimal dayFeedMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.day_feed_min
     *
     * @mbggenerated
     */
    private BigDecimal dayFeedMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.acc_ori_lay_weight
     *
     * @mbggenerated
     */
    private BigDecimal accOriLayWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.lay_weight_max
     *
     * @mbggenerated
     */
    private BigDecimal layWeightMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.lay_weight_min
     *
     * @mbggenerated
     */
    private BigDecimal layWeightMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.num_bak1
     *
     * @mbggenerated
     */
    private BigDecimal numBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.num_bak2
     *
     * @mbggenerated
     */
    private BigDecimal numBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.num_bak3
     *
     * @mbggenerated
     */
    private BigDecimal numBak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.create_person
     *
     * @mbggenerated
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.modify_person
     *
     * @mbggenerated
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_layer_chicken_standar.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.id
     *
     * @return the value of s_d_layer_chicken_standar.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.id
     *
     * @param id the value for s_d_layer_chicken_standar.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.farm_id
     *
     * @return the value of s_d_layer_chicken_standar.farm_id
     *
     * @mbggenerated
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.farm_id
     *
     * @param farmId the value for s_d_layer_chicken_standar.farm_id
     *
     * @mbggenerated
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.day_age
     *
     * @return the value of s_d_layer_chicken_standar.day_age
     *
     * @mbggenerated
     */
    public Integer getDayAge() {
        return dayAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.day_age
     *
     * @param dayAge the value for s_d_layer_chicken_standar.day_age
     *
     * @mbggenerated
     */
    public void setDayAge(Integer dayAge) {
        this.dayAge = dayAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.week_age
     *
     * @return the value of s_d_layer_chicken_standar.week_age
     *
     * @mbggenerated
     */
    public Integer getWeekAge() {
        return weekAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.week_age
     *
     * @param weekAge the value for s_d_layer_chicken_standar.week_age
     *
     * @mbggenerated
     */
    public void setWeekAge(Integer weekAge) {
        this.weekAge = weekAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.type1
     *
     * @return the value of s_d_layer_chicken_standar.type1
     *
     * @mbggenerated
     */
    public String getType1() {
        return type1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.type1
     *
     * @param type1 the value for s_d_layer_chicken_standar.type1
     *
     * @mbggenerated
     */
    public void setType1(String type1) {
        this.type1 = type1 == null ? null : type1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.day_lay_rate_max
     *
     * @return the value of s_d_layer_chicken_standar.day_lay_rate_max
     *
     * @mbggenerated
     */
    public BigDecimal getDayLayRateMax() {
        return dayLayRateMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.day_lay_rate_max
     *
     * @param dayLayRateMax the value for s_d_layer_chicken_standar.day_lay_rate_max
     *
     * @mbggenerated
     */
    public void setDayLayRateMax(BigDecimal dayLayRateMax) {
        this.dayLayRateMax = dayLayRateMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.day_lay_rate_min
     *
     * @return the value of s_d_layer_chicken_standar.day_lay_rate_min
     *
     * @mbggenerated
     */
    public BigDecimal getDayLayRateMin() {
        return dayLayRateMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.day_lay_rate_min
     *
     * @param dayLayRateMin the value for s_d_layer_chicken_standar.day_lay_rate_min
     *
     * @mbggenerated
     */
    public void setDayLayRateMin(BigDecimal dayLayRateMin) {
        this.dayLayRateMin = dayLayRateMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.acc_cur_lay_max
     *
     * @return the value of s_d_layer_chicken_standar.acc_cur_lay_max
     *
     * @mbggenerated
     */
    public BigDecimal getAccCurLayMax() {
        return accCurLayMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.acc_cur_lay_max
     *
     * @param accCurLayMax the value for s_d_layer_chicken_standar.acc_cur_lay_max
     *
     * @mbggenerated
     */
    public void setAccCurLayMax(BigDecimal accCurLayMax) {
        this.accCurLayMax = accCurLayMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.acc_cur_lay_min
     *
     * @return the value of s_d_layer_chicken_standar.acc_cur_lay_min
     *
     * @mbggenerated
     */
    public BigDecimal getAccCurLayMin() {
        return accCurLayMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.acc_cur_lay_min
     *
     * @param accCurLayMin the value for s_d_layer_chicken_standar.acc_cur_lay_min
     *
     * @mbggenerated
     */
    public void setAccCurLayMin(BigDecimal accCurLayMin) {
        this.accCurLayMin = accCurLayMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.acc_ori_lay_max
     *
     * @return the value of s_d_layer_chicken_standar.acc_ori_lay_max
     *
     * @mbggenerated
     */
    public BigDecimal getAccOriLayMax() {
        return accOriLayMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.acc_ori_lay_max
     *
     * @param accOriLayMax the value for s_d_layer_chicken_standar.acc_ori_lay_max
     *
     * @mbggenerated
     */
    public void setAccOriLayMax(BigDecimal accOriLayMax) {
        this.accOriLayMax = accOriLayMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.acc_ori_lay_min
     *
     * @return the value of s_d_layer_chicken_standar.acc_ori_lay_min
     *
     * @mbggenerated
     */
    public BigDecimal getAccOriLayMin() {
        return accOriLayMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.acc_ori_lay_min
     *
     * @param accOriLayMin the value for s_d_layer_chicken_standar.acc_ori_lay_min
     *
     * @mbggenerated
     */
    public void setAccOriLayMin(BigDecimal accOriLayMin) {
        this.accOriLayMin = accOriLayMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.acc_cd_rate
     *
     * @return the value of s_d_layer_chicken_standar.acc_cd_rate
     *
     * @mbggenerated
     */
    public BigDecimal getAccCdRate() {
        return accCdRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.acc_cd_rate
     *
     * @param accCdRate the value for s_d_layer_chicken_standar.acc_cd_rate
     *
     * @mbggenerated
     */
    public void setAccCdRate(BigDecimal accCdRate) {
        this.accCdRate = accCdRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.chicken_weight_max
     *
     * @return the value of s_d_layer_chicken_standar.chicken_weight_max
     *
     * @mbggenerated
     */
    public BigDecimal getChickenWeightMax() {
        return chickenWeightMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.chicken_weight_max
     *
     * @param chickenWeightMax the value for s_d_layer_chicken_standar.chicken_weight_max
     *
     * @mbggenerated
     */
    public void setChickenWeightMax(BigDecimal chickenWeightMax) {
        this.chickenWeightMax = chickenWeightMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.chicken_weight_min
     *
     * @return the value of s_d_layer_chicken_standar.chicken_weight_min
     *
     * @mbggenerated
     */
    public BigDecimal getChickenWeightMin() {
        return chickenWeightMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.chicken_weight_min
     *
     * @param chickenWeightMin the value for s_d_layer_chicken_standar.chicken_weight_min
     *
     * @mbggenerated
     */
    public void setChickenWeightMin(BigDecimal chickenWeightMin) {
        this.chickenWeightMin = chickenWeightMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.day_feed_max
     *
     * @return the value of s_d_layer_chicken_standar.day_feed_max
     *
     * @mbggenerated
     */
    public BigDecimal getDayFeedMax() {
        return dayFeedMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.day_feed_max
     *
     * @param dayFeedMax the value for s_d_layer_chicken_standar.day_feed_max
     *
     * @mbggenerated
     */
    public void setDayFeedMax(BigDecimal dayFeedMax) {
        this.dayFeedMax = dayFeedMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.day_feed_min
     *
     * @return the value of s_d_layer_chicken_standar.day_feed_min
     *
     * @mbggenerated
     */
    public BigDecimal getDayFeedMin() {
        return dayFeedMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.day_feed_min
     *
     * @param dayFeedMin the value for s_d_layer_chicken_standar.day_feed_min
     *
     * @mbggenerated
     */
    public void setDayFeedMin(BigDecimal dayFeedMin) {
        this.dayFeedMin = dayFeedMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.acc_ori_lay_weight
     *
     * @return the value of s_d_layer_chicken_standar.acc_ori_lay_weight
     *
     * @mbggenerated
     */
    public BigDecimal getAccOriLayWeight() {
        return accOriLayWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.acc_ori_lay_weight
     *
     * @param accOriLayWeight the value for s_d_layer_chicken_standar.acc_ori_lay_weight
     *
     * @mbggenerated
     */
    public void setAccOriLayWeight(BigDecimal accOriLayWeight) {
        this.accOriLayWeight = accOriLayWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.lay_weight_max
     *
     * @return the value of s_d_layer_chicken_standar.lay_weight_max
     *
     * @mbggenerated
     */
    public BigDecimal getLayWeightMax() {
        return layWeightMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.lay_weight_max
     *
     * @param layWeightMax the value for s_d_layer_chicken_standar.lay_weight_max
     *
     * @mbggenerated
     */
    public void setLayWeightMax(BigDecimal layWeightMax) {
        this.layWeightMax = layWeightMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.lay_weight_min
     *
     * @return the value of s_d_layer_chicken_standar.lay_weight_min
     *
     * @mbggenerated
     */
    public BigDecimal getLayWeightMin() {
        return layWeightMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.lay_weight_min
     *
     * @param layWeightMin the value for s_d_layer_chicken_standar.lay_weight_min
     *
     * @mbggenerated
     */
    public void setLayWeightMin(BigDecimal layWeightMin) {
        this.layWeightMin = layWeightMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.num_bak1
     *
     * @return the value of s_d_layer_chicken_standar.num_bak1
     *
     * @mbggenerated
     */
    public BigDecimal getNumBak1() {
        return numBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.num_bak1
     *
     * @param numBak1 the value for s_d_layer_chicken_standar.num_bak1
     *
     * @mbggenerated
     */
    public void setNumBak1(BigDecimal numBak1) {
        this.numBak1 = numBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.num_bak2
     *
     * @return the value of s_d_layer_chicken_standar.num_bak2
     *
     * @mbggenerated
     */
    public BigDecimal getNumBak2() {
        return numBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.num_bak2
     *
     * @param numBak2 the value for s_d_layer_chicken_standar.num_bak2
     *
     * @mbggenerated
     */
    public void setNumBak2(BigDecimal numBak2) {
        this.numBak2 = numBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.num_bak3
     *
     * @return the value of s_d_layer_chicken_standar.num_bak3
     *
     * @mbggenerated
     */
    public BigDecimal getNumBak3() {
        return numBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.num_bak3
     *
     * @param numBak3 the value for s_d_layer_chicken_standar.num_bak3
     *
     * @mbggenerated
     */
    public void setNumBak3(BigDecimal numBak3) {
        this.numBak3 = numBak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.create_person
     *
     * @return the value of s_d_layer_chicken_standar.create_person
     *
     * @mbggenerated
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.create_person
     *
     * @param createPerson the value for s_d_layer_chicken_standar.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.create_date
     *
     * @return the value of s_d_layer_chicken_standar.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.create_date
     *
     * @param createDate the value for s_d_layer_chicken_standar.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.create_time
     *
     * @return the value of s_d_layer_chicken_standar.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.create_time
     *
     * @param createTime the value for s_d_layer_chicken_standar.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.modify_person
     *
     * @return the value of s_d_layer_chicken_standar.modify_person
     *
     * @mbggenerated
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.modify_person
     *
     * @param modifyPerson the value for s_d_layer_chicken_standar.modify_person
     *
     * @mbggenerated
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.modify_date
     *
     * @return the value of s_d_layer_chicken_standar.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.modify_date
     *
     * @param modifyDate the value for s_d_layer_chicken_standar.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_layer_chicken_standar.modify_time
     *
     * @return the value of s_d_layer_chicken_standar.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_layer_chicken_standar.modify_time
     *
     * @param modifyTime the value for s_d_layer_chicken_standar.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}