package com.mtc.entity.app;

import java.util.Date;

public class SLJpushLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.tag_name
     *
     * @mbggenerated
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.house_id
     *
     * @mbggenerated
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.alarm_id
     *
     * @mbggenerated
     */
    private Integer alarmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.jg_push_time
     *
     * @mbggenerated
     */
    private Date jgPushTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.jg_res
     *
     * @mbggenerated
     */
    private String jgRes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.jg_message
     *
     * @mbggenerated
     */
    private String jgMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.mi_push_time
     *
     * @mbggenerated
     */
    private Date miPushTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.mi_res
     *
     * @mbggenerated
     */
    private String miRes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.mi_message
     *
     * @mbggenerated
     */
    private String miMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.oth1_push_time
     *
     * @mbggenerated
     */
    private Date oth1PushTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.oth1_result
     *
     * @mbggenerated
     */
    private String oth1Result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.oth1_message
     *
     * @mbggenerated
     */
    private String oth1Message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.oth2_push_time
     *
     * @mbggenerated
     */
    private Date oth2PushTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.oth2_result
     *
     * @mbggenerated
     */
    private String oth2Result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.oth2_message
     *
     * @mbggenerated
     */
    private String oth2Message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.oth3_push_time
     *
     * @mbggenerated
     */
    private Date oth3PushTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.oth3_result
     *
     * @mbggenerated
     */
    private String oth3Result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.oth3_message
     *
     * @mbggenerated
     */
    private String oth3Message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.make_date
     *
     * @mbggenerated
     */
    private Date makeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_jpush_log.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.id
     *
     * @return the value of s_l_jpush_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.id
     *
     * @param id the value for s_l_jpush_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.tag_name
     *
     * @return the value of s_l_jpush_log.tag_name
     *
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.tag_name
     *
     * @param tagName the value for s_l_jpush_log.tag_name
     *
     * @mbggenerated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.house_id
     *
     * @return the value of s_l_jpush_log.house_id
     *
     * @mbggenerated
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.house_id
     *
     * @param houseId the value for s_l_jpush_log.house_id
     *
     * @mbggenerated
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.alarm_id
     *
     * @return the value of s_l_jpush_log.alarm_id
     *
     * @mbggenerated
     */
    public Integer getAlarmId() {
        return alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.alarm_id
     *
     * @param alarmId the value for s_l_jpush_log.alarm_id
     *
     * @mbggenerated
     */
    public void setAlarmId(Integer alarmId) {
        this.alarmId = alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.content
     *
     * @return the value of s_l_jpush_log.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.content
     *
     * @param content the value for s_l_jpush_log.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.jg_push_time
     *
     * @return the value of s_l_jpush_log.jg_push_time
     *
     * @mbggenerated
     */
    public Date getJgPushTime() {
        return jgPushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.jg_push_time
     *
     * @param jgPushTime the value for s_l_jpush_log.jg_push_time
     *
     * @mbggenerated
     */
    public void setJgPushTime(Date jgPushTime) {
        this.jgPushTime = jgPushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.jg_res
     *
     * @return the value of s_l_jpush_log.jg_res
     *
     * @mbggenerated
     */
    public String getJgRes() {
        return jgRes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.jg_res
     *
     * @param jgRes the value for s_l_jpush_log.jg_res
     *
     * @mbggenerated
     */
    public void setJgRes(String jgRes) {
        this.jgRes = jgRes == null ? null : jgRes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.jg_message
     *
     * @return the value of s_l_jpush_log.jg_message
     *
     * @mbggenerated
     */
    public String getJgMessage() {
        return jgMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.jg_message
     *
     * @param jgMessage the value for s_l_jpush_log.jg_message
     *
     * @mbggenerated
     */
    public void setJgMessage(String jgMessage) {
        this.jgMessage = jgMessage == null ? null : jgMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.mi_push_time
     *
     * @return the value of s_l_jpush_log.mi_push_time
     *
     * @mbggenerated
     */
    public Date getMiPushTime() {
        return miPushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.mi_push_time
     *
     * @param miPushTime the value for s_l_jpush_log.mi_push_time
     *
     * @mbggenerated
     */
    public void setMiPushTime(Date miPushTime) {
        this.miPushTime = miPushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.mi_res
     *
     * @return the value of s_l_jpush_log.mi_res
     *
     * @mbggenerated
     */
    public String getMiRes() {
        return miRes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.mi_res
     *
     * @param miRes the value for s_l_jpush_log.mi_res
     *
     * @mbggenerated
     */
    public void setMiRes(String miRes) {
        this.miRes = miRes == null ? null : miRes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.mi_message
     *
     * @return the value of s_l_jpush_log.mi_message
     *
     * @mbggenerated
     */
    public String getMiMessage() {
        return miMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.mi_message
     *
     * @param miMessage the value for s_l_jpush_log.mi_message
     *
     * @mbggenerated
     */
    public void setMiMessage(String miMessage) {
        this.miMessage = miMessage == null ? null : miMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.oth1_push_time
     *
     * @return the value of s_l_jpush_log.oth1_push_time
     *
     * @mbggenerated
     */
    public Date getOth1PushTime() {
        return oth1PushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.oth1_push_time
     *
     * @param oth1PushTime the value for s_l_jpush_log.oth1_push_time
     *
     * @mbggenerated
     */
    public void setOth1PushTime(Date oth1PushTime) {
        this.oth1PushTime = oth1PushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.oth1_result
     *
     * @return the value of s_l_jpush_log.oth1_result
     *
     * @mbggenerated
     */
    public String getOth1Result() {
        return oth1Result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.oth1_result
     *
     * @param oth1Result the value for s_l_jpush_log.oth1_result
     *
     * @mbggenerated
     */
    public void setOth1Result(String oth1Result) {
        this.oth1Result = oth1Result == null ? null : oth1Result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.oth1_message
     *
     * @return the value of s_l_jpush_log.oth1_message
     *
     * @mbggenerated
     */
    public String getOth1Message() {
        return oth1Message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.oth1_message
     *
     * @param oth1Message the value for s_l_jpush_log.oth1_message
     *
     * @mbggenerated
     */
    public void setOth1Message(String oth1Message) {
        this.oth1Message = oth1Message == null ? null : oth1Message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.oth2_push_time
     *
     * @return the value of s_l_jpush_log.oth2_push_time
     *
     * @mbggenerated
     */
    public Date getOth2PushTime() {
        return oth2PushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.oth2_push_time
     *
     * @param oth2PushTime the value for s_l_jpush_log.oth2_push_time
     *
     * @mbggenerated
     */
    public void setOth2PushTime(Date oth2PushTime) {
        this.oth2PushTime = oth2PushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.oth2_result
     *
     * @return the value of s_l_jpush_log.oth2_result
     *
     * @mbggenerated
     */
    public String getOth2Result() {
        return oth2Result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.oth2_result
     *
     * @param oth2Result the value for s_l_jpush_log.oth2_result
     *
     * @mbggenerated
     */
    public void setOth2Result(String oth2Result) {
        this.oth2Result = oth2Result == null ? null : oth2Result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.oth2_message
     *
     * @return the value of s_l_jpush_log.oth2_message
     *
     * @mbggenerated
     */
    public String getOth2Message() {
        return oth2Message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.oth2_message
     *
     * @param oth2Message the value for s_l_jpush_log.oth2_message
     *
     * @mbggenerated
     */
    public void setOth2Message(String oth2Message) {
        this.oth2Message = oth2Message == null ? null : oth2Message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.oth3_push_time
     *
     * @return the value of s_l_jpush_log.oth3_push_time
     *
     * @mbggenerated
     */
    public Date getOth3PushTime() {
        return oth3PushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.oth3_push_time
     *
     * @param oth3PushTime the value for s_l_jpush_log.oth3_push_time
     *
     * @mbggenerated
     */
    public void setOth3PushTime(Date oth3PushTime) {
        this.oth3PushTime = oth3PushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.oth3_result
     *
     * @return the value of s_l_jpush_log.oth3_result
     *
     * @mbggenerated
     */
    public String getOth3Result() {
        return oth3Result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.oth3_result
     *
     * @param oth3Result the value for s_l_jpush_log.oth3_result
     *
     * @mbggenerated
     */
    public void setOth3Result(String oth3Result) {
        this.oth3Result = oth3Result == null ? null : oth3Result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.oth3_message
     *
     * @return the value of s_l_jpush_log.oth3_message
     *
     * @mbggenerated
     */
    public String getOth3Message() {
        return oth3Message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.oth3_message
     *
     * @param oth3Message the value for s_l_jpush_log.oth3_message
     *
     * @mbggenerated
     */
    public void setOth3Message(String oth3Message) {
        this.oth3Message = oth3Message == null ? null : oth3Message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.make_date
     *
     * @return the value of s_l_jpush_log.make_date
     *
     * @mbggenerated
     */
    public Date getMakeDate() {
        return makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.make_date
     *
     * @param makeDate the value for s_l_jpush_log.make_date
     *
     * @mbggenerated
     */
    public void setMakeDate(Date makeDate) {
        this.makeDate = makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_jpush_log.modify_date
     *
     * @return the value of s_l_jpush_log.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_jpush_log.modify_date
     *
     * @param modifyDate the value for s_l_jpush_log.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}